// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: backfill.sql

package dbgen

import (
	"context"
)

const advanceBackfillCursor = `-- name: AdvanceBackfillCursor :one
UPDATE backfill_cursors
SET phase = $1,
    page = $2,
    completed_at = CASE
        WHEN $1::text = 'done' THEN now()
        ELSE NULL
    END,
    updated_at = now()
WHERE installation_id = $3
  AND repo_full_name = $4
  AND phase = $5
  AND page = $6
RETURNING installation_id, repo_full_name, phase, page, completed_at, updated_at
`

type AdvanceBackfillCursorParams struct {
	NextPhase      string
	NextPage       int32
	InstallationID int64
	RepoFullName   string
	ExpectedPhase  string
	ExpectedPage   int32
}

func (q *Queries) AdvanceBackfillCursor(ctx context.Context, arg AdvanceBackfillCursorParams) (BackfillCursor, error) {
	row := q.db.QueryRow(ctx, advanceBackfillCursor,
		arg.NextPhase,
		arg.NextPage,
		arg.InstallationID,
		arg.RepoFullName,
		arg.ExpectedPhase,
		arg.ExpectedPage,
	)
	var i BackfillCursor
	err := row.Scan(
		&i.InstallationID,
		&i.RepoFullName,
		&i.Phase,
		&i.Page,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const ensureBackfillCursor = `-- name: EnsureBackfillCursor :one
INSERT INTO backfill_cursors (
    installation_id, repo_full_name, phase, page
) VALUES (
    $1, $2, 'repository', 1
)
ON CONFLICT (installation_id, repo_full_name) DO UPDATE
SET updated_at = backfill_cursors.updated_at
RETURNING installation_id, repo_full_name, phase, page, completed_at, updated_at
`

type EnsureBackfillCursorParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) EnsureBackfillCursor(ctx context.Context, arg EnsureBackfillCursorParams) (BackfillCursor, error) {
	row := q.db.QueryRow(ctx, ensureBackfillCursor, arg.InstallationID, arg.RepoFullName)
	var i BackfillCursor
	err := row.Scan(
		&i.InstallationID,
		&i.RepoFullName,
		&i.Phase,
		&i.Page,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackfillCursor = `-- name: GetBackfillCursor :one
SELECT installation_id, repo_full_name, phase, page, completed_at, updated_at
FROM backfill_cursors
WHERE installation_id = $1
  AND repo_full_name = $2
`

type GetBackfillCursorParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) GetBackfillCursor(ctx context.Context, arg GetBackfillCursorParams) (BackfillCursor, error) {
	row := q.db.QueryRow(ctx, getBackfillCursor, arg.InstallationID, arg.RepoFullName)
	var i BackfillCursor
	err := row.Scan(
		&i.InstallationID,
		&i.RepoFullName,
		&i.Phase,
		&i.Page,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBackfillCursorForUpdate = `-- name: GetBackfillCursorForUpdate :one
SELECT installation_id, repo_full_name, phase, page, completed_at, updated_at
FROM backfill_cursors
WHERE installation_id = $1
  AND repo_full_name = $2
FOR UPDATE
`

type GetBackfillCursorForUpdateParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) GetBackfillCursorForUpdate(ctx context.Context, arg GetBackfillCursorForUpdateParams) (BackfillCursor, error) {
	row := q.db.QueryRow(ctx, getBackfillCursorForUpdate, arg.InstallationID, arg.RepoFullName)
	var i BackfillCursor
	err := row.Scan(
		&i.InstallationID,
		&i.RepoFullName,
		&i.Phase,
		&i.Page,
		&i.CompletedAt,
		&i.UpdatedAt,
	)
	return i, err
}
