// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: branch.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceBranchReconciliationTargetGenerations = `-- name: AdvanceBranchReconciliationTargetGenerations :many
WITH repository AS MATERIALIZED (
    SELECT repos.id, repos.installation_id, repos.gh_id,
           repos.default_branch
    FROM repos
    JOIN repo_aliases ON repo_aliases.repo_id = repos.id
    WHERE repo_aliases.full_name = $1
      AND repos.tombstoned_at IS NULL
    LIMIT 1
), page_targets AS (
    SELECT 'refresh_pr'::text AS refresh_kind,
           ('pr:' || $1::text || ':' ||
            pull_requests.number::text)::text AS refresh_key,
           ('pr:' || repository.installation_id::text || ':' ||
            repository.gh_id::text || ':' ||
            pull_requests.number::text)::text AS entity_key,
           true AS page_target
    FROM repository
    JOIN pull_requests ON pull_requests.repo_id = repository.id
    WHERE pull_requests.tombstoned_at IS NULL
      AND pull_requests.state = 'open'
      AND (
          pull_requests.head_ref = $2
          OR pull_requests.base_ref = $2
      )

    UNION

    SELECT 'refresh_stack'::text,
           ('stack:' || $1::text || ':' ||
            stacks.number::text)::text,
           ('stack:' || repository.installation_id::text || ':' ||
            repository.gh_id::text || ':' || stacks.number::text)::text,
           true
    FROM repository
    JOIN stacks ON stacks.repo_id = repository.id
    WHERE stacks.tombstoned_at IS NULL
      AND (
          stacks.base_ref = $2
          OR EXISTS (
              SELECT 1
              FROM jsonb_array_elements(stacks.entries) AS entry
              WHERE entry->>'head_ref' = $2
          )
      )
), generation_targets AS (
    SELECT page_targets.refresh_kind, page_targets.refresh_key
    FROM page_targets

    UNION

    SELECT 'refresh_repository'::text,
           ('repo:' || $1::text || ':metadata')::text
    FROM repository
    WHERE repository.default_branch = $2
), advanced AS (
    INSERT INTO refresh_intent_generations (
        kind, refresh_key, generation, completed_generation,
        deadline_at, event_received_at, updated_at
    )
    SELECT generation_targets.refresh_kind,
           generation_targets.refresh_key,
           1, 1, NULL, NULL, $3
    FROM generation_targets
    ORDER BY generation_targets.refresh_kind,
             generation_targets.refresh_key
    ON CONFLICT (kind, refresh_key) DO UPDATE
    SET generation = refresh_intent_generations.generation + 1,
        completed_generation = refresh_intent_generations.generation + 1,
        deadline_at = NULL,
        event_received_at = NULL,
        updated_at = EXCLUDED.updated_at
    RETURNING kind, refresh_key, generation
)
SELECT page_targets.refresh_kind, page_targets.refresh_key,
       page_targets.entity_key, advanced.generation AS refresh_generation
FROM page_targets
JOIN advanced
  ON advanced.kind = page_targets.refresh_kind
 AND advanced.refresh_key = page_targets.refresh_key
ORDER BY page_targets.refresh_kind, page_targets.refresh_key
`

type AdvanceBranchReconciliationTargetGenerationsParams struct {
	RepoFullName string
	Branch       string
	AppliedAt    pgtype.Timestamptz
}

type AdvanceBranchReconciliationTargetGenerationsRow struct {
	RefreshKind       string
	RefreshKey        string
	EntityKey         string
	RefreshGeneration int64
}

func (q *Queries) AdvanceBranchReconciliationTargetGenerations(ctx context.Context, arg AdvanceBranchReconciliationTargetGenerationsParams) ([]AdvanceBranchReconciliationTargetGenerationsRow, error) {
	rows, err := q.db.Query(ctx, advanceBranchReconciliationTargetGenerations, arg.RepoFullName, arg.Branch, arg.AppliedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceBranchReconciliationTargetGenerationsRow
	for rows.Next() {
		var i AdvanceBranchReconciliationTargetGenerationsRow
		if err := rows.Scan(
			&i.RefreshKind,
			&i.RefreshKey,
			&i.EntityKey,
			&i.RefreshGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applyBranchHintTransition = `-- name: ApplyBranchHintTransition :many
WITH repository AS MATERIALIZED (
    SELECT repos.id, repos.installation_id, repos.gh_id,
           repos.default_branch
    FROM repos
    JOIN repo_aliases ON repo_aliases.repo_id = repos.id
    WHERE repo_aliases.full_name = $1
      AND repos.tombstoned_at IS NULL
    LIMIT 1
), updated_repository AS (
    UPDATE repos
    SET head_sha = $2,
        etag = ''
    WHERE repos.id = (SELECT id FROM repository)
      AND $3::boolean
      AND repos.default_branch = $4
      AND repos.head_sha = $5
      AND repos.head_sha IS DISTINCT FROM $2::text
    RETURNING repos.id
), updated_pulls AS (
    UPDATE pull_requests AS pull
    SET head_sha = CASE
            WHEN pull.head_ref = $4
             AND pull.head_sha = $5
            THEN $2
            ELSE pull.head_sha
        END,
        base_sha = CASE
            WHEN pull.base_ref = $4
             AND pull.base_sha = $5
            THEN $2
            ELSE pull.base_sha
        END,
        review_decision = '',
        mergeable_state = '',
        etag = ''
    FROM repository
    WHERE pull.repo_id = repository.id
      AND pull.tombstoned_at IS NULL
      AND pull.state = 'open'
      AND $3::boolean
      AND (
          (pull.head_ref = $4
           AND pull.head_sha = $5
           AND pull.head_sha IS DISTINCT FROM $2::text)
          OR
          (pull.base_ref = $4
           AND pull.base_sha = $5
           AND pull.base_sha IS DISTINCT FROM $2::text)
      )
    RETURNING pull.repo_id, pull.number, pull.stack_number
), stack_candidates AS MATERIALIZED (
    SELECT stack.id,
           CASE
               WHEN stack.base_ref = $4
                AND stack.base_sha = $5
               THEN $2::text
               ELSE stack.base_sha
           END AS new_base_sha,
           COALESCE((
               SELECT jsonb_agg(
                   CASE
                       WHEN entry.value->>'head_ref' = $4
                        AND entry.value->>'head_sha' = $5
                       THEN jsonb_set(
                           entry.value,
                           '{head_sha}',
                           to_jsonb($2::text),
                           false
                       )
                       ELSE entry.value
                   END
                   ORDER BY entry.ordinality
               )
               FROM jsonb_array_elements(stack.entries)
                   WITH ORDINALITY AS entry(value, ordinality)
           ), '[]'::jsonb) AS new_entries
    FROM stacks AS stack
    JOIN repository ON repository.id = stack.repo_id
    WHERE stack.tombstoned_at IS NULL
      AND $3::boolean
      AND (
          (stack.base_ref = $4
           AND stack.base_sha = $5)
          OR EXISTS (
              SELECT 1
              FROM jsonb_array_elements(stack.entries) AS entry
              WHERE entry->>'head_ref' = $4
                AND entry->>'head_sha' = $5
          )
      )
), updated_stacks AS (
    UPDATE stacks AS stack
    SET base_sha = candidate.new_base_sha,
        entries = candidate.new_entries,
        head_sha = CASE
            WHEN jsonb_array_length(candidate.new_entries) = 0
            THEN candidate.new_base_sha
            ELSE candidate.new_entries ->
                (jsonb_array_length(candidate.new_entries) - 1) ->>
                'head_sha'
        END,
        etag = ''
    FROM stack_candidates AS candidate
    WHERE stack.id = candidate.id
      AND ROW(stack.base_sha, stack.entries) IS DISTINCT FROM
          ROW(candidate.new_base_sha, candidate.new_entries)
    RETURNING stack.repo_id, stack.number
), dirty_scopes AS MATERIALIZED (
    SELECT DISTINCT CASE
        WHEN pull.stack_number IS NULL
        THEN 'pr:' || repository.installation_id::text || ':' ||
             repository.gh_id::text || ':' || pull.number::text
        ELSE 'stack:' || repository.installation_id::text || ':' ||
             repository.gh_id::text || ':' || pull.stack_number::text
        END AS scope_key
    FROM updated_pulls AS pull
    CROSS JOIN repository

    UNION

    SELECT 'stack:' || repository.installation_id::text || ':' ||
           repository.gh_id::text || ':' || stack.number::text
    FROM updated_stacks AS stack
    CROSS JOIN repository
), marked_dirty AS (
    INSERT INTO derivation_dirty (scope_key, marked_at)
    SELECT scope_key, $6
    FROM dirty_scopes
    ON CONFLICT (scope_key) DO UPDATE
    SET marked_at = GREATEST(
        derivation_dirty.marked_at,
        EXCLUDED.marked_at
    )
    RETURNING scope_key
), event_inputs AS MATERIALIZED (
    SELECT 'repository.changed'::text AS kind,
           'repo:' || repository.installation_id::text || ':' ||
           repository.gh_id::text AS entity_key
    FROM updated_repository
    CROSS JOIN repository

    UNION ALL

    SELECT 'pull_request.changed',
           'pr:' || repository.installation_id::text || ':' ||
           repository.gh_id::text || ':' || pull.number::text
    FROM updated_pulls AS pull
    CROSS JOIN repository

    UNION ALL

    SELECT 'stack.changed',
           'stack:' || repository.installation_id::text || ':' ||
           repository.gh_id::text || ':' || stack.number::text
    FROM updated_stacks AS stack
    CROSS JOIN repository
), inserted_events AS (
    INSERT INTO change_events (
        stream, kind, entity_key, occurred_at, payload
    )
    SELECT 'entities', kind, entity_key, $6,
           '{"version":1}'::jsonb
    FROM event_inputs
    ORDER BY entity_key, kind
    RETURNING seq, kind, entity_key
)
SELECT inserted_events.seq, inserted_events.kind,
       inserted_events.entity_key
FROM inserted_events
CROSS JOIN LATERAL (
    SELECT (SELECT count(*) FROM marked_dirty) AS ignored
) AS completed
ORDER BY inserted_events.seq
`

type ApplyBranchHintTransitionParams struct {
	RepoFullName    string
	AfterSha        string
	TransitionKnown bool
	Branch          string
	BeforeSha       string
	AppliedAt       pgtype.Timestamptz
}

type ApplyBranchHintTransitionRow struct {
	Seq       int64
	Kind      string
	EntityKey string
}

// Dependent base/head rows remain retained history. Every reader fences them
// against the live PR, while reconciliation can still reuse base-only
// CODEOWNERS source data when a head push did not invalidate it.
func (q *Queries) ApplyBranchHintTransition(ctx context.Context, arg ApplyBranchHintTransitionParams) ([]ApplyBranchHintTransitionRow, error) {
	rows, err := q.db.Query(ctx, applyBranchHintTransition,
		arg.RepoFullName,
		arg.AfterSha,
		arg.TransitionKnown,
		arg.Branch,
		arg.BeforeSha,
		arg.AppliedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplyBranchHintTransitionRow
	for rows.Next() {
		var i ApplyBranchHintTransitionRow
		if err := rows.Scan(&i.Seq, &i.Kind, &i.EntityKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const beginBranchReconciliation = `-- name: BeginBranchReconciliation :one
WITH repository AS MATERIALIZED (
    SELECT repos.id
    FROM repos
    JOIN repo_aliases ON repo_aliases.repo_id = repos.id
    WHERE repo_aliases.full_name = $1
      AND repos.tombstoned_at IS NULL
    LIMIT 1
), advanced AS (
    INSERT INTO branch_reconciliations (
        repo_id, branch, generation, before_sha, after_sha,
        transition_known, deleted, forced, delivery_guid, received_at,
        applied_at, target_count, page_count, completed_at
    )
    SELECT repository.id, $2, 1, $3,
           $4, $5,
           $6, $7, $8,
           $9, $10, 0, 0, NULL
    FROM repository
    ON CONFLICT (repo_id, branch) DO UPDATE
    SET generation = branch_reconciliations.generation + 1,
        before_sha = EXCLUDED.before_sha,
        after_sha = EXCLUDED.after_sha,
        transition_known = EXCLUDED.transition_known,
        deleted = EXCLUDED.deleted,
        forced = EXCLUDED.forced,
        delivery_guid = EXCLUDED.delivery_guid,
        received_at = EXCLUDED.received_at,
        applied_at = EXCLUDED.applied_at,
        target_count = 0,
        page_count = 0,
        completed_at = NULL
    WHERE branch_reconciliations.delivery_guid <>
          EXCLUDED.delivery_guid
    RETURNING repo_id, generation
), superseded AS (
    UPDATE branch_reconciliation_pages AS page
    SET status = 'superseded',
        superseded_targets = page.target_count,
        completed_at = $10
    FROM advanced
    WHERE page.repo_id = advanced.repo_id
      AND page.branch = $2
      AND page.generation < advanced.generation
      AND page.status = 'pending'
    RETURNING page.page_number
)
SELECT advanced.repo_id, advanced.generation,
       (SELECT count(*) FROM superseded)::bigint AS superseded_pages
FROM advanced
`

type BeginBranchReconciliationParams struct {
	RepoFullName    string
	Branch          string
	BeforeSha       string
	AfterSha        string
	TransitionKnown bool
	Deleted         bool
	Forced          bool
	DeliveryGuid    string
	ReceivedAt      pgtype.Timestamptz
	AppliedAt       pgtype.Timestamptz
}

type BeginBranchReconciliationRow struct {
	RepoID          int64
	Generation      int64
	SupersededPages int64
}

func (q *Queries) BeginBranchReconciliation(ctx context.Context, arg BeginBranchReconciliationParams) (BeginBranchReconciliationRow, error) {
	row := q.db.QueryRow(ctx, beginBranchReconciliation,
		arg.RepoFullName,
		arg.Branch,
		arg.BeforeSha,
		arg.AfterSha,
		arg.TransitionKnown,
		arg.Deleted,
		arg.Forced,
		arg.DeliveryGuid,
		arg.ReceivedAt,
		arg.AppliedAt,
	)
	var i BeginBranchReconciliationRow
	err := row.Scan(&i.RepoID, &i.Generation, &i.SupersededPages)
	return i, err
}

const collectBranchReconciliationBacklog = `-- name: CollectBranchReconciliationBacklog :one
SELECT count(*)::bigint AS pending_pages,
       COALESCE(sum(page.target_count), 0)::bigint AS pending_targets
FROM branch_reconciliation_pages AS page
JOIN branch_reconciliations AS reconciliation
  ON reconciliation.repo_id = page.repo_id
 AND reconciliation.branch = page.branch
 AND reconciliation.generation = page.generation
WHERE page.status = 'pending'
`

type CollectBranchReconciliationBacklogRow struct {
	PendingPages   int64
	PendingTargets int64
}

func (q *Queries) CollectBranchReconciliationBacklog(ctx context.Context) (CollectBranchReconciliationBacklogRow, error) {
	row := q.db.QueryRow(ctx, collectBranchReconciliationBacklog)
	var i CollectBranchReconciliationBacklogRow
	err := row.Scan(&i.PendingPages, &i.PendingTargets)
	return i, err
}

const completeBranchReconciliationPage = `-- name: CompleteBranchReconciliationPage :one
WITH completed AS (
    UPDATE branch_reconciliation_pages AS page
SET status = 'completed',
    superseded_targets = $1,
    heartbeat_at = $2,
    completed_at = $2
    WHERE page.repo_id = $3
      AND page.branch = $4
      AND page.generation = $5
      AND page.page_number = $6
      AND page.status = 'pending'
    RETURNING page.repo_id
), finished AS (
    UPDATE branch_reconciliations AS reconciliation
    SET completed_at = $2
    WHERE reconciliation.repo_id = $3
      AND reconciliation.branch = $4
      AND reconciliation.generation = $5
      AND NOT EXISTS (
          SELECT 1
          FROM branch_reconciliation_pages AS page
          WHERE page.repo_id = reconciliation.repo_id
            AND page.branch = reconciliation.branch
            AND page.generation = reconciliation.generation
            AND page.status = 'pending'
      )
    RETURNING reconciliation.repo_id
)
SELECT count(*)::bigint AS completed_count FROM completed
WHERE (SELECT count(*) FROM finished) >= 0
`

type CompleteBranchReconciliationPageParams struct {
	SupersededTargets int32
	CompletedAt       pgtype.Timestamptz
	RepoID            int64
	Branch            string
	Generation        int64
	PageNumber        int32
}

func (q *Queries) CompleteBranchReconciliationPage(ctx context.Context, arg CompleteBranchReconciliationPageParams) (int64, error) {
	row := q.db.QueryRow(ctx, completeBranchReconciliationPage,
		arg.SupersededTargets,
		arg.CompletedAt,
		arg.RepoID,
		arg.Branch,
		arg.Generation,
		arg.PageNumber,
	)
	var completed_count int64
	err := row.Scan(&completed_count)
	return completed_count, err
}

const getBranchReconciliationGenerationForShare = `-- name: GetBranchReconciliationGenerationForShare :one
SELECT generation
FROM branch_reconciliations
WHERE repo_id = $1
  AND branch = $2
FOR SHARE
`

type GetBranchReconciliationGenerationForShareParams struct {
	RepoID int64
	Branch string
}

func (q *Queries) GetBranchReconciliationGenerationForShare(ctx context.Context, arg GetBranchReconciliationGenerationForShareParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBranchReconciliationGenerationForShare, arg.RepoID, arg.Branch)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getBranchReconciliationPage = `-- name: GetBranchReconciliationPage :one
SELECT status
FROM branch_reconciliation_pages
WHERE repo_id = $1
  AND branch = $2
  AND generation = $3
  AND page_number = $4
`

type GetBranchReconciliationPageParams struct {
	RepoID     int64
	Branch     string
	Generation int64
	PageNumber int32
}

func (q *Queries) GetBranchReconciliationPage(ctx context.Context, arg GetBranchReconciliationPageParams) (string, error) {
	row := q.db.QueryRow(ctx, getBranchReconciliationPage,
		arg.RepoID,
		arg.Branch,
		arg.Generation,
		arg.PageNumber,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const heartbeatBranchReconciliationPage = `-- name: HeartbeatBranchReconciliationPage :execrows
UPDATE branch_reconciliation_pages AS page
SET heartbeat_at = clock_timestamp()
WHERE page.repo_id = $1
  AND page.branch = $2
  AND page.generation = $3
  AND page.page_number = $4
  AND page.status = 'pending'
  AND EXISTS (
      SELECT 1
      FROM branch_reconciliations AS reconciliation
      WHERE reconciliation.repo_id = page.repo_id
        AND reconciliation.branch = page.branch
        AND reconciliation.generation = page.generation
  )
`

type HeartbeatBranchReconciliationPageParams struct {
	RepoID     int64
	Branch     string
	Generation int64
	PageNumber int32
}

func (q *Queries) HeartbeatBranchReconciliationPage(ctx context.Context, arg HeartbeatBranchReconciliationPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, heartbeatBranchReconciliationPage,
		arg.RepoID,
		arg.Branch,
		arg.Generation,
		arg.PageNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBranchReconciliationGenerationKeys = `-- name: ListBranchReconciliationGenerationKeys :many
WITH repository AS MATERIALIZED (
    SELECT repos.id, repos.installation_id, repos.gh_id,
           repos.default_branch
    FROM repos
    JOIN repo_aliases ON repo_aliases.repo_id = repos.id
    WHERE repo_aliases.full_name = $1
      AND repos.tombstoned_at IS NULL
    LIMIT 1
), page_targets AS (
    SELECT 'refresh_pr'::text AS refresh_kind,
           ('pr:' || $1::text || ':' ||
            pull_requests.number::text)::text AS refresh_key,
           ('pr:' || repository.installation_id::text || ':' ||
            repository.gh_id::text || ':' ||
            pull_requests.number::text)::text AS entity_key
    FROM repository
    JOIN pull_requests ON pull_requests.repo_id = repository.id
    WHERE pull_requests.tombstoned_at IS NULL
      AND pull_requests.state = 'open'
      AND (
          pull_requests.head_ref = $2
          OR pull_requests.base_ref = $2
      )

    UNION

    SELECT 'refresh_stack'::text,
           ('stack:' || $1::text || ':' ||
            stacks.number::text)::text,
           ('stack:' || repository.installation_id::text || ':' ||
            repository.gh_id::text || ':' || stacks.number::text)::text
    FROM repository
    JOIN stacks ON stacks.repo_id = repository.id
    WHERE stacks.tombstoned_at IS NULL
      AND (
          stacks.base_ref = $2
          OR EXISTS (
              SELECT 1
              FROM jsonb_array_elements(stacks.entries) AS entry
              WHERE entry->>'head_ref' = $2
          )
      )
), generation_targets AS (
    SELECT page_targets.refresh_kind, page_targets.refresh_key
    FROM page_targets

    UNION

    SELECT 'refresh_repository'::text,
           ('repo:' || $1::text || ':metadata')::text
    FROM repository
    WHERE repository.default_branch = $2
)
SELECT generation_targets.refresh_kind, generation_targets.refresh_key
FROM generation_targets
ORDER BY generation_targets.refresh_kind, generation_targets.refresh_key
`

type ListBranchReconciliationGenerationKeysParams struct {
	RepoFullName string
	Branch       string
}

type ListBranchReconciliationGenerationKeysRow struct {
	RefreshKind string
	RefreshKey  string
}

func (q *Queries) ListBranchReconciliationGenerationKeys(ctx context.Context, arg ListBranchReconciliationGenerationKeysParams) ([]ListBranchReconciliationGenerationKeysRow, error) {
	rows, err := q.db.Query(ctx, listBranchReconciliationGenerationKeys, arg.RepoFullName, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBranchReconciliationGenerationKeysRow
	for rows.Next() {
		var i ListBranchReconciliationGenerationKeysRow
		if err := rows.Scan(&i.RefreshKind, &i.RefreshKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordBranchReconciliationPages = `-- name: RecordBranchReconciliationPages :exec
WITH input AS (
    SELECT (element->>'page_number')::integer AS page_number,
           (element->>'target_count')::integer AS target_count
    FROM jsonb_array_elements($7::jsonb) AS element
), inserted AS (
    INSERT INTO branch_reconciliation_pages (
        repo_id, branch, generation, page_number, target_count,
        created_at
    )
    SELECT $4, $5, $6,
           input.page_number, input.target_count, $3
    FROM input
    ON CONFLICT (repo_id, branch, generation, page_number) DO NOTHING
    RETURNING page_number
)
UPDATE branch_reconciliations AS current_reconciliation
SET target_count = $1,
    page_count = $2,
    completed_at = CASE
        WHEN $2::integer = 0 THEN $3
        ELSE NULL
    END
WHERE current_reconciliation.repo_id = $4
  AND current_reconciliation.branch = $5
  AND current_reconciliation.generation = $6
  AND (SELECT count(*) FROM inserted) >= 0
`

type RecordBranchReconciliationPagesParams struct {
	TargetCount int32
	PageCount   int32
	CreatedAt   pgtype.Timestamptz
	RepoID      int64
	Branch      string
	Generation  int64
	Pages       []byte
}

func (q *Queries) RecordBranchReconciliationPages(ctx context.Context, arg RecordBranchReconciliationPagesParams) error {
	_, err := q.db.Exec(ctx, recordBranchReconciliationPages,
		arg.TargetCount,
		arg.PageCount,
		arg.CreatedAt,
		arg.RepoID,
		arg.Branch,
		arg.Generation,
		arg.Pages,
	)
	return err
}

const startBranchReconciliationPage = `-- name: StartBranchReconciliationPage :execrows
UPDATE branch_reconciliation_pages AS page
SET attempt_count = page.attempt_count + 1,
    last_started_at = clock_timestamp(),
    heartbeat_at = clock_timestamp()
WHERE page.repo_id = $1
  AND page.branch = $2
  AND page.generation = $3
  AND page.page_number = $4
  AND page.status = 'pending'
  AND EXISTS (
      SELECT 1
      FROM branch_reconciliations AS reconciliation
      WHERE reconciliation.repo_id = page.repo_id
        AND reconciliation.branch = page.branch
        AND reconciliation.generation = page.generation
  )
`

type StartBranchReconciliationPageParams struct {
	RepoID     int64
	Branch     string
	Generation int64
	PageNumber int32
}

func (q *Queries) StartBranchReconciliationPage(ctx context.Context, arg StartBranchReconciliationPageParams) (int64, error) {
	result, err := q.db.Exec(ctx, startBranchReconciliationPage,
		arg.RepoID,
		arg.Branch,
		arg.Generation,
		arg.PageNumber,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
