// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEntityAdvisoryLock = `-- name: AcquireEntityAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// C-C1 transaction-scoped serialization for direct writer calls.
func (q *Queries) AcquireEntityAdvisoryLock(ctx context.Context, entityKey string) error {
	_, err := q.db.Exec(ctx, acquireEntityAdvisoryLock, entityKey)
	return err
}

const acquireEntitySessionLock = `-- name: AcquireEntitySessionLock :exec
SELECT pg_advisory_lock(hashtextextended($1::text, 0))
`

// Fetch workers use a dedicated connection and hold this lock from before
// observation until after the state transaction commits.
func (q *Queries) AcquireEntitySessionLock(ctx context.Context, entityKey string) error {
	_, err := q.db.Exec(ctx, acquireEntitySessionLock, entityKey)
	return err
}

const appendAcceptedCheckHistory = `-- name: AppendAcceptedCheckHistory :exec
WITH input AS (
    SELECT (element->>'gh_id')::bigint AS gh_id,
           element->>'name' AS name,
           element->>'status' AS status,
           element->>'conclusion' AS conclusion,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at,
           element->>'semantic_version' AS semantic_version,
           element->'observed' AS observed
    FROM jsonb_array_elements($6::jsonb) AS element
)
INSERT INTO check_history (
    check_run_gh_id, repo_id, name, status, conclusion, observed,
    gh_updated_at, semantic_version, head_sha, synced_at, etag, sync_source,
    tombstoned_at
)
SELECT input.gh_id, $1, input.name, input.status,
       input.conclusion, input.observed, input.gh_updated_at,
       input.semantic_version, $2, $3,
       $4, $5, NULL
FROM input
JOIN check_runs ON check_runs.gh_id = input.gh_id
WHERE check_runs.repo_id = $1
  AND check_runs.head_sha = $2
  AND check_runs.synced_at = $3
  AND check_runs.status = input.status
  AND check_runs.conclusion = input.conclusion
  AND check_runs.semantic_version = input.semantic_version
`

type AppendAcceptedCheckHistoryParams struct {
	RepoID     int64
	HeadSha    string
	SyncedAt   pgtype.Timestamptz
	Etag       string
	SyncSource string
	CheckRuns  []byte
}

func (q *Queries) AppendAcceptedCheckHistory(ctx context.Context, arg AppendAcceptedCheckHistoryParams) error {
	_, err := q.db.Exec(ctx, appendAcceptedCheckHistory,
		arg.RepoID,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
		arg.CheckRuns,
	)
	return err
}

const getCheckRunsFetchMetadata = `-- name: GetCheckRunsFetchMetadata :one
SELECT repos.gh_id AS repo_gh_id, repos.installation_id,
       repos.full_name AS repo_full_name,
       COALESCE((
           SELECT check_runs.etag
           FROM check_runs
           WHERE check_runs.repo_id = repos.id
             AND check_runs.head_sha = $1
           ORDER BY check_runs.last_checked_at DESC, check_runs.gh_id
           LIMIT 1
       ), ''::text)::text AS etag
FROM repos
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $2
`

type GetCheckRunsFetchMetadataParams struct {
	HeadSha      string
	RepoFullName string
}

type GetCheckRunsFetchMetadataRow struct {
	RepoGhID       int64
	InstallationID int64
	RepoFullName   string
	Etag           string
}

// C-B4: the first-page validator is shared by every check row in one
// repository/head-SHA listing. Prefer the newest observation when rows span
// multiple refreshes, including a fully tombstoned listing.
func (q *Queries) GetCheckRunsFetchMetadata(ctx context.Context, arg GetCheckRunsFetchMetadataParams) (GetCheckRunsFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getCheckRunsFetchMetadata, arg.HeadSha, arg.RepoFullName)
	var i GetCheckRunsFetchMetadataRow
	err := row.Scan(
		&i.RepoGhID,
		&i.InstallationID,
		&i.RepoFullName,
		&i.Etag,
	)
	return i, err
}

const getPullRequestByIdentity = `-- name: GetPullRequestByIdentity :one
SELECT pull_requests.id, pull_requests.repo_id, pull_requests.gh_id, pull_requests.node_id, pull_requests.number, pull_requests.title, pull_requests.state, pull_requests.draft, pull_requests.author_login, pull_requests.head_ref, pull_requests.head_sha, pull_requests.base_ref, pull_requests.base_sha, pull_requests.review_decision, pull_requests.mergeable_state, pull_requests.stack_number, pull_requests.stack_position, pull_requests.gh_updated_at, pull_requests.synced_at, pull_requests.etag, pull_requests.sync_source, pull_requests.tombstoned_at, pull_requests.last_checked_at, pull_requests.display_until, repos.full_name AS repo_full_name
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.gh_id = $1
  AND pull_requests.number = $2
`

type GetPullRequestByIdentityParams struct {
	RepoGhID int64
	PrNumber int32
}

type GetPullRequestByIdentityRow struct {
	ID             int64
	RepoID         int64
	GhID           pgtype.Int8
	NodeID         string
	Number         int32
	Title          string
	State          string
	Draft          bool
	AuthorLogin    string
	HeadRef        string
	HeadSha        string
	BaseRef        string
	BaseSha        string
	ReviewDecision string
	MergeableState string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	GhUpdatedAt    pgtype.Timestamptz
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
	TombstonedAt   pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	DisplayUntil   pgtype.Timestamptz
	RepoFullName   string
}

func (q *Queries) GetPullRequestByIdentity(ctx context.Context, arg GetPullRequestByIdentityParams) (GetPullRequestByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestByIdentity, arg.RepoGhID, arg.PrNumber)
	var i GetPullRequestByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
		&i.RepoFullName,
	)
	return i, err
}

const getPullRequestByKey = `-- name: GetPullRequestByKey :one
SELECT pull_requests.id, pull_requests.repo_id, pull_requests.gh_id, pull_requests.node_id, pull_requests.number, pull_requests.title, pull_requests.state, pull_requests.draft, pull_requests.author_login, pull_requests.head_ref, pull_requests.head_sha, pull_requests.base_ref, pull_requests.base_sha, pull_requests.review_decision, pull_requests.mergeable_state, pull_requests.stack_number, pull_requests.stack_position, pull_requests.gh_updated_at, pull_requests.synced_at, pull_requests.etag, pull_requests.sync_source, pull_requests.tombstoned_at, pull_requests.last_checked_at, pull_requests.display_until, repos.full_name AS repo_full_name
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND pull_requests.number = $2
`

type GetPullRequestByKeyParams struct {
	RepoFullName string
	PrNumber     int32
}

type GetPullRequestByKeyRow struct {
	ID             int64
	RepoID         int64
	GhID           pgtype.Int8
	NodeID         string
	Number         int32
	Title          string
	State          string
	Draft          bool
	AuthorLogin    string
	HeadRef        string
	HeadSha        string
	BaseRef        string
	BaseSha        string
	ReviewDecision string
	MergeableState string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	GhUpdatedAt    pgtype.Timestamptz
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
	TombstonedAt   pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	DisplayUntil   pgtype.Timestamptz
	RepoFullName   string
}

func (q *Queries) GetPullRequestByKey(ctx context.Context, arg GetPullRequestByKeyParams) (GetPullRequestByKeyRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestByKey, arg.RepoFullName, arg.PrNumber)
	var i GetPullRequestByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
		&i.RepoFullName,
	)
	return i, err
}

const getPullRequestFetchMetadata = `-- name: GetPullRequestFetchMetadata :one
SELECT pull_requests.node_id, pull_requests.etag,
       pull_requests.stack_number, pull_requests.stack_position,
       pull_requests.head_sha, repos.gh_id AS repo_gh_id,
       repos.installation_id, repos.full_name AS repo_full_name
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND pull_requests.number = $2
`

type GetPullRequestFetchMetadataParams struct {
	RepoFullName string
	PrNumber     int32
}

type GetPullRequestFetchMetadataRow struct {
	NodeID         string
	Etag           string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	HeadSha        string
	RepoGhID       int64
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) GetPullRequestFetchMetadata(ctx context.Context, arg GetPullRequestFetchMetadataParams) (GetPullRequestFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestFetchMetadata, arg.RepoFullName, arg.PrNumber)
	var i GetPullRequestFetchMetadataRow
	err := row.Scan(
		&i.NodeID,
		&i.Etag,
		&i.StackNumber,
		&i.StackPosition,
		&i.HeadSha,
		&i.RepoGhID,
		&i.InstallationID,
		&i.RepoFullName,
	)
	return i, err
}

const getRepoByFullName = `-- name: GetRepoByFullName :one
SELECT repos.id, repos.installation_id, repos.org_id, repos.gh_id, repos.node_id, repos.owner, repos.name, repos.full_name, repos.default_branch, repos.archived, repos.gh_updated_at, repos.head_sha, repos.synced_at, repos.etag, repos.sync_source, repos.tombstoned_at, repos.last_checked_at
FROM repo_aliases
JOIN repos ON repos.id = repo_aliases.repo_id
WHERE repo_aliases.full_name = $1
`

func (q *Queries) GetRepoByFullName(ctx context.Context, fullName string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
	)
	return i, err
}

const getRepoByGitHubID = `-- name: GetRepoByGitHubID :one
SELECT id, installation_id, org_id, gh_id, node_id, owner, name, full_name, default_branch, archived, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at, last_checked_at
FROM repos
WHERE gh_id = $1
`

func (q *Queries) GetRepoByGitHubID(ctx context.Context, ghID int64) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByGitHubID, ghID)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
	)
	return i, err
}

const getRepoRulesFetchMetadata = `-- name: GetRepoRulesFetchMetadata :one
SELECT repos.id AS repo_id, repos.gh_id AS repo_gh_id,
       repos.installation_id, repos.full_name,
       COALESCE(repo_rule_sync_state.etag, '') AS etag
FROM repos
LEFT JOIN repo_rule_sync_state
    ON repo_rule_sync_state.repo_id = repos.id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
`

type GetRepoRulesFetchMetadataRow struct {
	RepoID         int64
	RepoGhID       int64
	InstallationID int64
	FullName       string
	Etag           string
}

func (q *Queries) GetRepoRulesFetchMetadata(ctx context.Context, repoFullName string) (GetRepoRulesFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getRepoRulesFetchMetadata, repoFullName)
	var i GetRepoRulesFetchMetadataRow
	err := row.Scan(
		&i.RepoID,
		&i.RepoGhID,
		&i.InstallationID,
		&i.FullName,
		&i.Etag,
	)
	return i, err
}

const getStackByIdentity = `-- name: GetStackByIdentity :one
SELECT stacks.id, stacks.repo_id, stacks.gh_id, stacks.node_id, stacks.number, stacks.base_ref, stacks.base_sha, stacks.open, stacks.entries, stacks.gh_updated_at, stacks.head_sha, stacks.synced_at, stacks.etag, stacks.sync_source, stacks.tombstoned_at, stacks.last_checked_at, stacks.display_until, repos.full_name AS repo_full_name
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.gh_id = $1
  AND stacks.number = $2
`

type GetStackByIdentityParams struct {
	RepoGhID    int64
	StackNumber int32
}

type GetStackByIdentityRow struct {
	ID            int64
	RepoID        int64
	GhID          pgtype.Int8
	NodeID        string
	Number        int32
	BaseRef       string
	BaseSha       string
	Open          bool
	Entries       []byte
	GhUpdatedAt   pgtype.Timestamptz
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	Etag          string
	SyncSource    string
	TombstonedAt  pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	DisplayUntil  pgtype.Timestamptz
	RepoFullName  string
}

func (q *Queries) GetStackByIdentity(ctx context.Context, arg GetStackByIdentityParams) (GetStackByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getStackByIdentity, arg.RepoGhID, arg.StackNumber)
	var i GetStackByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
		&i.RepoFullName,
	)
	return i, err
}

const getStackByKey = `-- name: GetStackByKey :one
SELECT stacks.id, stacks.repo_id, stacks.gh_id, stacks.node_id, stacks.number, stacks.base_ref, stacks.base_sha, stacks.open, stacks.entries, stacks.gh_updated_at, stacks.head_sha, stacks.synced_at, stacks.etag, stacks.sync_source, stacks.tombstoned_at, stacks.last_checked_at, stacks.display_until, repos.full_name AS repo_full_name
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND stacks.number = $2
`

type GetStackByKeyParams struct {
	RepoFullName string
	StackNumber  int32
}

type GetStackByKeyRow struct {
	ID            int64
	RepoID        int64
	GhID          pgtype.Int8
	NodeID        string
	Number        int32
	BaseRef       string
	BaseSha       string
	Open          bool
	Entries       []byte
	GhUpdatedAt   pgtype.Timestamptz
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	Etag          string
	SyncSource    string
	TombstonedAt  pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	DisplayUntil  pgtype.Timestamptz
	RepoFullName  string
}

func (q *Queries) GetStackByKey(ctx context.Context, arg GetStackByKeyParams) (GetStackByKeyRow, error) {
	row := q.db.QueryRow(ctx, getStackByKey, arg.RepoFullName, arg.StackNumber)
	var i GetStackByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
		&i.RepoFullName,
	)
	return i, err
}

const getStackFetchMetadata = `-- name: GetStackFetchMetadata :one
SELECT stacks.etag, stacks.entries, stacks.head_sha,
       repos.gh_id AS repo_gh_id, repos.installation_id,
       repos.full_name AS repo_full_name
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND stacks.number = $2
`

type GetStackFetchMetadataParams struct {
	RepoFullName string
	StackNumber  int32
}

type GetStackFetchMetadataRow struct {
	Etag           string
	Entries        []byte
	HeadSha        string
	RepoGhID       int64
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) GetStackFetchMetadata(ctx context.Context, arg GetStackFetchMetadataParams) (GetStackFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getStackFetchMetadata, arg.RepoFullName, arg.StackNumber)
	var i GetStackFetchMetadataRow
	err := row.Scan(
		&i.Etag,
		&i.Entries,
		&i.HeadSha,
		&i.RepoGhID,
		&i.InstallationID,
		&i.RepoFullName,
	)
	return i, err
}

const insertChangeEvent = `-- name: InsertChangeEvent :one
INSERT INTO change_events (
    stream, kind, entity_key, occurred_at, payload
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING seq
`

type InsertChangeEventParams struct {
	Stream     string
	Kind       string
	EntityKey  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

func (q *Queries) InsertChangeEvent(ctx context.Context, arg InsertChangeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChangeEvent,
		arg.Stream,
		arg.Kind,
		arg.EntityKey,
		arg.OccurredAt,
		arg.Payload,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const listCachedPRMemberships = `-- name: ListCachedPRMemberships :many
SELECT pull_requests.number, pull_requests.stack_number
FROM pull_requests
WHERE pull_requests.repo_id = $1
  AND pull_requests.number = ANY($2::int[])
ORDER BY pull_requests.number
`

type ListCachedPRMembershipsParams struct {
	RepoID    int64
	PrNumbers []int32
}

type ListCachedPRMembershipsRow struct {
	Number      int32
	StackNumber pgtype.Int4
}

func (q *Queries) ListCachedPRMemberships(ctx context.Context, arg ListCachedPRMembershipsParams) ([]ListCachedPRMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listCachedPRMemberships, arg.RepoID, arg.PrNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCachedPRMembershipsRow
	for rows.Next() {
		var i ListCachedPRMembershipsRow
		if err := rows.Scan(&i.Number, &i.StackNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRScopesByHeadSHA = `-- name: ListPRScopesByHeadSHA :many
SELECT pull_requests.number, pull_requests.stack_number,
       repos.gh_id AS repo_gh_id, repos.installation_id
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.gh_id = $1
  AND pull_requests.head_sha = $2
  AND pull_requests.tombstoned_at IS NULL
ORDER BY pull_requests.number
`

type ListPRScopesByHeadSHAParams struct {
	RepoGhID int64
	HeadSha  string
}

type ListPRScopesByHeadSHARow struct {
	Number         int32
	StackNumber    pgtype.Int4
	RepoGhID       int64
	InstallationID int64
}

func (q *Queries) ListPRScopesByHeadSHA(ctx context.Context, arg ListPRScopesByHeadSHAParams) ([]ListPRScopesByHeadSHARow, error) {
	rows, err := q.db.Query(ctx, listPRScopesByHeadSHA, arg.RepoGhID, arg.HeadSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPRScopesByHeadSHARow
	for rows.Next() {
		var i ListPRScopesByHeadSHARow
		if err := rows.Scan(
			&i.Number,
			&i.StackNumber,
			&i.RepoGhID,
			&i.InstallationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRsAffectedByBranch = `-- name: ListPRsAffectedByBranch :many
SELECT DISTINCT pull_requests.number, pull_requests.stack_number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND pull_requests.tombstoned_at IS NULL
  AND (
      pull_requests.head_ref = $2
      OR pull_requests.base_ref = $2
  )
ORDER BY pull_requests.number
`

type ListPRsAffectedByBranchParams struct {
	RepoFullName string
	Branch       string
}

type ListPRsAffectedByBranchRow struct {
	Number      int32
	StackNumber pgtype.Int4
}

func (q *Queries) ListPRsAffectedByBranch(ctx context.Context, arg ListPRsAffectedByBranchParams) ([]ListPRsAffectedByBranchRow, error) {
	rows, err := q.db.Query(ctx, listPRsAffectedByBranch, arg.RepoFullName, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPRsAffectedByBranchRow
	for rows.Next() {
		var i ListPRsAffectedByBranchRow
		if err := rows.Scan(&i.Number, &i.StackNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRepositoryDerivationScopes = `-- name: ListRepositoryDerivationScopes :many
SELECT scopes.scope_key::text
FROM (
    SELECT 'stack:' || repos.installation_id::text || ':' ||
           repos.gh_id::text || ':' || stacks.number::text AS scope_key
    FROM stacks
    JOIN repos ON repos.id = stacks.repo_id
    WHERE repos.id = $1
      AND stacks.tombstoned_at IS NULL
    UNION
    SELECT 'pr:' || repos.installation_id::text || ':' ||
           repos.gh_id::text || ':' || pull_requests.number::text AS scope_key
    FROM pull_requests
    JOIN repos ON repos.id = pull_requests.repo_id
    WHERE repos.id = $1
      AND pull_requests.tombstoned_at IS NULL
      AND pull_requests.stack_number IS NULL
) AS scopes
ORDER BY scope_key
`

func (q *Queries) ListRepositoryDerivationScopes(ctx context.Context, repoID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listRepositoryDerivationScopes, repoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var scopes_scope_key string
		if err := rows.Scan(&scopes_scope_key); err != nil {
			return nil, err
		}
		items = append(items, scopes_scope_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStacksAffectedByBranch = `-- name: ListStacksAffectedByBranch :many
SELECT DISTINCT stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
JOIN repo_aliases ON repo_aliases.repo_id = repos.id
WHERE repo_aliases.full_name = $1
  AND stacks.tombstoned_at IS NULL
  AND (
      stacks.base_ref = $2
      OR EXISTS (
          SELECT 1
          FROM jsonb_array_elements(stacks.entries) AS entry
          WHERE entry->>'head_ref' = $2
      )
  )
ORDER BY stacks.number
`

type ListStacksAffectedByBranchParams struct {
	RepoFullName string
	Branch       string
}

func (q *Queries) ListStacksAffectedByBranch(ctx context.Context, arg ListStacksAffectedByBranchParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listStacksAffectedByBranch, arg.RepoFullName, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDerivationDirty = `-- name: MarkDerivationDirty :exec
INSERT INTO derivation_dirty (scope_key, marked_at)
SELECT DISTINCT dirty.scope_key, $1::timestamptz
FROM unnest($2::text[]) AS dirty(scope_key)
ON CONFLICT (scope_key) DO UPDATE
SET marked_at = GREATEST(derivation_dirty.marked_at, EXCLUDED.marked_at)
`

type MarkDerivationDirtyParams struct {
	MarkedAt  pgtype.Timestamptz
	ScopeKeys []string
}

func (q *Queries) MarkDerivationDirty(ctx context.Context, arg MarkDerivationDirtyParams) error {
	_, err := q.db.Exec(ctx, markDerivationDirty, arg.MarkedAt, arg.ScopeKeys)
	return err
}

const releaseEntitySessionLock = `-- name: ReleaseEntitySessionLock :exec
SELECT pg_advisory_unlock(hashtextextended($1::text, 0))
`

func (q *Queries) ReleaseEntitySessionLock(ctx context.Context, entityKey string) error {
	_, err := q.db.Exec(ctx, releaseEntitySessionLock, entityKey)
	return err
}

const replaceCheckRuns = `-- name: ReplaceCheckRuns :many
WITH input AS (
    SELECT (element->>'gh_id')::bigint AS gh_id,
           element->>'node_id' AS node_id,
           element->>'name' AS name,
           element->>'status' AS status,
           element->>'conclusion' AS conclusion,
           element->>'details_url' AS details_url,
           element->>'app_slug' AS app_slug,
           (element->>'started_at')::timestamptz AS started_at,
           (element->>'completed_at')::timestamptz AS completed_at,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at,
           element->>'semantic_version' AS semantic_version,
           element->'observed' AS observed
    FROM jsonb_array_elements($1::jsonb) AS element
),
upserted AS (
    INSERT INTO check_runs (
        gh_id, repo_id, node_id, name, status, conclusion, details_url,
        app_slug, started_at, completed_at, gh_updated_at, semantic_version,
        head_sha, synced_at, last_checked_at, etag, sync_source, tombstoned_at
    )
    SELECT input.gh_id, $2, input.node_id, input.name,
           input.status, input.conclusion, input.details_url, input.app_slug,
           input.started_at, input.completed_at, input.gh_updated_at,
           input.semantic_version, $3, $4,
           $5, $6,
           $7, NULL
    FROM input
    ON CONFLICT (gh_id) DO UPDATE
    SET repo_id = EXCLUDED.repo_id,
        node_id = EXCLUDED.node_id,
        name = EXCLUDED.name,
        status = EXCLUDED.status,
        conclusion = EXCLUDED.conclusion,
        details_url = EXCLUDED.details_url,
        app_slug = EXCLUDED.app_slug,
        started_at = EXCLUDED.started_at,
        completed_at = EXCLUDED.completed_at,
        gh_updated_at = EXCLUDED.gh_updated_at,
        semantic_version = EXCLUDED.semantic_version,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE (
           check_runs.gh_updated_at IS NULL
           AND EXCLUDED.gh_updated_at IS NOT NULL
       )
       OR EXCLUDED.gh_updated_at > check_runs.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at IS NOT DISTINCT FROM check_runs.gh_updated_at
           AND ROW(
               EXCLUDED.repo_id, EXCLUDED.node_id, EXCLUDED.name,
               EXCLUDED.status, EXCLUDED.conclusion, EXCLUDED.details_url,
               EXCLUDED.app_slug, EXCLUDED.started_at, EXCLUDED.completed_at,
               EXCLUDED.semantic_version, EXCLUDED.head_sha
           ) IS DISTINCT FROM ROW(
               check_runs.repo_id, check_runs.node_id, check_runs.name,
               check_runs.status, check_runs.conclusion,
               check_runs.details_url, check_runs.app_slug,
               check_runs.started_at, check_runs.completed_at,
               check_runs.semantic_version, check_runs.head_sha
           )
       )
       OR (
           check_runs.tombstoned_at IS NOT NULL
           AND EXCLUDED.last_checked_at > check_runs.tombstoned_at
       )
    RETURNING gh_id
),
tombstoned AS (
    UPDATE check_runs
    SET tombstoned_at = $5,
        synced_at = $4,
        last_checked_at = $5,
        etag = $6,
        sync_source = $7
    WHERE repo_id = $2
      AND head_sha = $3
      AND tombstoned_at IS NULL
      AND last_checked_at <= $5
      AND NOT EXISTS (
          SELECT 1 FROM input WHERE input.gh_id = check_runs.gh_id
      )
    RETURNING gh_id
)
SELECT gh_id FROM upserted
UNION ALL
SELECT gh_id FROM tombstoned
`

type ReplaceCheckRunsParams struct {
	CheckRuns     []byte
	RepoID        int64
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	Etag          string
	SyncSource    string
}

func (q *Queries) ReplaceCheckRuns(ctx context.Context, arg ReplaceCheckRunsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, replaceCheckRuns,
		arg.CheckRuns,
		arg.RepoID,
		arg.HeadSha,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var gh_id int64
		if err := rows.Scan(&gh_id); err != nil {
			return nil, err
		}
		items = append(items, gh_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePullRequestComments = `-- name: ReplacePullRequestComments :many
WITH input AS (
    SELECT NULLIF((element->>'gh_id')::bigint, 0) AS gh_id,
           element->>'node_id' AS node_id,
           element->>'author_kind' AS author_kind,
           NULLIF(element->>'author_node_id', '') AS author_node_id,
           NULLIF(element->>'author_login', '') AS author_login,
           (element->>'created_at')::timestamptz AS created_at,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at
    FROM jsonb_array_elements($1::jsonb) AS element
),
eligible AS (
    SELECT pull_requests.repo_id
    FROM pull_requests
    WHERE pull_requests.repo_id = $2
      AND pull_requests.number = $3
      AND pull_requests.tombstoned_at IS NULL
      AND (
          pull_requests.gh_updated_at IS NULL
          OR pull_requests.gh_updated_at <= $4
      )
),
upserted AS (
    INSERT INTO pull_request_comments (
        gh_id, node_id, repo_id, pr_number, author_kind, author_node_id,
        author_login, created_at, gh_updated_at, head_sha, synced_at, etag,
        sync_source, tombstoned_at, last_checked_at
    )
    SELECT input.gh_id, input.node_id, $2,
           $3, input.author_kind, input.author_node_id,
           input.author_login, input.created_at, input.gh_updated_at,
           $5, $6, $7,
           $8, NULL, $9
    FROM input
    WHERE EXISTS (SELECT 1 FROM eligible)
    ON CONFLICT (node_id) DO UPDATE
    SET gh_id = EXCLUDED.gh_id,
        repo_id = EXCLUDED.repo_id,
        pr_number = EXCLUDED.pr_number,
        author_kind = EXCLUDED.author_kind,
        author_node_id = EXCLUDED.author_node_id,
        author_login = EXCLUDED.author_login,
        created_at = EXCLUDED.created_at,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE EXCLUDED.gh_updated_at > pull_request_comments.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at = pull_request_comments.gh_updated_at
           AND (
               (
                   pull_request_comments.tombstoned_at IS NULL
                   AND ROW(
                   EXCLUDED.gh_id, EXCLUDED.repo_id, EXCLUDED.pr_number,
                   EXCLUDED.author_kind, EXCLUDED.author_node_id,
                   EXCLUDED.author_login, EXCLUDED.created_at,
                   EXCLUDED.head_sha
                   ) IS DISTINCT FROM ROW(
                   pull_request_comments.gh_id,
                   pull_request_comments.repo_id,
                   pull_request_comments.pr_number,
                   pull_request_comments.author_kind,
                   pull_request_comments.author_node_id,
                   pull_request_comments.author_login,
                   pull_request_comments.created_at,
                       pull_request_comments.head_sha
                   )
               )
               OR (
                   pull_request_comments.tombstoned_at IS NOT NULL
                   AND EXCLUDED.last_checked_at >
                       pull_request_comments.tombstoned_at
                   AND EXISTS (SELECT 1 FROM eligible)
               )
           )
       )
    RETURNING node_id
),
tombstoned AS (
    UPDATE pull_request_comments
    SET tombstoned_at = $9,
        synced_at = $6,
        last_checked_at = $9,
        etag = $7,
        sync_source = $8
    WHERE repo_id = $2
      AND pr_number = $3
      AND tombstoned_at IS NULL
      AND EXISTS (SELECT 1 FROM eligible)
      AND last_checked_at <= $9
      AND NOT EXISTS (
          SELECT 1 FROM input
          WHERE input.node_id = pull_request_comments.node_id
      )
    RETURNING node_id
)
SELECT node_id FROM upserted
UNION ALL
SELECT node_id FROM tombstoned
`

type ReplacePullRequestCommentsParams struct {
	Comments          []byte
	RepoID            int64
	PrNumber          int32
	ParentGhUpdatedAt pgtype.Timestamptz
	HeadSha           string
	SyncedAt          pgtype.Timestamptz
	Etag              string
	SyncSource        string
	LastCheckedAt     pgtype.Timestamptz
}

func (q *Queries) ReplacePullRequestComments(ctx context.Context, arg ReplacePullRequestCommentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, replacePullRequestComments,
		arg.Comments,
		arg.RepoID,
		arg.PrNumber,
		arg.ParentGhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
		arg.LastCheckedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePullRequestReviewRequests = `-- name: ReplacePullRequestReviewRequests :many
WITH input AS (
    SELECT element->>'kind' AS reviewer_kind,
           (element->>'gh_id')::bigint AS reviewer_gh_id,
           element->>'node_id' AS reviewer_node_id,
           element->>'login' AS reviewer_login,
           (element->>'requested_at')::timestamptz AS requested_at
    FROM jsonb_array_elements($1::jsonb) AS element
),
eligible AS (
    SELECT pull_requests.repo_id
    FROM pull_requests
    WHERE pull_requests.repo_id = $2
      AND pull_requests.number = $3
      AND pull_requests.tombstoned_at IS NULL
      AND (
          pull_requests.gh_updated_at IS NULL
          OR pull_requests.gh_updated_at <= $4
      )
),
upserted AS (
    INSERT INTO pull_request_review_requests (
        repo_id, pr_number, reviewer_kind, reviewer_gh_id,
        reviewer_node_id, reviewer_login, requested_at, first_seen_at,
        gh_updated_at, head_sha, synced_at, last_checked_at, etag,
        sync_source, tombstoned_at
    )
    SELECT $2, $3, input.reviewer_kind,
           input.reviewer_gh_id, input.reviewer_node_id,
           input.reviewer_login, input.requested_at,
           $5, $4,
           $6, $7,
           $8, $9,
           $10, NULL
    FROM input
    CROSS JOIN eligible
    ON CONFLICT (repo_id, pr_number, reviewer_kind, reviewer_gh_id)
    DO UPDATE
    SET reviewer_node_id = EXCLUDED.reviewer_node_id,
        reviewer_login = EXCLUDED.reviewer_login,
        requested_at = CASE
            WHEN pull_request_review_requests.tombstoned_at IS NOT NULL
            THEN EXCLUDED.requested_at
            ELSE COALESCE(
                EXCLUDED.requested_at,
                pull_request_review_requests.requested_at
            )
        END,
        first_seen_at = CASE
            WHEN pull_request_review_requests.tombstoned_at IS NOT NULL
            THEN EXCLUDED.first_seen_at
            ELSE pull_request_review_requests.first_seen_at
        END,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE pull_request_review_requests.tombstoned_at IS NOT NULL
       OR ROW(
           EXCLUDED.reviewer_node_id,
           EXCLUDED.reviewer_login,
           CASE
               WHEN pull_request_review_requests.tombstoned_at IS NOT NULL
               THEN EXCLUDED.requested_at
               ELSE COALESCE(
                   EXCLUDED.requested_at,
                   pull_request_review_requests.requested_at
               )
           END,
           EXCLUDED.head_sha
       ) IS DISTINCT FROM ROW(
           pull_request_review_requests.reviewer_node_id,
           pull_request_review_requests.reviewer_login,
           pull_request_review_requests.requested_at,
           pull_request_review_requests.head_sha
       )
    RETURNING reviewer_kind || ':' || reviewer_gh_id::text AS reviewer_key
),
tombstoned AS (
    UPDATE pull_request_review_requests
    SET tombstoned_at = $8,
        synced_at = $7,
        last_checked_at = $8,
        etag = $9,
        sync_source = $10
    WHERE repo_id = $2
      AND pr_number = $3
      AND tombstoned_at IS NULL
      AND EXISTS (SELECT 1 FROM eligible)
      AND NOT EXISTS (
          SELECT 1
          FROM input
          WHERE input.reviewer_kind =
                    pull_request_review_requests.reviewer_kind
            AND input.reviewer_gh_id =
                    pull_request_review_requests.reviewer_gh_id
      )
    RETURNING reviewer_kind || ':' || reviewer_gh_id::text AS reviewer_key
)
SELECT reviewer_key FROM upserted
UNION ALL
SELECT reviewer_key FROM tombstoned
`

type ReplacePullRequestReviewRequestsParams struct {
	ReviewRequests []byte
	RepoID         int64
	PrNumber       int32
	GhUpdatedAt    pgtype.Timestamptz
	FirstSeenAt    pgtype.Timestamptz
	HeadSha        string
	SyncedAt       pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	Etag           string
	SyncSource     string
}

// The parent pull request's updated_at is the C-C2 observation version for
// this timestamp-less GitHub connection. Equal-version replacements remain
// eligible so a pure request-set change is not swallowed.
func (q *Queries) ReplacePullRequestReviewRequests(ctx context.Context, arg ReplacePullRequestReviewRequestsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, replacePullRequestReviewRequests,
		arg.ReviewRequests,
		arg.RepoID,
		arg.PrNumber,
		arg.GhUpdatedAt,
		arg.FirstSeenAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var reviewer_key interface{}
		if err := rows.Scan(&reviewer_key); err != nil {
			return nil, err
		}
		items = append(items, reviewer_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replacePullRequestReviews = `-- name: ReplacePullRequestReviews :many
WITH input AS (
    SELECT NULLIF((element->>'gh_id')::bigint, 0) AS gh_id,
           element->>'node_id' AS node_id,
           element->>'author_kind' AS author_kind,
           NULLIF(element->>'author_node_id', '') AS author_node_id,
           NULLIF(element->>'author_login', '') AS author_login,
           element->>'state' AS state,
           (element->>'submitted_at')::timestamptz AS submitted_at,
           NULLIF(element->>'commit_oid', '') AS commit_oid,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at
    FROM jsonb_array_elements($1::jsonb) AS element
),
eligible AS (
    SELECT pull_requests.repo_id
    FROM pull_requests
    WHERE pull_requests.repo_id = $2
      AND pull_requests.number = $3
      AND pull_requests.tombstoned_at IS NULL
      AND (
          pull_requests.gh_updated_at IS NULL
          OR pull_requests.gh_updated_at <= $4
      )
),
upserted AS (
    INSERT INTO pull_request_reviews (
        gh_id, node_id, repo_id, pr_number, author_kind, author_node_id,
        author_login, state, submitted_at, commit_oid, gh_updated_at,
        head_sha, synced_at, etag, sync_source, tombstoned_at,
        last_checked_at
    )
    SELECT input.gh_id, input.node_id, $2,
           $3, input.author_kind, input.author_node_id,
           input.author_login, input.state, input.submitted_at,
           input.commit_oid, input.gh_updated_at, $5,
           $6, $7, $8, NULL,
           $9
    FROM input
    WHERE EXISTS (SELECT 1 FROM eligible)
    ON CONFLICT (node_id) DO UPDATE
    SET gh_id = EXCLUDED.gh_id,
        repo_id = EXCLUDED.repo_id,
        pr_number = EXCLUDED.pr_number,
        author_kind = EXCLUDED.author_kind,
        author_node_id = EXCLUDED.author_node_id,
        author_login = EXCLUDED.author_login,
        state = EXCLUDED.state,
        submitted_at = EXCLUDED.submitted_at,
        commit_oid = EXCLUDED.commit_oid,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE ROW(
              CASE
                  WHEN EXCLUDED.state = 'dismissed' THEN 2
                  WHEN EXCLUDED.submitted_at IS NOT NULL THEN 1
                  ELSE 0
              END,
              COALESCE(
                  EXCLUDED.submitted_at,
                  '-infinity'::timestamptz
              ),
              EXCLUDED.gh_updated_at
          ) > ROW(
              CASE
                  WHEN pull_request_reviews.state = 'dismissed' THEN 2
                  WHEN pull_request_reviews.submitted_at IS NOT NULL THEN 1
                  ELSE 0
              END,
              COALESCE(
                  pull_request_reviews.submitted_at,
                  '-infinity'::timestamptz
              ),
              pull_request_reviews.gh_updated_at
          )
       OR (
           ROW(
               CASE
                   WHEN EXCLUDED.state = 'dismissed' THEN 2
                   WHEN EXCLUDED.submitted_at IS NOT NULL THEN 1
                   ELSE 0
               END,
               COALESCE(
                   EXCLUDED.submitted_at,
                   '-infinity'::timestamptz
               ),
               EXCLUDED.gh_updated_at
           ) = ROW(
               CASE
                   WHEN pull_request_reviews.state = 'dismissed' THEN 2
                   WHEN pull_request_reviews.submitted_at IS NOT NULL THEN 1
                   ELSE 0
               END,
               COALESCE(
                   pull_request_reviews.submitted_at,
                   '-infinity'::timestamptz
               ),
               pull_request_reviews.gh_updated_at
           )
           AND (
               (
                   pull_request_reviews.tombstoned_at IS NULL
                   AND ROW(
                   EXCLUDED.gh_id, EXCLUDED.repo_id, EXCLUDED.pr_number,
                   EXCLUDED.author_kind, EXCLUDED.author_node_id,
                   EXCLUDED.author_login, EXCLUDED.state,
                   EXCLUDED.submitted_at, EXCLUDED.commit_oid,
                   EXCLUDED.head_sha
                   ) IS DISTINCT FROM ROW(
                   pull_request_reviews.gh_id,
                   pull_request_reviews.repo_id,
                   pull_request_reviews.pr_number,
                   pull_request_reviews.author_kind,
                   pull_request_reviews.author_node_id,
                   pull_request_reviews.author_login,
                   pull_request_reviews.state,
                   pull_request_reviews.submitted_at,
                   pull_request_reviews.commit_oid,
                       pull_request_reviews.head_sha
                   )
               )
               OR (
                   pull_request_reviews.tombstoned_at IS NOT NULL
                   AND EXCLUDED.last_checked_at >
                       pull_request_reviews.tombstoned_at
                   AND EXISTS (SELECT 1 FROM eligible)
               )
           )
       )
    RETURNING node_id
),
tombstoned AS (
    UPDATE pull_request_reviews
    SET tombstoned_at = $9,
        synced_at = $6,
        last_checked_at = $9,
        etag = $7,
        sync_source = $8
    WHERE repo_id = $2
      AND pr_number = $3
      AND tombstoned_at IS NULL
      AND EXISTS (SELECT 1 FROM eligible)
      AND last_checked_at <= $9
      AND NOT EXISTS (
          SELECT 1 FROM input
          WHERE input.node_id = pull_request_reviews.node_id
      )
    RETURNING node_id
)
SELECT node_id FROM upserted
UNION ALL
SELECT node_id FROM tombstoned
`

type ReplacePullRequestReviewsParams struct {
	Reviews           []byte
	RepoID            int64
	PrNumber          int32
	ParentGhUpdatedAt pgtype.Timestamptz
	HeadSha           string
	SyncedAt          pgtype.Timestamptz
	Etag              string
	SyncSource        string
	LastCheckedAt     pgtype.Timestamptz
}

func (q *Queries) ReplacePullRequestReviews(ctx context.Context, arg ReplacePullRequestReviewsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, replacePullRequestReviews,
		arg.Reviews,
		arg.RepoID,
		arg.PrNumber,
		arg.ParentGhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
		arg.LastCheckedAt,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceRepoRules = `-- name: ReplaceRepoRules :many
WITH input AS (
    SELECT element->>'rule_key' AS rule_key,
           element->'rule' AS rule,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at,
           element->>'head_sha' AS head_sha
    FROM jsonb_array_elements($1::jsonb) AS element
),
upserted AS (
    INSERT INTO repo_rules (
        repo_id, rule_key, rule, gh_updated_at, head_sha, synced_at,
        last_checked_at, etag, sync_source, tombstoned_at
    )
    SELECT $2, input.rule_key, input.rule,
           input.gh_updated_at, input.head_sha, $3,
           $4, $5,
           $6, NULL
    FROM input
    ON CONFLICT (repo_id, rule_key) DO UPDATE
    SET rule = EXCLUDED.rule,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE (
           repo_rules.gh_updated_at IS NULL
           AND EXCLUDED.gh_updated_at IS NOT NULL
       )
       OR EXCLUDED.gh_updated_at > repo_rules.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at IS NOT DISTINCT FROM repo_rules.gh_updated_at
           AND ROW(EXCLUDED.rule, EXCLUDED.head_sha)
               IS DISTINCT FROM ROW(repo_rules.rule, repo_rules.head_sha)
       )
       OR (
           repo_rules.tombstoned_at IS NOT NULL
           AND EXCLUDED.last_checked_at > repo_rules.tombstoned_at
       )
    RETURNING rule_key
),
tombstoned AS (
    UPDATE repo_rules
    SET tombstoned_at = $4,
        synced_at = $3,
        last_checked_at = $4,
        etag = $5,
        sync_source = $6
    WHERE repo_id = $2
      AND tombstoned_at IS NULL
      AND last_checked_at <= $4
      AND NOT EXISTS (
          SELECT 1 FROM input WHERE input.rule_key = repo_rules.rule_key
      )
    RETURNING rule_key
)
SELECT rule_key FROM upserted
UNION ALL
SELECT rule_key FROM tombstoned
`

type ReplaceRepoRulesParams struct {
	Rules         []byte
	RepoID        int64
	SyncedAt      pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	Etag          string
	SyncSource    string
}

func (q *Queries) ReplaceRepoRules(ctx context.Context, arg ReplaceRepoRulesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, replaceRepoRules,
		arg.Rules,
		arg.RepoID,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var rule_key string
		if err := rows.Scan(&rule_key); err != nil {
			return nil, err
		}
		items = append(items, rule_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceReviewThreads = `-- name: ReplaceReviewThreads :many
WITH input AS (
    SELECT element->>'id' AS id,
           (element->>'is_resolved')::boolean AS is_resolved,
           (element->>'is_outdated')::boolean AS is_outdated,
           element->>'path' AS path,
           (element->>'line')::int AS line,
           element->'comments' AS comments,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at
    FROM jsonb_array_elements($1::jsonb) AS element
),
upserted AS (
    INSERT INTO review_threads (
        id, repo_id, pr_number, is_resolved, is_outdated, path, line,
        comments, gh_updated_at, head_sha, synced_at, last_checked_at,
        etag, sync_source, tombstoned_at
    )
    SELECT input.id, $2, $3,
           input.is_resolved, input.is_outdated, input.path, input.line,
           input.comments, input.gh_updated_at, $4,
           $5, $6,
           $7, $8, NULL
    FROM input
    ON CONFLICT (id) DO UPDATE
    SET repo_id = EXCLUDED.repo_id,
        pr_number = EXCLUDED.pr_number,
        is_resolved = EXCLUDED.is_resolved,
        is_outdated = EXCLUDED.is_outdated,
        path = EXCLUDED.path,
        line = EXCLUDED.line,
        comments = EXCLUDED.comments,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        last_checked_at = EXCLUDED.last_checked_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE review_threads.gh_updated_at IS NULL
       OR EXCLUDED.gh_updated_at > review_threads.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at IS NOT DISTINCT FROM review_threads.gh_updated_at
           AND ROW(
               EXCLUDED.repo_id, EXCLUDED.pr_number, EXCLUDED.is_resolved,
               EXCLUDED.is_outdated, EXCLUDED.path, EXCLUDED.line,
               EXCLUDED.comments, EXCLUDED.head_sha
           ) IS DISTINCT FROM ROW(
               review_threads.repo_id, review_threads.pr_number,
               review_threads.is_resolved, review_threads.is_outdated,
               review_threads.path, review_threads.line,
               review_threads.comments, review_threads.head_sha
           )
       )
       OR (
           review_threads.tombstoned_at IS NOT NULL
           AND EXCLUDED.last_checked_at > review_threads.tombstoned_at
       )
    RETURNING id
),
tombstoned AS (
    UPDATE review_threads
    SET tombstoned_at = $6,
        synced_at = $5,
        last_checked_at = $6,
        etag = $7,
        sync_source = $8
    WHERE repo_id = $2
      AND pr_number = $3
      AND tombstoned_at IS NULL
      AND last_checked_at <= $6
      AND NOT EXISTS (SELECT 1 FROM input WHERE input.id = review_threads.id)
    RETURNING id
)
SELECT id FROM upserted
UNION ALL
SELECT id FROM tombstoned
`

type ReplaceReviewThreadsParams struct {
	Threads       []byte
	RepoID        int64
	PrNumber      int32
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	Etag          string
	SyncSource    string
}

func (q *Queries) ReplaceReviewThreads(ctx context.Context, arg ReplaceReviewThreadsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, replaceReviewThreads,
		arg.Threads,
		arg.RepoID,
		arg.PrNumber,
		arg.HeadSha,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstonePullRequest = `-- name: TombstonePullRequest :one
UPDATE pull_requests
SET tombstoned_at = $1,
    synced_at = $2,
    last_checked_at = GREATEST(last_checked_at, $1),
    display_until = NULL,
    etag = '',
    sync_source = $3
WHERE repo_id = $4
  AND number = $5
  AND tombstoned_at IS NULL
  AND last_checked_at <= $1
RETURNING id, repo_id, gh_id, node_id, number, title, state, draft, author_login, head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state, stack_number, stack_position, gh_updated_at, synced_at, etag, sync_source, tombstoned_at, last_checked_at, display_until
`

type TombstonePullRequestParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	PrNumber     int32
}

func (q *Queries) TombstonePullRequest(ctx context.Context, arg TombstonePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, tombstonePullRequest,
		arg.TombstonedAt,
		arg.SyncedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.PrNumber,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
	)
	return i, err
}

const tombstonePullRequestComments = `-- name: TombstonePullRequestComments :many
UPDATE pull_request_comments
SET tombstoned_at = $1,
    synced_at = $1,
    last_checked_at = GREATEST(last_checked_at, $1),
    etag = '',
    sync_source = $2
WHERE repo_id = $3
  AND pr_number = $4
  AND tombstoned_at IS NULL
RETURNING node_id
`

type TombstonePullRequestCommentsParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	PrNumber     int32
}

func (q *Queries) TombstonePullRequestComments(ctx context.Context, arg TombstonePullRequestCommentsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, tombstonePullRequestComments,
		arg.TombstonedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstonePullRequestReviewRequests = `-- name: TombstonePullRequestReviewRequests :many
UPDATE pull_request_review_requests
SET tombstoned_at = $1,
    synced_at = $1,
    last_checked_at = GREATEST(
        last_checked_at,
        $1
    ),
    etag = '',
    sync_source = $2
WHERE repo_id = $3
  AND pr_number = $4
  AND tombstoned_at IS NULL
RETURNING reviewer_kind || ':' || reviewer_gh_id::text AS reviewer_key
`

type TombstonePullRequestReviewRequestsParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	PrNumber     int32
}

func (q *Queries) TombstonePullRequestReviewRequests(ctx context.Context, arg TombstonePullRequestReviewRequestsParams) ([]interface{}, error) {
	rows, err := q.db.Query(ctx, tombstonePullRequestReviewRequests,
		arg.TombstonedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []interface{}
	for rows.Next() {
		var reviewer_key interface{}
		if err := rows.Scan(&reviewer_key); err != nil {
			return nil, err
		}
		items = append(items, reviewer_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstonePullRequestReviews = `-- name: TombstonePullRequestReviews :many
UPDATE pull_request_reviews
SET tombstoned_at = $1,
    synced_at = $1,
    last_checked_at = GREATEST(last_checked_at, $1),
    etag = '',
    sync_source = $2
WHERE repo_id = $3
  AND pr_number = $4
  AND tombstoned_at IS NULL
RETURNING node_id
`

type TombstonePullRequestReviewsParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	PrNumber     int32
}

func (q *Queries) TombstonePullRequestReviews(ctx context.Context, arg TombstonePullRequestReviewsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, tombstonePullRequestReviews,
		arg.TombstonedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.PrNumber,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var node_id string
		if err := rows.Scan(&node_id); err != nil {
			return nil, err
		}
		items = append(items, node_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstoneRepository = `-- name: TombstoneRepository :one
UPDATE repos
SET tombstoned_at = $1,
    synced_at = $2,
    last_checked_at = GREATEST(last_checked_at, $1),
    etag = '',
    sync_source = $3
WHERE gh_id = $4
  AND tombstoned_at IS NULL
  AND last_checked_at <= $1
RETURNING id, installation_id, org_id, gh_id, node_id, owner, name, full_name, default_branch, archived, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at, last_checked_at
`

type TombstoneRepositoryParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
	SyncSource   string
	GhID         int64
}

// C-R3 repository disappearance is authoritative only after the installation
// listing omits it and this entity fetch confirms 404.
func (q *Queries) TombstoneRepository(ctx context.Context, arg TombstoneRepositoryParams) (Repo, error) {
	row := q.db.QueryRow(ctx, tombstoneRepository,
		arg.TombstonedAt,
		arg.SyncedAt,
		arg.SyncSource,
		arg.GhID,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
	)
	return i, err
}

const tombstoneStack = `-- name: TombstoneStack :one
UPDATE stacks
SET tombstoned_at = $1,
    open = false,
    synced_at = $2,
    last_checked_at = GREATEST(last_checked_at, $1),
    display_until = NULL,
    etag = '',
    sync_source = $3
WHERE repo_id = $4
  AND number = $5
  AND tombstoned_at IS NULL
  AND last_checked_at <= $1
RETURNING id, repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at, last_checked_at, display_until
`

type TombstoneStackParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	StackNumber  int32
}

func (q *Queries) TombstoneStack(ctx context.Context, arg TombstoneStackParams) (Stack, error) {
	row := q.db.QueryRow(ctx, tombstoneStack,
		arg.TombstonedAt,
		arg.SyncedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.StackNumber,
	)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
	)
	return i, err
}

const touchCheckRunsCheckedAt = `-- name: TouchCheckRunsCheckedAt :exec
UPDATE check_runs
SET last_checked_at = GREATEST(last_checked_at, $1),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE repo_id = $3
  AND head_sha = $4
`

type TouchCheckRunsCheckedAtParams struct {
	CheckedAt pgtype.Timestamptz
	Etag      string
	RepoID    int64
	HeadSha   string
}

func (q *Queries) TouchCheckRunsCheckedAt(ctx context.Context, arg TouchCheckRunsCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchCheckRunsCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.HeadSha,
	)
	return err
}

const touchPullRequestCheckedAt = `-- name: TouchPullRequestCheckedAt :exec
UPDATE pull_requests
SET last_checked_at = GREATEST(last_checked_at, $1),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE repo_id = $3
  AND number = $4
`

type TouchPullRequestCheckedAtParams struct {
	CheckedAt pgtype.Timestamptz
	Etag      string
	RepoID    int64
	PrNumber  int32
}

func (q *Queries) TouchPullRequestCheckedAt(ctx context.Context, arg TouchPullRequestCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchPullRequestCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.PrNumber,
	)
	return err
}

const touchPullRequestCommentsCheckedAt = `-- name: TouchPullRequestCommentsCheckedAt :exec
UPDATE pull_request_comments
SET last_checked_at = GREATEST(
        pull_request_comments.last_checked_at,
        $1
    ),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE pull_request_comments.repo_id = $3
  AND pull_request_comments.pr_number = $4
  AND pull_request_comments.tombstoned_at IS NULL
  AND EXISTS (
      SELECT 1 FROM pull_requests
      WHERE pull_requests.repo_id = $3
        AND pull_requests.number = $4
        AND pull_requests.tombstoned_at IS NULL
        AND (
            pull_requests.gh_updated_at IS NULL
            OR pull_requests.gh_updated_at <= $5
        )
  )
`

type TouchPullRequestCommentsCheckedAtParams struct {
	CheckedAt         pgtype.Timestamptz
	Etag              string
	RepoID            int64
	PrNumber          int32
	ParentGhUpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchPullRequestCommentsCheckedAt(ctx context.Context, arg TouchPullRequestCommentsCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchPullRequestCommentsCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.PrNumber,
		arg.ParentGhUpdatedAt,
	)
	return err
}

const touchPullRequestReviewRequestsCheckedAt = `-- name: TouchPullRequestReviewRequestsCheckedAt :exec
UPDATE pull_request_review_requests
SET last_checked_at = GREATEST(
        pull_request_review_requests.last_checked_at,
        $1
    ),
    etag = CASE WHEN $2::text = ''
                THEN pull_request_review_requests.etag
                ELSE $2::text END
WHERE pull_request_review_requests.repo_id = $3
  AND pull_request_review_requests.pr_number = $4
  AND pull_request_review_requests.tombstoned_at IS NULL
  AND EXISTS (
      SELECT 1
      FROM pull_requests
      WHERE pull_requests.repo_id = $3
        AND pull_requests.number = $4
        AND pull_requests.tombstoned_at IS NULL
        AND (
            pull_requests.gh_updated_at IS NULL
            OR pull_requests.gh_updated_at <= $5
        )
  )
`

type TouchPullRequestReviewRequestsCheckedAtParams struct {
	CheckedAt   pgtype.Timestamptz
	Etag        string
	RepoID      int64
	PrNumber    int32
	GhUpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchPullRequestReviewRequestsCheckedAt(ctx context.Context, arg TouchPullRequestReviewRequestsCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchPullRequestReviewRequestsCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.PrNumber,
		arg.GhUpdatedAt,
	)
	return err
}

const touchPullRequestReviewsCheckedAt = `-- name: TouchPullRequestReviewsCheckedAt :exec
UPDATE pull_request_reviews
SET last_checked_at = GREATEST(
        pull_request_reviews.last_checked_at,
        $1
    ),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE pull_request_reviews.repo_id = $3
  AND pull_request_reviews.pr_number = $4
  AND pull_request_reviews.tombstoned_at IS NULL
  AND EXISTS (
      SELECT 1 FROM pull_requests
      WHERE pull_requests.repo_id = $3
        AND pull_requests.number = $4
        AND pull_requests.tombstoned_at IS NULL
        AND (
            pull_requests.gh_updated_at IS NULL
            OR pull_requests.gh_updated_at <= $5
        )
  )
`

type TouchPullRequestReviewsCheckedAtParams struct {
	CheckedAt         pgtype.Timestamptz
	Etag              string
	RepoID            int64
	PrNumber          int32
	ParentGhUpdatedAt pgtype.Timestamptz
}

func (q *Queries) TouchPullRequestReviewsCheckedAt(ctx context.Context, arg TouchPullRequestReviewsCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchPullRequestReviewsCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.PrNumber,
		arg.ParentGhUpdatedAt,
	)
	return err
}

const touchRepoRulesCheckedAt = `-- name: TouchRepoRulesCheckedAt :exec
UPDATE repo_rules
SET last_checked_at = GREATEST(last_checked_at, $1)
WHERE repo_id = $2
`

type TouchRepoRulesCheckedAtParams struct {
	CheckedAt pgtype.Timestamptz
	RepoID    int64
}

func (q *Queries) TouchRepoRulesCheckedAt(ctx context.Context, arg TouchRepoRulesCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchRepoRulesCheckedAt, arg.CheckedAt, arg.RepoID)
	return err
}

const touchRepositoryCheckedAt = `-- name: TouchRepositoryCheckedAt :exec
UPDATE repos
SET last_checked_at = GREATEST(last_checked_at, $1),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE gh_id = $3
`

type TouchRepositoryCheckedAtParams struct {
	CheckedAt pgtype.Timestamptz
	Etag      string
	GhID      int64
}

func (q *Queries) TouchRepositoryCheckedAt(ctx context.Context, arg TouchRepositoryCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchRepositoryCheckedAt, arg.CheckedAt, arg.Etag, arg.GhID)
	return err
}

const touchReviewThreadsCheckedAt = `-- name: TouchReviewThreadsCheckedAt :exec
UPDATE review_threads
SET last_checked_at = GREATEST(last_checked_at, $1)
WHERE repo_id = $2
  AND pr_number = $3
`

type TouchReviewThreadsCheckedAtParams struct {
	CheckedAt pgtype.Timestamptz
	RepoID    int64
	PrNumber  int32
}

func (q *Queries) TouchReviewThreadsCheckedAt(ctx context.Context, arg TouchReviewThreadsCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchReviewThreadsCheckedAt, arg.CheckedAt, arg.RepoID, arg.PrNumber)
	return err
}

const touchStackCheckedAt = `-- name: TouchStackCheckedAt :exec
UPDATE stacks
SET last_checked_at = GREATEST(last_checked_at, $1),
    etag = CASE WHEN $2::text = '' THEN etag
                ELSE $2::text END
WHERE repo_id = $3
  AND number = $4
`

type TouchStackCheckedAtParams struct {
	CheckedAt   pgtype.Timestamptz
	Etag        string
	RepoID      int64
	StackNumber int32
}

func (q *Queries) TouchStackCheckedAt(ctx context.Context, arg TouchStackCheckedAtParams) error {
	_, err := q.db.Exec(ctx, touchStackCheckedAt,
		arg.CheckedAt,
		arg.Etag,
		arg.RepoID,
		arg.StackNumber,
	)
	return err
}

const upsertPullRequestWriteIfNewer = `-- name: UpsertPullRequestWriteIfNewer :one
INSERT INTO pull_requests (
    repo_id, gh_id, node_id, number, title, state, draft, author_login,
    head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state,
    stack_number, stack_position, gh_updated_at, synced_at, last_checked_at,
    etag, sync_source, tombstoned_at, display_until
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14,
    CASE WHEN $15::boolean
         THEN $16::int ELSE NULL END,
    CASE WHEN $15::boolean
         THEN $17::int ELSE NULL END,
    $18, $19,
    $20, $21, $22, NULL,
    CASE WHEN $6::text = 'open'
         THEN NULL
         ELSE clock_timestamp() + make_interval(
             secs => $23::int
         )
    END
)
ON CONFLICT (repo_id, number) DO UPDATE
SET gh_id = EXCLUDED.gh_id,
    node_id = EXCLUDED.node_id,
    title = EXCLUDED.title,
    state = EXCLUDED.state,
    draft = EXCLUDED.draft,
    author_login = EXCLUDED.author_login,
    head_ref = EXCLUDED.head_ref,
    head_sha = EXCLUDED.head_sha,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    review_decision = EXCLUDED.review_decision,
    mergeable_state = EXCLUDED.mergeable_state,
    stack_number = CASE
        WHEN $15::boolean
        THEN EXCLUDED.stack_number
        ELSE pull_requests.stack_number
    END,
    stack_position = CASE
        WHEN $15::boolean
        THEN EXCLUDED.stack_position
        ELSE pull_requests.stack_position
    END,
    gh_updated_at = EXCLUDED.gh_updated_at,
    synced_at = EXCLUDED.synced_at,
    last_checked_at = EXCLUDED.last_checked_at,
    etag = CASE
        WHEN EXCLUDED.etag = '' THEN pull_requests.etag
        ELSE EXCLUDED.etag
    END,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL,
    display_until = CASE
        WHEN EXCLUDED.state = 'open' THEN NULL
        WHEN pull_requests.state = 'open'
        THEN clock_timestamp() + make_interval(
            secs => $23::int
        )
        ELSE pull_requests.display_until
    END
WHERE pull_requests.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > pull_requests.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at IS NOT DISTINCT FROM pull_requests.gh_updated_at
       AND ROW(
           EXCLUDED.gh_id, EXCLUDED.node_id, EXCLUDED.title, EXCLUDED.state,
           EXCLUDED.draft, EXCLUDED.author_login, EXCLUDED.head_ref,
           EXCLUDED.head_sha, EXCLUDED.base_ref, EXCLUDED.base_sha,
           EXCLUDED.review_decision, EXCLUDED.mergeable_state,
           CASE WHEN $15::boolean
                THEN EXCLUDED.stack_number ELSE pull_requests.stack_number END,
           CASE WHEN $15::boolean
                THEN EXCLUDED.stack_position ELSE pull_requests.stack_position END
       ) IS DISTINCT FROM ROW(
           pull_requests.gh_id, pull_requests.node_id, pull_requests.title,
           pull_requests.state, pull_requests.draft,
           pull_requests.author_login, pull_requests.head_ref,
           pull_requests.head_sha, pull_requests.base_ref,
           pull_requests.base_sha, pull_requests.review_decision,
           pull_requests.mergeable_state, pull_requests.stack_number,
           pull_requests.stack_position
       )
   )
   OR (
       pull_requests.tombstoned_at IS NOT NULL
       AND EXCLUDED.last_checked_at > pull_requests.tombstoned_at
   )
RETURNING id, repo_id, gh_id, node_id, number, title, state, draft, author_login, head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state, stack_number, stack_position, gh_updated_at, synced_at, etag, sync_source, tombstoned_at, last_checked_at, display_until
`

type UpsertPullRequestWriteIfNewerParams struct {
	RepoID               int64
	GhID                 pgtype.Int8
	NodeID               string
	PrNumber             int32
	Title                string
	State                string
	Draft                bool
	AuthorLogin          string
	HeadRef              string
	HeadSha              string
	BaseRef              string
	BaseSha              string
	ReviewDecision       string
	MergeableState       string
	MembershipKnown      bool
	StackNumber          pgtype.Int4
	StackPosition        pgtype.Int4
	GhUpdatedAt          pgtype.Timestamptz
	SyncedAt             pgtype.Timestamptz
	LastCheckedAt        pgtype.Timestamptz
	Etag                 string
	SyncSource           string
	DisplayWindowSeconds int32
}

func (q *Queries) UpsertPullRequestWriteIfNewer(ctx context.Context, arg UpsertPullRequestWriteIfNewerParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequestWriteIfNewer,
		arg.RepoID,
		arg.GhID,
		arg.NodeID,
		arg.PrNumber,
		arg.Title,
		arg.State,
		arg.Draft,
		arg.AuthorLogin,
		arg.HeadRef,
		arg.HeadSha,
		arg.BaseRef,
		arg.BaseSha,
		arg.ReviewDecision,
		arg.MergeableState,
		arg.MembershipKnown,
		arg.StackNumber,
		arg.StackPosition,
		arg.GhUpdatedAt,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
		arg.DisplayWindowSeconds,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
	)
	return i, err
}

const upsertRepoRuleSyncState = `-- name: UpsertRepoRuleSyncState :exec
INSERT INTO repo_rule_sync_state (repo_id, etag, last_checked_at)
VALUES ($1, $2, $3)
ON CONFLICT (repo_id) DO UPDATE
SET etag = CASE
        WHEN EXCLUDED.etag = '' THEN repo_rule_sync_state.etag
        ELSE EXCLUDED.etag
    END,
    last_checked_at = GREATEST(
        repo_rule_sync_state.last_checked_at,
        EXCLUDED.last_checked_at
    )
`

type UpsertRepoRuleSyncStateParams struct {
	RepoID    int64
	Etag      string
	CheckedAt pgtype.Timestamptz
}

func (q *Queries) UpsertRepoRuleSyncState(ctx context.Context, arg UpsertRepoRuleSyncStateParams) error {
	_, err := q.db.Exec(ctx, upsertRepoRuleSyncState, arg.RepoID, arg.Etag, arg.CheckedAt)
	return err
}

const upsertRepositoryAlias = `-- name: UpsertRepositoryAlias :exec
INSERT INTO repo_aliases (full_name, repo_id, first_seen_at, last_seen_at)
VALUES (
    $1, $2,
    $3, $3
)
ON CONFLICT (full_name) DO UPDATE
SET repo_id = EXCLUDED.repo_id,
    last_seen_at = GREATEST(repo_aliases.last_seen_at, EXCLUDED.last_seen_at)
WHERE EXCLUDED.last_seen_at >= repo_aliases.last_seen_at
`

type UpsertRepositoryAliasParams struct {
	FullName   string
	RepoID     int64
	ObservedAt pgtype.Timestamptz
}

func (q *Queries) UpsertRepositoryAlias(ctx context.Context, arg UpsertRepositoryAliasParams) error {
	_, err := q.db.Exec(ctx, upsertRepositoryAlias, arg.FullName, arg.RepoID, arg.ObservedAt)
	return err
}

const upsertRepositoryWriteIfNewer = `-- name: UpsertRepositoryWriteIfNewer :one
INSERT INTO repos (
    installation_id, org_id, gh_id, node_id, owner, name, full_name,
    default_branch, archived, gh_updated_at, head_sha, synced_at,
    last_checked_at, etag, sync_source, tombstoned_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9,
    $10, $11, $12,
    $13, $14, $15, NULL
)
ON CONFLICT (gh_id) DO UPDATE
SET installation_id = EXCLUDED.installation_id,
    org_id = EXCLUDED.org_id,
    node_id = EXCLUDED.node_id,
    owner = EXCLUDED.owner,
    name = EXCLUDED.name,
    full_name = EXCLUDED.full_name,
    default_branch = EXCLUDED.default_branch,
    archived = EXCLUDED.archived,
    gh_updated_at = EXCLUDED.gh_updated_at,
    head_sha = EXCLUDED.head_sha,
    synced_at = EXCLUDED.synced_at,
    last_checked_at = EXCLUDED.last_checked_at,
    etag = EXCLUDED.etag,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL
WHERE repos.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > repos.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at IS NOT DISTINCT FROM repos.gh_updated_at
       AND ROW(
           EXCLUDED.installation_id, EXCLUDED.org_id, EXCLUDED.node_id,
           EXCLUDED.owner, EXCLUDED.name, EXCLUDED.full_name,
           EXCLUDED.default_branch, EXCLUDED.archived, EXCLUDED.head_sha
       ) IS DISTINCT FROM ROW(
           repos.installation_id, repos.org_id, repos.node_id,
           repos.owner, repos.name, repos.full_name,
           repos.default_branch, repos.archived, repos.head_sha
       )
   )
   OR (
       repos.tombstoned_at IS NOT NULL
       AND EXCLUDED.last_checked_at > repos.tombstoned_at
   )
RETURNING id, installation_id, org_id, gh_id, node_id, owner, name, full_name, default_branch, archived, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at, last_checked_at
`

type UpsertRepositoryWriteIfNewerParams struct {
	InstallationID int64
	OrgID          int64
	GhID           int64
	NodeID         string
	Owner          string
	Name           string
	FullName       string
	DefaultBranch  string
	Archived       bool
	GhUpdatedAt    pgtype.Timestamptz
	HeadSha        string
	SyncedAt       pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	Etag           string
	SyncSource     string
}

func (q *Queries) UpsertRepositoryWriteIfNewer(ctx context.Context, arg UpsertRepositoryWriteIfNewerParams) (Repo, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryWriteIfNewer,
		arg.InstallationID,
		arg.OrgID,
		arg.GhID,
		arg.NodeID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
		arg.Archived,
		arg.GhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
	)
	return i, err
}

const upsertStackWriteIfNewer = `-- name: UpsertStackWriteIfNewer :one
INSERT INTO stacks (
    repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries,
    gh_updated_at, head_sha, synced_at, last_checked_at, etag, sync_source,
    tombstoned_at, display_until
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, $14, NULL,
    CASE WHEN $7::boolean
         THEN NULL
         ELSE clock_timestamp() + make_interval(
             secs => $15::int
         )
    END
)
ON CONFLICT (repo_id, number) DO UPDATE
SET gh_id = EXCLUDED.gh_id,
    node_id = EXCLUDED.node_id,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    open = EXCLUDED.open,
    entries = EXCLUDED.entries,
    gh_updated_at = EXCLUDED.gh_updated_at,
    head_sha = EXCLUDED.head_sha,
    synced_at = EXCLUDED.synced_at,
    last_checked_at = EXCLUDED.last_checked_at,
    etag = EXCLUDED.etag,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL,
    display_until = CASE
        WHEN EXCLUDED.open THEN NULL
        WHEN stacks.open THEN clock_timestamp() + make_interval(
            secs => $15::int
        )
        ELSE stacks.display_until
    END
WHERE stacks.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > stacks.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at IS NOT DISTINCT FROM stacks.gh_updated_at
       AND ROW(
           EXCLUDED.gh_id, EXCLUDED.node_id, EXCLUDED.base_ref,
           EXCLUDED.base_sha, EXCLUDED.open, EXCLUDED.entries,
           EXCLUDED.head_sha
       ) IS DISTINCT FROM ROW(
           stacks.gh_id, stacks.node_id, stacks.base_ref,
           stacks.base_sha, stacks.open, stacks.entries, stacks.head_sha
       )
   )
   OR (
       stacks.tombstoned_at IS NOT NULL
       AND EXCLUDED.last_checked_at > stacks.tombstoned_at
   )
RETURNING id, repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at, last_checked_at, display_until
`

type UpsertStackWriteIfNewerParams struct {
	RepoID               int64
	GhID                 pgtype.Int8
	NodeID               string
	StackNumber          int32
	BaseRef              string
	BaseSha              string
	Open                 bool
	Entries              []byte
	GhUpdatedAt          pgtype.Timestamptz
	HeadSha              string
	SyncedAt             pgtype.Timestamptz
	LastCheckedAt        pgtype.Timestamptz
	Etag                 string
	SyncSource           string
	DisplayWindowSeconds int32
}

func (q *Queries) UpsertStackWriteIfNewer(ctx context.Context, arg UpsertStackWriteIfNewerParams) (Stack, error) {
	row := q.db.QueryRow(ctx, upsertStackWriteIfNewer,
		arg.RepoID,
		arg.GhID,
		arg.NodeID,
		arg.StackNumber,
		arg.BaseRef,
		arg.BaseSha,
		arg.Open,
		arg.Entries,
		arg.GhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.LastCheckedAt,
		arg.Etag,
		arg.SyncSource,
		arg.DisplayWindowSeconds,
	)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.LastCheckedAt,
		&i.DisplayUntil,
	)
	return i, err
}
