// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cache.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireEntityAdvisoryLock = `-- name: AcquireEntityAdvisoryLock :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

// C-C1: transaction-scoped serialization survives process crashes.
func (q *Queries) AcquireEntityAdvisoryLock(ctx context.Context, entityKey string) error {
	_, err := q.db.Exec(ctx, acquireEntityAdvisoryLock, entityKey)
	return err
}

const appendCheckHistory = `-- name: AppendCheckHistory :exec
WITH input AS (
    SELECT (element->>'gh_id')::bigint AS gh_id,
           element->>'name' AS name,
           element->>'status' AS status,
           element->>'conclusion' AS conclusion,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at,
           element->'observed' AS observed
    FROM jsonb_array_elements($6::jsonb) AS element
)
INSERT INTO check_history (
    check_run_gh_id, repo_id, name, status, conclusion, observed,
    gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
)
SELECT input.gh_id, $1, input.name, input.status,
       input.conclusion, input.observed, input.gh_updated_at,
       $2, $3, $4,
       $5, NULL
FROM input
ON CONFLICT DO NOTHING
`

type AppendCheckHistoryParams struct {
	RepoID     int64
	HeadSha    string
	SyncedAt   pgtype.Timestamptz
	Etag       string
	SyncSource string
	CheckRuns  []byte
}

// check_history is append-only raw material for later flake-rate derivation.
func (q *Queries) AppendCheckHistory(ctx context.Context, arg AppendCheckHistoryParams) error {
	_, err := q.db.Exec(ctx, appendCheckHistory,
		arg.RepoID,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
		arg.CheckRuns,
	)
	return err
}

const getPullRequestByKey = `-- name: GetPullRequestByKey :one
SELECT pull_requests.id, pull_requests.repo_id, pull_requests.gh_id, pull_requests.node_id, pull_requests.number, pull_requests.title, pull_requests.state, pull_requests.draft, pull_requests.author_login, pull_requests.head_ref, pull_requests.head_sha, pull_requests.base_ref, pull_requests.base_sha, pull_requests.review_decision, pull_requests.mergeable_state, pull_requests.stack_number, pull_requests.stack_position, pull_requests.gh_updated_at, pull_requests.synced_at, pull_requests.etag, pull_requests.sync_source, pull_requests.tombstoned_at, repos.full_name AS repo_full_name
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.full_name = $1
  AND pull_requests.number = $2
`

type GetPullRequestByKeyParams struct {
	RepoFullName string
	PrNumber     int32
}

type GetPullRequestByKeyRow struct {
	ID             int64
	RepoID         int64
	GhID           pgtype.Int8
	NodeID         string
	Number         int32
	Title          string
	State          string
	Draft          bool
	AuthorLogin    string
	HeadRef        string
	HeadSha        string
	BaseRef        string
	BaseSha        string
	ReviewDecision string
	MergeableState string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	GhUpdatedAt    pgtype.Timestamptz
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
	TombstonedAt   pgtype.Timestamptz
	RepoFullName   string
}

func (q *Queries) GetPullRequestByKey(ctx context.Context, arg GetPullRequestByKeyParams) (GetPullRequestByKeyRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestByKey, arg.RepoFullName, arg.PrNumber)
	var i GetPullRequestByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.RepoFullName,
	)
	return i, err
}

const getPullRequestFetchMetadata = `-- name: GetPullRequestFetchMetadata :one
SELECT pull_requests.node_id, pull_requests.etag, pull_requests.stack_number,
       pull_requests.stack_position, pull_requests.head_sha
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.full_name = $1
  AND pull_requests.number = $2
`

type GetPullRequestFetchMetadataParams struct {
	RepoFullName string
	PrNumber     int32
}

type GetPullRequestFetchMetadataRow struct {
	NodeID        string
	Etag          string
	StackNumber   pgtype.Int4
	StackPosition pgtype.Int4
	HeadSha       string
}

func (q *Queries) GetPullRequestFetchMetadata(ctx context.Context, arg GetPullRequestFetchMetadataParams) (GetPullRequestFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestFetchMetadata, arg.RepoFullName, arg.PrNumber)
	var i GetPullRequestFetchMetadataRow
	err := row.Scan(
		&i.NodeID,
		&i.Etag,
		&i.StackNumber,
		&i.StackPosition,
		&i.HeadSha,
	)
	return i, err
}

const getRepoByFullName = `-- name: GetRepoByFullName :one
SELECT id, installation_id, org_id, gh_id, node_id, owner, name, full_name, default_branch, archived, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
FROM repos
WHERE full_name = $1
`

func (q *Queries) GetRepoByFullName(ctx context.Context, fullName string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}

const getStackByKey = `-- name: GetStackByKey :one
SELECT stacks.id, stacks.repo_id, stacks.gh_id, stacks.node_id, stacks.number, stacks.base_ref, stacks.base_sha, stacks.open, stacks.entries, stacks.gh_updated_at, stacks.head_sha, stacks.synced_at, stacks.etag, stacks.sync_source, stacks.tombstoned_at, repos.full_name AS repo_full_name
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.full_name = $1
  AND stacks.number = $2
`

type GetStackByKeyParams struct {
	RepoFullName string
	StackNumber  int32
}

type GetStackByKeyRow struct {
	ID           int64
	RepoID       int64
	GhID         pgtype.Int8
	NodeID       string
	Number       int32
	BaseRef      string
	BaseSha      string
	Open         bool
	Entries      []byte
	GhUpdatedAt  pgtype.Timestamptz
	HeadSha      string
	SyncedAt     pgtype.Timestamptz
	Etag         string
	SyncSource   string
	TombstonedAt pgtype.Timestamptz
	RepoFullName string
}

func (q *Queries) GetStackByKey(ctx context.Context, arg GetStackByKeyParams) (GetStackByKeyRow, error) {
	row := q.db.QueryRow(ctx, getStackByKey, arg.RepoFullName, arg.StackNumber)
	var i GetStackByKeyRow
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
		&i.RepoFullName,
	)
	return i, err
}

const getStackFetchMetadata = `-- name: GetStackFetchMetadata :one
SELECT stacks.etag, stacks.entries, stacks.head_sha
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.full_name = $1
  AND stacks.number = $2
`

type GetStackFetchMetadataParams struct {
	RepoFullName string
	StackNumber  int32
}

type GetStackFetchMetadataRow struct {
	Etag    string
	Entries []byte
	HeadSha string
}

func (q *Queries) GetStackFetchMetadata(ctx context.Context, arg GetStackFetchMetadataParams) (GetStackFetchMetadataRow, error) {
	row := q.db.QueryRow(ctx, getStackFetchMetadata, arg.RepoFullName, arg.StackNumber)
	var i GetStackFetchMetadataRow
	err := row.Scan(&i.Etag, &i.Entries, &i.HeadSha)
	return i, err
}

const insertChangeEvent = `-- name: InsertChangeEvent :one
INSERT INTO change_events (
    stream, kind, entity_key, occurred_at, payload
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING seq
`

type InsertChangeEventParams struct {
	Stream     string
	Kind       string
	EntityKey  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

// C-C3/C-S1: called inside the same transaction as the accepted entity write.
func (q *Queries) InsertChangeEvent(ctx context.Context, arg InsertChangeEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChangeEvent,
		arg.Stream,
		arg.Kind,
		arg.EntityKey,
		arg.OccurredAt,
		arg.Payload,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const listCachedPRMemberships = `-- name: ListCachedPRMemberships :many
SELECT pull_requests.number, pull_requests.stack_number
FROM pull_requests
WHERE pull_requests.repo_id = (
        SELECT id FROM repos WHERE full_name = $1
      )
  AND pull_requests.number = ANY($2::int[])
ORDER BY pull_requests.number
`

type ListCachedPRMembershipsParams struct {
	RepoFullName string
	PrNumbers    []int32
}

type ListCachedPRMembershipsRow struct {
	Number      int32
	StackNumber pgtype.Int4
}

func (q *Queries) ListCachedPRMemberships(ctx context.Context, arg ListCachedPRMembershipsParams) ([]ListCachedPRMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listCachedPRMemberships, arg.RepoFullName, arg.PrNumbers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCachedPRMembershipsRow
	for rows.Next() {
		var i ListCachedPRMembershipsRow
		if err := rows.Scan(&i.Number, &i.StackNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRScopesByHeadSHA = `-- name: ListPRScopesByHeadSHA :many
SELECT pull_requests.number, pull_requests.stack_number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.full_name = $1
  AND pull_requests.head_sha = $2
  AND pull_requests.tombstoned_at IS NULL
ORDER BY pull_requests.number
`

type ListPRScopesByHeadSHAParams struct {
	RepoFullName string
	HeadSha      string
}

type ListPRScopesByHeadSHARow struct {
	Number      int32
	StackNumber pgtype.Int4
}

func (q *Queries) ListPRScopesByHeadSHA(ctx context.Context, arg ListPRScopesByHeadSHAParams) ([]ListPRScopesByHeadSHARow, error) {
	rows, err := q.db.Query(ctx, listPRScopesByHeadSHA, arg.RepoFullName, arg.HeadSha)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPRScopesByHeadSHARow
	for rows.Next() {
		var i ListPRScopesByHeadSHARow
		if err := rows.Scan(&i.Number, &i.StackNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRsAffectedByBranch = `-- name: ListPRsAffectedByBranch :many
SELECT DISTINCT pull_requests.number, pull_requests.stack_number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.full_name = $1
  AND pull_requests.tombstoned_at IS NULL
  AND (
      pull_requests.head_ref = $2
      OR pull_requests.base_ref = $2
  )
ORDER BY pull_requests.number
`

type ListPRsAffectedByBranchParams struct {
	RepoFullName string
	Branch       string
}

type ListPRsAffectedByBranchRow struct {
	Number      int32
	StackNumber pgtype.Int4
}

func (q *Queries) ListPRsAffectedByBranch(ctx context.Context, arg ListPRsAffectedByBranchParams) ([]ListPRsAffectedByBranchRow, error) {
	rows, err := q.db.Query(ctx, listPRsAffectedByBranch, arg.RepoFullName, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPRsAffectedByBranchRow
	for rows.Next() {
		var i ListPRsAffectedByBranchRow
		if err := rows.Scan(&i.Number, &i.StackNumber); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStacksAffectedByBranch = `-- name: ListStacksAffectedByBranch :many
SELECT DISTINCT stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.full_name = $1
  AND stacks.tombstoned_at IS NULL
  AND (
      stacks.base_ref = $2
      OR EXISTS (
          SELECT 1
          FROM jsonb_array_elements(stacks.entries) AS entry
          WHERE entry->>'head_ref' = $2
      )
  )
ORDER BY stacks.number
`

type ListStacksAffectedByBranchParams struct {
	RepoFullName string
	Branch       string
}

func (q *Queries) ListStacksAffectedByBranch(ctx context.Context, arg ListStacksAffectedByBranchParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listStacksAffectedByBranch, arg.RepoFullName, arg.Branch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDerivationDirty = `-- name: MarkDerivationDirty :exec
INSERT INTO derivation_dirty (scope_key, marked_at)
SELECT DISTINCT dirty.scope_key, $1::timestamptz
FROM unnest($2::text[]) AS dirty(scope_key)
ON CONFLICT (scope_key) DO UPDATE
SET marked_at = GREATEST(derivation_dirty.marked_at, EXCLUDED.marked_at)
`

type MarkDerivationDirtyParams struct {
	MarkedAt  pgtype.Timestamptz
	ScopeKeys []string
}

// C-D2: the caller supplies only stack or loose-PR scope keys.
func (q *Queries) MarkDerivationDirty(ctx context.Context, arg MarkDerivationDirtyParams) error {
	_, err := q.db.Exec(ctx, markDerivationDirty, arg.MarkedAt, arg.ScopeKeys)
	return err
}

const replaceCheckRuns = `-- name: ReplaceCheckRuns :many
WITH input AS (
    SELECT (element->>'gh_id')::bigint AS gh_id,
           element->>'node_id' AS node_id,
           element->>'name' AS name,
           element->>'status' AS status,
           element->>'conclusion' AS conclusion,
           element->>'details_url' AS details_url,
           element->>'app_slug' AS app_slug,
           (element->>'started_at')::timestamptz AS started_at,
           (element->>'completed_at')::timestamptz AS completed_at,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at,
           element->'observed' AS observed
    FROM jsonb_array_elements($1::jsonb) AS element
),
upserted AS (
    INSERT INTO check_runs (
        gh_id, repo_id, node_id, name, status, conclusion, details_url,
        app_slug, started_at, completed_at, gh_updated_at, head_sha,
        synced_at, etag, sync_source, tombstoned_at
    )
    SELECT input.gh_id, $2, input.node_id, input.name,
           input.status, input.conclusion, input.details_url, input.app_slug,
           input.started_at, input.completed_at, input.gh_updated_at,
           $3, $4, $5,
           $6, NULL
    FROM input
    ON CONFLICT (gh_id) DO UPDATE
    SET repo_id = EXCLUDED.repo_id,
        node_id = EXCLUDED.node_id,
        name = EXCLUDED.name,
        status = EXCLUDED.status,
        conclusion = EXCLUDED.conclusion,
        details_url = EXCLUDED.details_url,
        app_slug = EXCLUDED.app_slug,
        started_at = EXCLUDED.started_at,
        completed_at = EXCLUDED.completed_at,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE check_runs.gh_updated_at IS NULL
       OR EXCLUDED.gh_updated_at > check_runs.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at = check_runs.gh_updated_at
           AND EXCLUDED.head_sha = check_runs.head_sha
           AND EXCLUDED.synced_at >= check_runs.synced_at
           AND check_runs.tombstoned_at IS NULL
       )
    RETURNING gh_id
),
tombstoned AS (
    UPDATE check_runs
    SET tombstoned_at = $4,
        synced_at = $4,
        etag = $5,
        sync_source = $6
    WHERE repo_id = $2
      AND head_sha = $3
      AND tombstoned_at IS NULL
      AND synced_at <= $4
      AND NOT EXISTS (
          SELECT 1 FROM input WHERE input.gh_id = check_runs.gh_id
      )
    RETURNING gh_id
)
SELECT gh_id FROM upserted
UNION ALL
SELECT gh_id FROM tombstoned
`

type ReplaceCheckRunsParams struct {
	CheckRuns  []byte
	RepoID     int64
	HeadSha    string
	SyncedAt   pgtype.Timestamptz
	Etag       string
	SyncSource string
}

// C-P3: one unnest-like json recordset upsert replaces row-at-a-time writes.
func (q *Queries) ReplaceCheckRuns(ctx context.Context, arg ReplaceCheckRunsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, replaceCheckRuns,
		arg.CheckRuns,
		arg.RepoID,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var gh_id int64
		if err := rows.Scan(&gh_id); err != nil {
			return nil, err
		}
		items = append(items, gh_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceReviewThreads = `-- name: ReplaceReviewThreads :many
WITH input AS (
    SELECT element->>'id' AS id,
           (element->>'is_resolved')::boolean AS is_resolved,
           (element->>'is_outdated')::boolean AS is_outdated,
           element->>'path' AS path,
           (element->>'line')::int AS line,
           element->'comments' AS comments,
           (element->>'gh_updated_at')::timestamptz AS gh_updated_at
    FROM jsonb_array_elements($1::jsonb) AS element
),
upserted AS (
    INSERT INTO review_threads (
        id, repo_id, pr_number, is_resolved, is_outdated, path, line,
        comments, gh_updated_at, head_sha, synced_at, etag, sync_source,
        tombstoned_at
    )
    SELECT input.id, $2, $3,
           input.is_resolved, input.is_outdated, input.path, input.line,
           input.comments, input.gh_updated_at, $4,
           $5, $6, $7, NULL
    FROM input
    ON CONFLICT (id) DO UPDATE
    SET is_resolved = EXCLUDED.is_resolved,
        is_outdated = EXCLUDED.is_outdated,
        path = EXCLUDED.path,
        line = EXCLUDED.line,
        comments = EXCLUDED.comments,
        gh_updated_at = EXCLUDED.gh_updated_at,
        head_sha = EXCLUDED.head_sha,
        synced_at = EXCLUDED.synced_at,
        etag = EXCLUDED.etag,
        sync_source = EXCLUDED.sync_source,
        tombstoned_at = NULL
    WHERE review_threads.gh_updated_at IS NULL
       OR EXCLUDED.gh_updated_at > review_threads.gh_updated_at
       OR (
           EXCLUDED.gh_updated_at = review_threads.gh_updated_at
           AND EXCLUDED.head_sha = review_threads.head_sha
           AND EXCLUDED.synced_at >= review_threads.synced_at
           AND review_threads.tombstoned_at IS NULL
       )
    RETURNING id
),
tombstoned AS (
    UPDATE review_threads
    SET tombstoned_at = $5,
        synced_at = $5,
        etag = $6,
        sync_source = $7
    WHERE repo_id = $2
      AND pr_number = $3
      AND tombstoned_at IS NULL
      AND synced_at <= $5
      AND NOT EXISTS (SELECT 1 FROM input WHERE input.id = review_threads.id)
    RETURNING id
)
SELECT id FROM upserted
UNION ALL
SELECT id FROM tombstoned
`

type ReplaceReviewThreadsParams struct {
	Threads    []byte
	RepoID     int64
	PrNumber   int32
	HeadSha    string
	SyncedAt   pgtype.Timestamptz
	Etag       string
	SyncSource string
}

// C-P3: all threads returned for one PR are applied as a set.
func (q *Queries) ReplaceReviewThreads(ctx context.Context, arg ReplaceReviewThreadsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, replaceReviewThreads,
		arg.Threads,
		arg.RepoID,
		arg.PrNumber,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tombstonePullRequest = `-- name: TombstonePullRequest :one
UPDATE pull_requests
SET tombstoned_at = $1,
    synced_at = $2,
    etag = '',
    sync_source = $3
WHERE repo_id = $4
  AND number = $5
  AND tombstoned_at IS NULL
  AND synced_at <= $1
RETURNING id, repo_id, gh_id, node_id, number, title, state, draft, author_login, head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state, stack_number, stack_position, gh_updated_at, synced_at, etag, sync_source, tombstoned_at
`

type TombstonePullRequestParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	PrNumber     int32
}

func (q *Queries) TombstonePullRequest(ctx context.Context, arg TombstonePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, tombstonePullRequest,
		arg.TombstonedAt,
		arg.SyncedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.PrNumber,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}

const tombstoneStack = `-- name: TombstoneStack :one
UPDATE stacks
SET tombstoned_at = $1,
    open = false,
    synced_at = $2,
    etag = '',
    sync_source = $3
WHERE repo_id = $4
  AND number = $5
  AND tombstoned_at IS NULL
  AND synced_at <= $1
RETURNING id, repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
`

type TombstoneStackParams struct {
	TombstonedAt pgtype.Timestamptz
	SyncedAt     pgtype.Timestamptz
	SyncSource   string
	RepoID       int64
	StackNumber  int32
}

func (q *Queries) TombstoneStack(ctx context.Context, arg TombstoneStackParams) (Stack, error) {
	row := q.db.QueryRow(ctx, tombstoneStack,
		arg.TombstonedAt,
		arg.SyncedAt,
		arg.SyncSource,
		arg.RepoID,
		arg.StackNumber,
	)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}

const upsertPullRequestWriteIfNewer = `-- name: UpsertPullRequestWriteIfNewer :one
INSERT INTO pull_requests (
    repo_id, gh_id, node_id, number, title, state, draft, author_login,
    head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state,
    stack_number, stack_position, gh_updated_at, synced_at, etag, sync_source,
    tombstoned_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14,
    CASE WHEN $15::boolean
         THEN $16::int ELSE NULL END,
    CASE WHEN $15::boolean
         THEN $17::int ELSE NULL END,
    $18,
    $19, $20, $21, NULL
)
ON CONFLICT (repo_id, number) DO UPDATE
SET gh_id = EXCLUDED.gh_id,
    node_id = EXCLUDED.node_id,
    title = EXCLUDED.title,
    state = EXCLUDED.state,
    draft = EXCLUDED.draft,
    author_login = EXCLUDED.author_login,
    head_ref = EXCLUDED.head_ref,
    head_sha = EXCLUDED.head_sha,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    review_decision = EXCLUDED.review_decision,
    mergeable_state = EXCLUDED.mergeable_state,
    stack_number = CASE
        WHEN $15::boolean
        THEN EXCLUDED.stack_number
        ELSE pull_requests.stack_number
    END,
    stack_position = CASE
        WHEN $15::boolean
        THEN EXCLUDED.stack_position
        ELSE pull_requests.stack_position
    END,
    gh_updated_at = EXCLUDED.gh_updated_at,
    synced_at = EXCLUDED.synced_at,
    etag = EXCLUDED.etag,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL
WHERE pull_requests.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > pull_requests.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at = pull_requests.gh_updated_at
       AND EXCLUDED.head_sha = pull_requests.head_sha
       AND EXCLUDED.synced_at >= pull_requests.synced_at
       AND pull_requests.tombstoned_at IS NULL
   )
RETURNING id, repo_id, gh_id, node_id, number, title, state, draft, author_login, head_ref, head_sha, base_ref, base_sha, review_decision, mergeable_state, stack_number, stack_position, gh_updated_at, synced_at, etag, sync_source, tombstoned_at
`

type UpsertPullRequestWriteIfNewerParams struct {
	RepoID          int64
	GhID            pgtype.Int8
	NodeID          string
	PrNumber        int32
	Title           string
	State           string
	Draft           bool
	AuthorLogin     string
	HeadRef         string
	HeadSha         string
	BaseRef         string
	BaseSha         string
	ReviewDecision  string
	MergeableState  string
	MembershipKnown bool
	StackNumber     pgtype.Int4
	StackPosition   pgtype.Int4
	GhUpdatedAt     pgtype.Timestamptz
	SyncedAt        pgtype.Timestamptz
	Etag            string
	SyncSource      string
}

// C-C2: (gh_updated_at, head_sha) is the monotonic PR version.
func (q *Queries) UpsertPullRequestWriteIfNewer(ctx context.Context, arg UpsertPullRequestWriteIfNewerParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, upsertPullRequestWriteIfNewer,
		arg.RepoID,
		arg.GhID,
		arg.NodeID,
		arg.PrNumber,
		arg.Title,
		arg.State,
		arg.Draft,
		arg.AuthorLogin,
		arg.HeadRef,
		arg.HeadSha,
		arg.BaseRef,
		arg.BaseSha,
		arg.ReviewDecision,
		arg.MergeableState,
		arg.MembershipKnown,
		arg.StackNumber,
		arg.StackPosition,
		arg.GhUpdatedAt,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.Title,
		&i.State,
		&i.Draft,
		&i.AuthorLogin,
		&i.HeadRef,
		&i.HeadSha,
		&i.BaseRef,
		&i.BaseSha,
		&i.ReviewDecision,
		&i.MergeableState,
		&i.StackNumber,
		&i.StackPosition,
		&i.GhUpdatedAt,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}

const upsertRepositoryWriteIfNewer = `-- name: UpsertRepositoryWriteIfNewer :one
INSERT INTO repos (
    installation_id, org_id, gh_id, node_id, owner, name, full_name,
    default_branch, archived, gh_updated_at, head_sha, synced_at, etag,
    sync_source, tombstoned_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9,
    $10, $11, $12,
    $13, $14, NULL
)
ON CONFLICT (full_name) DO UPDATE
SET installation_id = EXCLUDED.installation_id,
    org_id = EXCLUDED.org_id,
    gh_id = EXCLUDED.gh_id,
    node_id = EXCLUDED.node_id,
    owner = EXCLUDED.owner,
    name = EXCLUDED.name,
    default_branch = EXCLUDED.default_branch,
    archived = EXCLUDED.archived,
    gh_updated_at = EXCLUDED.gh_updated_at,
    head_sha = EXCLUDED.head_sha,
    synced_at = EXCLUDED.synced_at,
    etag = EXCLUDED.etag,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL
WHERE repos.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > repos.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at = repos.gh_updated_at
       AND EXCLUDED.head_sha = repos.head_sha
       AND EXCLUDED.synced_at >= repos.synced_at
       AND repos.tombstoned_at IS NULL
   )
RETURNING id, installation_id, org_id, gh_id, node_id, owner, name, full_name, default_branch, archived, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
`

type UpsertRepositoryWriteIfNewerParams struct {
	InstallationID int64
	OrgID          int64
	GhID           int64
	NodeID         string
	Owner          string
	Name           string
	FullName       string
	DefaultBranch  string
	Archived       bool
	GhUpdatedAt    pgtype.Timestamptz
	HeadSha        string
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
}

// C-C2: equal versions are idempotent; only a strictly newer version may
// resurrect a tombstone.
func (q *Queries) UpsertRepositoryWriteIfNewer(ctx context.Context, arg UpsertRepositoryWriteIfNewerParams) (Repo, error) {
	row := q.db.QueryRow(ctx, upsertRepositoryWriteIfNewer,
		arg.InstallationID,
		arg.OrgID,
		arg.GhID,
		arg.NodeID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.DefaultBranch,
		arg.Archived,
		arg.GhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.OrgID,
		&i.GhID,
		&i.NodeID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.DefaultBranch,
		&i.Archived,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}

const upsertStackWriteIfNewer = `-- name: UpsertStackWriteIfNewer :one
INSERT INTO stacks (
    repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries,
    gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13, NULL
)
ON CONFLICT (repo_id, number) DO UPDATE
SET gh_id = EXCLUDED.gh_id,
    node_id = EXCLUDED.node_id,
    base_ref = EXCLUDED.base_ref,
    base_sha = EXCLUDED.base_sha,
    open = EXCLUDED.open,
    entries = EXCLUDED.entries,
    gh_updated_at = EXCLUDED.gh_updated_at,
    head_sha = EXCLUDED.head_sha,
    synced_at = EXCLUDED.synced_at,
    etag = EXCLUDED.etag,
    sync_source = EXCLUDED.sync_source,
    tombstoned_at = NULL
WHERE stacks.gh_updated_at IS NULL
   OR EXCLUDED.gh_updated_at > stacks.gh_updated_at
   OR (
       EXCLUDED.gh_updated_at = stacks.gh_updated_at
       AND EXCLUDED.head_sha = stacks.head_sha
       AND EXCLUDED.synced_at >= stacks.synced_at
       AND stacks.tombstoned_at IS NULL
   )
RETURNING id, repo_id, gh_id, node_id, number, base_ref, base_sha, open, entries, gh_updated_at, head_sha, synced_at, etag, sync_source, tombstoned_at
`

type UpsertStackWriteIfNewerParams struct {
	RepoID      int64
	GhID        pgtype.Int8
	NodeID      string
	StackNumber int32
	BaseRef     string
	BaseSha     string
	Open        bool
	Entries     []byte
	GhUpdatedAt pgtype.Timestamptz
	HeadSha     string
	SyncedAt    pgtype.Timestamptz
	Etag        string
	SyncSource  string
}

func (q *Queries) UpsertStackWriteIfNewer(ctx context.Context, arg UpsertStackWriteIfNewerParams) (Stack, error) {
	row := q.db.QueryRow(ctx, upsertStackWriteIfNewer,
		arg.RepoID,
		arg.GhID,
		arg.NodeID,
		arg.StackNumber,
		arg.BaseRef,
		arg.BaseSha,
		arg.Open,
		arg.Entries,
		arg.GhUpdatedAt,
		arg.HeadSha,
		arg.SyncedAt,
		arg.Etag,
		arg.SyncSource,
	)
	var i Stack
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.GhID,
		&i.NodeID,
		&i.Number,
		&i.BaseRef,
		&i.BaseSha,
		&i.Open,
		&i.Entries,
		&i.GhUpdatedAt,
		&i.HeadSha,
		&i.SyncedAt,
		&i.Etag,
		&i.SyncSource,
		&i.TombstonedAt,
	)
	return i, err
}
