// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: database.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDatabaseClock = `-- name: GetDatabaseClock :one
SELECT clock_timestamp()::timestamptz AS database_clock
`

func (q *Queries) GetDatabaseClock(ctx context.Context) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getDatabaseClock)
	var database_clock pgtype.Timestamptz
	err := row.Scan(&database_clock)
	return database_clock, err
}

const showSynchronousCommit = `-- name: ShowSynchronousCommit :one
SELECT current_setting('synchronous_commit')::text
`

func (q *Queries) ShowSynchronousCommit(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, showSynchronousCommit)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
