// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: drift.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDriftFindings = `-- name: CountDriftFindings :one
SELECT count(*)
FROM drift_findings
`

func (q *Queries) CountDriftFindings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDriftFindings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const escalateOpenDriftFinding = `-- name: EscalateOpenDriftFinding :one
UPDATE drift_findings
SET last_seen_at = $1,
    occurrence_count = occurrence_count + 1,
    cache_snapshot = $2,
    upstream_snapshot = $3,
    diff = $4,
    escalated_at = COALESCE(escalated_at, $5)
WHERE id = $6
  AND resolved_at IS NULL
RETURNING drift_findings.id, drift_findings.installation_id, drift_findings.entity_kind, drift_findings.entity_key, drift_findings.detected_at, drift_findings.cache_snapshot, drift_findings.upstream_snapshot, drift_findings.diff, drift_findings.refresh_enqueued_at, drift_findings.diff_hash, drift_findings.first_seen_at, drift_findings.last_seen_at, drift_findings.occurrence_count, drift_findings.heal_generation, drift_findings.escalated_at, drift_findings.resolved_at
`

type EscalateOpenDriftFindingParams struct {
	LastSeenAt       pgtype.Timestamptz
	CacheSnapshot    []byte
	UpstreamSnapshot []byte
	Diff             []byte
	EscalatedAt      pgtype.Timestamptz
	ID               int64
}

func (q *Queries) EscalateOpenDriftFinding(ctx context.Context, arg EscalateOpenDriftFindingParams) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, escalateOpenDriftFinding,
		arg.LastSeenAt,
		arg.CacheSnapshot,
		arg.UpstreamSnapshot,
		arg.Diff,
		arg.EscalatedAt,
		arg.ID,
	)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getCachedEntitySnapshot = `-- name: GetCachedEntitySnapshot :one
SELECT entity_kind, source_id, entity_key, lock_key, cache_snapshot,
       last_checked_at
FROM drift_entities
WHERE installation_id = $1
  AND entity_kind = $2
  AND entity_key = $3
`

type GetCachedEntitySnapshotParams struct {
	InstallationID int64
	EntityKind     string
	EntityKey      string
}

type GetCachedEntitySnapshotRow struct {
	EntityKind    string
	SourceID      int64
	EntityKey     string
	LockKey       string
	CacheSnapshot []byte
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) GetCachedEntitySnapshot(ctx context.Context, arg GetCachedEntitySnapshotParams) (GetCachedEntitySnapshotRow, error) {
	row := q.db.QueryRow(ctx, getCachedEntitySnapshot, arg.InstallationID, arg.EntityKind, arg.EntityKey)
	var i GetCachedEntitySnapshotRow
	err := row.Scan(
		&i.EntityKind,
		&i.SourceID,
		&i.EntityKey,
		&i.LockKey,
		&i.CacheSnapshot,
		&i.LastCheckedAt,
	)
	return i, err
}

const getDriftFinding = `-- name: GetDriftFinding :one
SELECT id, installation_id, entity_kind, entity_key, detected_at, cache_snapshot, upstream_snapshot, diff, refresh_enqueued_at, diff_hash, first_seen_at, last_seen_at, occurrence_count, heal_generation, escalated_at, resolved_at
FROM drift_findings
WHERE id = $1
`

func (q *Queries) GetDriftFinding(ctx context.Context, id int64) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, getDriftFinding, id)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getDriftSampleCursor = `-- name: GetDriftSampleCursor :one
SELECT source_id
FROM drift_sample_cursors
WHERE installation_id = $1
  AND entity_kind = $2
`

type GetDriftSampleCursorParams struct {
	InstallationID int64
	EntityKind     string
}

func (q *Queries) GetDriftSampleCursor(ctx context.Context, arg GetDriftSampleCursorParams) (int64, error) {
	row := q.db.QueryRow(ctx, getDriftSampleCursor, arg.InstallationID, arg.EntityKind)
	var source_id int64
	err := row.Scan(&source_id)
	return source_id, err
}

const getOpenDriftFindingByHash = `-- name: GetOpenDriftFindingByHash :one
SELECT id, installation_id, entity_kind, entity_key, detected_at, cache_snapshot, upstream_snapshot, diff, refresh_enqueued_at, diff_hash, first_seen_at, last_seen_at, occurrence_count, heal_generation, escalated_at, resolved_at
FROM drift_findings
WHERE installation_id = $1
  AND entity_kind = $2
  AND entity_key = $3
  AND diff_hash = $4
  AND resolved_at IS NULL
FOR UPDATE
`

type GetOpenDriftFindingByHashParams struct {
	InstallationID int64
	EntityKind     string
	EntityKey      string
	DiffHash       string
}

func (q *Queries) GetOpenDriftFindingByHash(ctx context.Context, arg GetOpenDriftFindingByHashParams) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, getOpenDriftFindingByHash,
		arg.InstallationID,
		arg.EntityKind,
		arg.EntityKey,
		arg.DiffHash,
	)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const hasOutstandingRefresh = `-- name: HasOutstandingRefresh :one
SELECT COALESCE((
    EXISTS (
        SELECT 1
        FROM refresh_intent_generations
        WHERE refresh_key = $1
          AND completed_generation < generation
    )
    OR EXISTS (
        SELECT 1
        FROM river_job
        WHERE args->>'key' = $1
          AND state IN (
              'available', 'pending', 'retryable', 'running', 'scheduled'
          )
    )
), false)::boolean
`

func (q *Queries) HasOutstandingRefresh(ctx context.Context, refreshKey string) (bool, error) {
	row := q.db.QueryRow(ctx, hasOutstandingRefresh, refreshKey)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const insertDriftFinding = `-- name: InsertDriftFinding :one
INSERT INTO drift_findings (
    installation_id, entity_kind, entity_key, detected_at, cache_snapshot,
    upstream_snapshot, diff, diff_hash, first_seen_at, last_seen_at,
    occurrence_count, refresh_enqueued_at
) VALUES (
    $1, $2,
    $3, $4,
    $5, $6,
    $7, $8, $4,
    $4, 1, $9
)
RETURNING id, installation_id, entity_kind, entity_key, detected_at, cache_snapshot, upstream_snapshot, diff, refresh_enqueued_at, diff_hash, first_seen_at, last_seen_at, occurrence_count, heal_generation, escalated_at, resolved_at
`

type InsertDriftFindingParams struct {
	InstallationID    int64
	EntityKind        string
	EntityKey         string
	DetectedAt        pgtype.Timestamptz
	CacheSnapshot     []byte
	UpstreamSnapshot  []byte
	Diff              []byte
	DiffHash          string
	RefreshEnqueuedAt pgtype.Timestamptz
}

func (q *Queries) InsertDriftFinding(ctx context.Context, arg InsertDriftFindingParams) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, insertDriftFinding,
		arg.InstallationID,
		arg.EntityKind,
		arg.EntityKey,
		arg.DetectedAt,
		arg.CacheSnapshot,
		arg.UpstreamSnapshot,
		arg.Diff,
		arg.DiffHash,
		arg.RefreshEnqueuedAt,
	)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const pruneResolvedDriftFindingBatch = `-- name: PruneResolvedDriftFindingBatch :execrows
DELETE FROM drift_findings AS finding
WHERE finding.id IN (
    SELECT candidate.id
    FROM drift_findings AS candidate
    WHERE candidate.resolved_at < $1
    ORDER BY candidate.resolved_at, candidate.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
`

type PruneResolvedDriftFindingBatchParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) PruneResolvedDriftFindingBatch(ctx context.Context, arg PruneResolvedDriftFindingBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneResolvedDriftFindingBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveOpenDriftFindings = `-- name: ResolveOpenDriftFindings :execrows
UPDATE drift_findings
SET resolved_at = $1,
    last_seen_at = $1
WHERE installation_id = $2
  AND entity_kind = $3
  AND entity_key = $4
  AND resolved_at IS NULL
`

type ResolveOpenDriftFindingsParams struct {
	ResolvedAt     pgtype.Timestamptz
	InstallationID int64
	EntityKind     string
	EntityKey      string
}

func (q *Queries) ResolveOpenDriftFindings(ctx context.Context, arg ResolveOpenDriftFindingsParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveOpenDriftFindings,
		arg.ResolvedAt,
		arg.InstallationID,
		arg.EntityKind,
		arg.EntityKey,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const sampleCachedEntitiesAfter = `-- name: SampleCachedEntitiesAfter :many
SELECT entity_kind, source_id, entity_key, lock_key, cache_snapshot,
       last_checked_at
FROM drift_entities
WHERE installation_id = $1
  AND entity_kind = $2
  AND source_id > $3
ORDER BY source_id
LIMIT $4
`

type SampleCachedEntitiesAfterParams struct {
	InstallationID int64
	EntityKind     string
	AfterSourceID  int64
	SampleSize     int32
}

type SampleCachedEntitiesAfterRow struct {
	EntityKind    string
	SourceID      int64
	EntityKey     string
	LockKey       string
	CacheSnapshot []byte
	LastCheckedAt pgtype.Timestamptz
}

// Q11: the forward half of the rotating sample is a plain indexed source_id
// range. Detect issues a second bounded range only when this reaches the end.
func (q *Queries) SampleCachedEntitiesAfter(ctx context.Context, arg SampleCachedEntitiesAfterParams) ([]SampleCachedEntitiesAfterRow, error) {
	rows, err := q.db.Query(ctx, sampleCachedEntitiesAfter,
		arg.InstallationID,
		arg.EntityKind,
		arg.AfterSourceID,
		arg.SampleSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SampleCachedEntitiesAfterRow
	for rows.Next() {
		var i SampleCachedEntitiesAfterRow
		if err := rows.Scan(
			&i.EntityKind,
			&i.SourceID,
			&i.EntityKey,
			&i.LockKey,
			&i.CacheSnapshot,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sampleCachedEntitiesThrough = `-- name: SampleCachedEntitiesThrough :many
SELECT entity_kind, source_id, entity_key, lock_key, cache_snapshot,
       last_checked_at
FROM drift_entities
WHERE installation_id = $1
  AND entity_kind = $2
  AND source_id <= $3
ORDER BY source_id
LIMIT $4
`

type SampleCachedEntitiesThroughParams struct {
	InstallationID  int64
	EntityKind      string
	ThroughSourceID int64
	SampleSize      int32
}

type SampleCachedEntitiesThroughRow struct {
	EntityKind    string
	SourceID      int64
	EntityKey     string
	LockKey       string
	CacheSnapshot []byte
	LastCheckedAt pgtype.Timestamptz
}

// The wrap half cannot overlap the forward half and retains source_id order.
func (q *Queries) SampleCachedEntitiesThrough(ctx context.Context, arg SampleCachedEntitiesThroughParams) ([]SampleCachedEntitiesThroughRow, error) {
	rows, err := q.db.Query(ctx, sampleCachedEntitiesThrough,
		arg.InstallationID,
		arg.EntityKind,
		arg.ThroughSourceID,
		arg.SampleSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SampleCachedEntitiesThroughRow
	for rows.Next() {
		var i SampleCachedEntitiesThroughRow
		if err := rows.Scan(
			&i.EntityKind,
			&i.SourceID,
			&i.EntityKey,
			&i.LockKey,
			&i.CacheSnapshot,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDriftFindingHealGeneration = `-- name: SetDriftFindingHealGeneration :one
UPDATE drift_findings
SET heal_generation = $1
WHERE id = $2
RETURNING id, installation_id, entity_kind, entity_key, detected_at, cache_snapshot, upstream_snapshot, diff, refresh_enqueued_at, diff_hash, first_seen_at, last_seen_at, occurrence_count, heal_generation, escalated_at, resolved_at
`

type SetDriftFindingHealGenerationParams struct {
	HealGeneration int64
	ID             int64
}

func (q *Queries) SetDriftFindingHealGeneration(ctx context.Context, arg SetDriftFindingHealGenerationParams) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, setDriftFindingHealGeneration, arg.HealGeneration, arg.ID)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const touchOpenDriftFinding = `-- name: TouchOpenDriftFinding :one
UPDATE drift_findings
SET last_seen_at = $1,
    cache_snapshot = $2,
    upstream_snapshot = $3,
    diff = $4
WHERE id = $5
  AND resolved_at IS NULL
RETURNING id, installation_id, entity_kind, entity_key, detected_at, cache_snapshot, upstream_snapshot, diff, refresh_enqueued_at, diff_hash, first_seen_at, last_seen_at, occurrence_count, heal_generation, escalated_at, resolved_at
`

type TouchOpenDriftFindingParams struct {
	LastSeenAt       pgtype.Timestamptz
	CacheSnapshot    []byte
	UpstreamSnapshot []byte
	Diff             []byte
	ID               int64
}

func (q *Queries) TouchOpenDriftFinding(ctx context.Context, arg TouchOpenDriftFindingParams) (DriftFinding, error) {
	row := q.db.QueryRow(ctx, touchOpenDriftFinding,
		arg.LastSeenAt,
		arg.CacheSnapshot,
		arg.UpstreamSnapshot,
		arg.Diff,
		arg.ID,
	)
	var i DriftFinding
	err := row.Scan(
		&i.ID,
		&i.InstallationID,
		&i.EntityKind,
		&i.EntityKey,
		&i.DetectedAt,
		&i.CacheSnapshot,
		&i.UpstreamSnapshot,
		&i.Diff,
		&i.RefreshEnqueuedAt,
		&i.DiffHash,
		&i.FirstSeenAt,
		&i.LastSeenAt,
		&i.OccurrenceCount,
		&i.HealGeneration,
		&i.EscalatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const upsertDriftSampleCursor = `-- name: UpsertDriftSampleCursor :exec
INSERT INTO drift_sample_cursors (
    installation_id, entity_kind, source_id
) VALUES (
    $1, $2, $3
)
ON CONFLICT (installation_id, entity_kind) DO UPDATE
SET source_id = EXCLUDED.source_id,
    updated_at = now()
`

type UpsertDriftSampleCursorParams struct {
	InstallationID int64
	EntityKind     string
	SourceID       int64
}

func (q *Queries) UpsertDriftSampleCursor(ctx context.Context, arg UpsertDriftSampleCursorParams) error {
	_, err := q.db.Exec(ctx, upsertDriftSampleCursor, arg.InstallationID, arg.EntityKind, arg.SourceID)
	return err
}
