// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installation_budgets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireInstallationBudgetLease = `-- name: AcquireInstallationBudgetLease :execrows
UPDATE installation_budgets
SET lease_owner = $1,
    lease_until = now() + $2::double precision * interval '1 second'
WHERE installation_id = $3
`

type AcquireInstallationBudgetLeaseParams struct {
	Owner          pgtype.Text
	TtlSeconds     float64
	InstallationID int64
}

func (q *Queries) AcquireInstallationBudgetLease(ctx context.Context, arg AcquireInstallationBudgetLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, acquireInstallationBudgetLease, arg.Owner, arg.TtlSeconds, arg.InstallationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureInstallationBudget = `-- name: EnsureInstallationBudget :exec
INSERT INTO installation_budgets (installation_id, class)
VALUES ($1, $2)
ON CONFLICT (installation_id, class) DO NOTHING
`

type EnsureInstallationBudgetParams struct {
	InstallationID int64
	Class          string
}

func (q *Queries) EnsureInstallationBudget(ctx context.Context, arg EnsureInstallationBudgetParams) error {
	_, err := q.db.Exec(ctx, ensureInstallationBudget, arg.InstallationID, arg.Class)
	return err
}

const lockInstallationBudgets = `-- name: LockInstallationBudgets :many
SELECT class, remaining, rate_limit, reset_at, lease_owner, lease_until,
       (
           lease_owner IS NOT NULL
           AND lease_owner <> $1
           AND lease_until > now()
       )::boolean AS held_by_other
FROM installation_budgets
WHERE installation_id = $2
ORDER BY class
FOR UPDATE
`

type LockInstallationBudgetsParams struct {
	Owner          pgtype.Text
	InstallationID int64
}

type LockInstallationBudgetsRow struct {
	Class       string
	Remaining   pgtype.Int8
	RateLimit   pgtype.Int8
	ResetAt     pgtype.Timestamptz
	LeaseOwner  pgtype.Text
	LeaseUntil  pgtype.Timestamptz
	HeldByOther bool
}

func (q *Queries) LockInstallationBudgets(ctx context.Context, arg LockInstallationBudgetsParams) ([]LockInstallationBudgetsRow, error) {
	rows, err := q.db.Query(ctx, lockInstallationBudgets, arg.Owner, arg.InstallationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockInstallationBudgetsRow
	for rows.Next() {
		var i LockInstallationBudgetsRow
		if err := rows.Scan(
			&i.Class,
			&i.Remaining,
			&i.RateLimit,
			&i.ResetAt,
			&i.LeaseOwner,
			&i.LeaseUntil,
			&i.HeldByOther,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseInstallationBudgetLease = `-- name: ReleaseInstallationBudgetLease :exec
UPDATE installation_budgets
SET lease_owner = NULL, lease_until = NULL
WHERE installation_id = $1 AND lease_owner = $2
`

type ReleaseInstallationBudgetLeaseParams struct {
	InstallationID int64
	LeaseOwner     pgtype.Text
}

func (q *Queries) ReleaseInstallationBudgetLease(ctx context.Context, arg ReleaseInstallationBudgetLeaseParams) error {
	_, err := q.db.Exec(ctx, releaseInstallationBudgetLease, arg.InstallationID, arg.LeaseOwner)
	return err
}

const renewInstallationBudgetLease = `-- name: RenewInstallationBudgetLease :execrows
UPDATE installation_budgets
SET lease_until = now() + $1::double precision * interval '1 second'
WHERE installation_id = $2
  AND lease_owner = $3
  AND lease_until > now()
`

type RenewInstallationBudgetLeaseParams struct {
	TtlSeconds     float64
	InstallationID int64
	Owner          pgtype.Text
}

func (q *Queries) RenewInstallationBudgetLease(ctx context.Context, arg RenewInstallationBudgetLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, renewInstallationBudgetLease, arg.TtlSeconds, arg.InstallationID, arg.Owner)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveInstallationBudgetSnapshot = `-- name: SaveInstallationBudgetSnapshot :execrows
UPDATE installation_budgets
SET remaining = CASE class
        WHEN 'rest' THEN $1::bigint
        WHEN 'graphql' THEN $2::bigint
    END,
    rate_limit = CASE class
        WHEN 'rest' THEN $3::bigint
        WHEN 'graphql' THEN $4::bigint
    END,
    reset_at = CASE class
        WHEN 'rest' THEN $5::timestamptz
        WHEN 'graphql' THEN $6::timestamptz
    END,
    updated_at = now()
WHERE installation_id = $7
  AND lease_owner = $8
  AND lease_until > now()
`

type SaveInstallationBudgetSnapshotParams struct {
	RestRemaining    pgtype.Int8
	GraphqlRemaining pgtype.Int8
	RestLimit        pgtype.Int8
	GraphqlLimit     pgtype.Int8
	RestResetAt      pgtype.Timestamptz
	GraphqlResetAt   pgtype.Timestamptz
	InstallationID   int64
	Owner            pgtype.Text
}

func (q *Queries) SaveInstallationBudgetSnapshot(ctx context.Context, arg SaveInstallationBudgetSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveInstallationBudgetSnapshot,
		arg.RestRemaining,
		arg.GraphqlRemaining,
		arg.RestLimit,
		arg.GraphqlLimit,
		arg.RestResetAt,
		arg.GraphqlResetAt,
		arg.InstallationID,
		arg.Owner,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
