// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: installation_budgets.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireInstallationBudgetLease = `-- name: AcquireInstallationBudgetLease :many
WITH locked AS MATERIALIZED (
    SELECT class
    FROM installation_budgets
    WHERE installation_id = $2
    ORDER BY class
    FOR UPDATE
),
proposed AS MATERIALIZED (
    SELECT clock_timestamp()
           + $3::double precision * interval '1 second'
           AS lease_until
    FROM (SELECT count(*) FROM locked) AS after_lock
)
UPDATE installation_budgets AS budgets
SET lease_owner = $1::text,
    lease_until = proposed.lease_until
FROM proposed
WHERE budgets.installation_id = $2
  AND (
      budgets.lease_owner IS NULL
      OR budgets.lease_until <= clock_timestamp()
      OR budgets.lease_owner = $1::text
  )
RETURNING budgets.class, budgets.remaining, budgets.rate_limit,
          budgets.reset_at, budgets.backoff_until, budgets.lease_until
`

type AcquireInstallationBudgetLeaseParams struct {
	LeaseToken     string
	InstallationID int64
	TtlSeconds     float64
}

type AcquireInstallationBudgetLeaseRow struct {
	Class        string
	Remaining    pgtype.Int8
	RateLimit    pgtype.Int8
	ResetAt      pgtype.Timestamptz
	BackoffUntil pgtype.Timestamptz
	LeaseUntil   pgtype.Timestamptz
}

func (q *Queries) AcquireInstallationBudgetLease(ctx context.Context, arg AcquireInstallationBudgetLeaseParams) ([]AcquireInstallationBudgetLeaseRow, error) {
	rows, err := q.db.Query(ctx, acquireInstallationBudgetLease, arg.LeaseToken, arg.InstallationID, arg.TtlSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AcquireInstallationBudgetLeaseRow
	for rows.Next() {
		var i AcquireInstallationBudgetLeaseRow
		if err := rows.Scan(
			&i.Class,
			&i.Remaining,
			&i.RateLimit,
			&i.ResetAt,
			&i.BackoffUntil,
			&i.LeaseUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const ensureInstallationBudget = `-- name: EnsureInstallationBudget :exec
INSERT INTO installation_budgets (installation_id, class)
VALUES ($1, $2)
ON CONFLICT (installation_id, class) DO NOTHING
`

type EnsureInstallationBudgetParams struct {
	InstallationID int64
	Class          string
}

func (q *Queries) EnsureInstallationBudget(ctx context.Context, arg EnsureInstallationBudgetParams) error {
	_, err := q.db.Exec(ctx, ensureInstallationBudget, arg.InstallationID, arg.Class)
	return err
}

const releaseInstallationBudgetLease = `-- name: ReleaseInstallationBudgetLease :execrows
UPDATE installation_budgets
SET lease_owner = NULL, lease_until = NULL
WHERE installation_id = $1
  AND lease_owner = $2::text
`

type ReleaseInstallationBudgetLeaseParams struct {
	InstallationID int64
	LeaseToken     string
}

func (q *Queries) ReleaseInstallationBudgetLease(ctx context.Context, arg ReleaseInstallationBudgetLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseInstallationBudgetLease, arg.InstallationID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renewInstallationBudgetLease = `-- name: RenewInstallationBudgetLease :many
WITH locked AS MATERIALIZED (
    SELECT class
    FROM installation_budgets
    WHERE installation_id = $1
    ORDER BY class
    FOR UPDATE
),
proposed AS MATERIALIZED (
    SELECT clock_timestamp()
           + $3::double precision * interval '1 second'
           AS lease_until
    FROM (SELECT count(*) FROM locked) AS after_lock
)
UPDATE installation_budgets AS budgets
SET lease_until = proposed.lease_until
FROM proposed
WHERE budgets.installation_id = $1
  AND budgets.lease_owner = $2::text
  AND budgets.lease_until > clock_timestamp()
RETURNING budgets.lease_until
`

type RenewInstallationBudgetLeaseParams struct {
	InstallationID int64
	LeaseToken     string
	TtlSeconds     float64
}

func (q *Queries) RenewInstallationBudgetLease(ctx context.Context, arg RenewInstallationBudgetLeaseParams) ([]pgtype.Timestamptz, error) {
	rows, err := q.db.Query(ctx, renewInstallationBudgetLease, arg.InstallationID, arg.LeaseToken, arg.TtlSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.Timestamptz
	for rows.Next() {
		var lease_until pgtype.Timestamptz
		if err := rows.Scan(&lease_until); err != nil {
			return nil, err
		}
		items = append(items, lease_until)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveInstallationBudgetBackoff = `-- name: SaveInstallationBudgetBackoff :execrows
WITH locked AS MATERIALIZED (
    SELECT class
    FROM installation_budgets
    WHERE installation_id = $2
    ORDER BY class
    FOR UPDATE
),
observed AS MATERIALIZED (
    SELECT clock_timestamp() AS checked_at
    FROM (SELECT count(*) FROM locked) AS after_lock
)
UPDATE installation_budgets AS budgets
SET backoff_until = CASE
        WHEN budgets.backoff_until IS NULL
          OR budgets.backoff_until < $1::timestamptz
        THEN $1::timestamptz
        ELSE budgets.backoff_until
    END,
    updated_at = observed.checked_at
FROM observed
WHERE budgets.installation_id = $2
  AND budgets.lease_owner = $3::text
  AND budgets.lease_until > observed.checked_at
`

type SaveInstallationBudgetBackoffParams struct {
	BackoffUntil   pgtype.Timestamptz
	InstallationID int64
	LeaseToken     string
}

func (q *Queries) SaveInstallationBudgetBackoff(ctx context.Context, arg SaveInstallationBudgetBackoffParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveInstallationBudgetBackoff, arg.BackoffUntil, arg.InstallationID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const saveInstallationBudgetSnapshot = `-- name: SaveInstallationBudgetSnapshot :execrows
WITH locked AS MATERIALIZED (
    SELECT class
    FROM installation_budgets
    WHERE installation_id = $8
    ORDER BY class
    FOR UPDATE
),
observed AS MATERIALIZED (
    SELECT clock_timestamp() AS checked_at
    FROM (SELECT count(*) FROM locked) AS after_lock
)
UPDATE installation_budgets AS budgets
SET remaining = CASE budgets.class
        WHEN 'rest' THEN $1::bigint
        WHEN 'graphql' THEN $2::bigint
    END,
    rate_limit = CASE budgets.class
        WHEN 'rest' THEN $3::bigint
        WHEN 'graphql' THEN $4::bigint
    END,
    reset_at = CASE budgets.class
        WHEN 'rest' THEN $5::timestamptz
        WHEN 'graphql' THEN $6::timestamptz
    END,
    backoff_until = CASE
        WHEN budgets.backoff_until IS NULL
          OR budgets.backoff_until <
             $7::timestamptz
        THEN $7::timestamptz
        ELSE budgets.backoff_until
    END,
    updated_at = observed.checked_at
FROM observed
WHERE budgets.installation_id = $8
  AND budgets.lease_owner = $9::text
  AND budgets.lease_until > observed.checked_at
`

type SaveInstallationBudgetSnapshotParams struct {
	RestRemaining    pgtype.Int8
	GraphqlRemaining pgtype.Int8
	RestLimit        pgtype.Int8
	GraphqlLimit     pgtype.Int8
	RestResetAt      pgtype.Timestamptz
	GraphqlResetAt   pgtype.Timestamptz
	BackoffUntil     pgtype.Timestamptz
	InstallationID   int64
	LeaseToken       string
}

func (q *Queries) SaveInstallationBudgetSnapshot(ctx context.Context, arg SaveInstallationBudgetSnapshotParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveInstallationBudgetSnapshot,
		arg.RestRemaining,
		arg.GraphqlRemaining,
		arg.RestLimit,
		arg.GraphqlLimit,
		arg.RestResetAt,
		arg.GraphqlResetAt,
		arg.BackoffUntil,
		arg.InstallationID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBudgetLeaseTransactionTimeouts = `-- name: SetBudgetLeaseTransactionTimeouts :exec
SELECT set_config('lock_timeout', $1, true),
       set_config('statement_timeout', $1, true)
`

func (q *Queries) SetBudgetLeaseTransactionTimeouts(ctx context.Context, timeout string) error {
	_, err := q.db.Exec(ctx, setBudgetLeaseTransactionTimeouts, timeout)
	return err
}
