// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: loadgen.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLoadgenRunDeliveries = `-- name: CountLoadgenRunDeliveries :one
SELECT
    count(*) FILTER (WHERE status = 'processed') AS completed,
    count(*) AS total
FROM webhook_deliveries
WHERE delivery_guid = ANY($1::text[])
`

type CountLoadgenRunDeliveriesRow struct {
	Completed int64
	Total     int64
}

func (q *Queries) CountLoadgenRunDeliveries(ctx context.Context, deliveryGuids []string) (CountLoadgenRunDeliveriesRow, error) {
	row := q.db.QueryRow(ctx, countLoadgenRunDeliveries, deliveryGuids)
	var i CountLoadgenRunDeliveriesRow
	err := row.Scan(&i.Completed, &i.Total)
	return i, err
}

const deleteLoadgenConsumerCursor = `-- name: DeleteLoadgenConsumerCursor :exec
DELETE FROM consumer_cursors
WHERE consumer = $1
  AND stream = $2
`

type DeleteLoadgenConsumerCursorParams struct {
	Consumer string
	Stream   string
}

func (q *Queries) DeleteLoadgenConsumerCursor(ctx context.Context, arg DeleteLoadgenConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, deleteLoadgenConsumerCursor, arg.Consumer, arg.Stream)
	return err
}

const getLoadgenCacheSeedState = `-- name: GetLoadgenCacheSeedState :one
WITH params AS (
    SELECT $1::bigint AS installation_id
)
SELECT
    EXISTS (
        SELECT 1
        FROM installation_backfill_cursors AS installation_cursor
        WHERE installation_cursor.installation_id = params.installation_id
          AND installation_cursor.phase = 'done'
          AND installation_cursor.completed_at IS NOT NULL
    ) AS installation_done,
    (
        SELECT count(*)
        FROM backfill_cursors AS repository_cursor
        WHERE repository_cursor.installation_id = params.installation_id
    ) AS repositories,
    (
        SELECT count(*)
        FROM backfill_cursors AS repository_cursor
        WHERE repository_cursor.installation_id = params.installation_id
          AND repository_cursor.phase <> 'done'
    ) AS incomplete_repos,
    (
        SELECT count(*)
        FROM backfill_children AS child
        WHERE child.installation_id = params.installation_id
          AND child.completed_at IS NULL
    ) AS pending_children,
    (
        SELECT count(*)
        FROM river_job AS job
        WHERE job.kind IN (
            'backfill_installation_page',
            'backfill_repo_page'
        )
          AND job.state IN (
              'available', 'pending', 'retryable', 'running', 'scheduled'
          )
    ) AS backfill_jobs
FROM params
`

type GetLoadgenCacheSeedStateRow struct {
	InstallationDone bool
	Repositories     int64
	IncompleteRepos  int64
	PendingChildren  int64
	BackfillJobs     int64
}

func (q *Queries) GetLoadgenCacheSeedState(ctx context.Context, installationID int64) (GetLoadgenCacheSeedStateRow, error) {
	row := q.db.QueryRow(ctx, getLoadgenCacheSeedState, installationID)
	var i GetLoadgenCacheSeedStateRow
	err := row.Scan(
		&i.InstallationDone,
		&i.Repositories,
		&i.IncompleteRepos,
		&i.PendingChildren,
		&i.BackfillJobs,
	)
	return i, err
}

const listLoadgenCachedCheckRuns = `-- name: ListLoadgenCachedCheckRuns :many
SELECT
    run.gh_id,
    run.node_id,
    run.head_sha,
    run.name,
    run.status,
    run.conclusion,
    run.details_url,
    run.app_slug,
    run.started_at,
    run.completed_at,
    run.gh_updated_at,
    run.semantic_version
FROM check_runs AS run
JOIN repos AS repo ON repo.id = run.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND run.tombstoned_at IS NULL
ORDER BY run.gh_id
`

type ListLoadgenCachedCheckRunsRow struct {
	GhID            int64
	NodeID          string
	HeadSha         string
	Name            string
	Status          string
	Conclusion      string
	DetailsUrl      string
	AppSlug         string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	GhUpdatedAt     pgtype.Timestamptz
	SemanticVersion string
}

func (q *Queries) ListLoadgenCachedCheckRuns(ctx context.Context, repoFullName string) ([]ListLoadgenCachedCheckRunsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedCheckRuns, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedCheckRunsRow
	for rows.Next() {
		var i ListLoadgenCachedCheckRunsRow
		if err := rows.Scan(
			&i.GhID,
			&i.NodeID,
			&i.HeadSha,
			&i.Name,
			&i.Status,
			&i.Conclusion,
			&i.DetailsUrl,
			&i.AppSlug,
			&i.StartedAt,
			&i.CompletedAt,
			&i.GhUpdatedAt,
			&i.SemanticVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedPullRequestComments = `-- name: ListLoadgenCachedPullRequestComments :many
SELECT comment.pr_number, comment.gh_id, comment.node_id,
       comment.author_kind, comment.author_node_id, comment.author_login,
       comment.created_at, comment.gh_updated_at, comment.head_sha
FROM pull_request_comments AS comment
JOIN repos AS repo ON repo.id = comment.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND comment.tombstoned_at IS NULL
ORDER BY comment.pr_number, comment.node_id
`

type ListLoadgenCachedPullRequestCommentsRow struct {
	PrNumber     int32
	GhID         pgtype.Int8
	NodeID       string
	AuthorKind   string
	AuthorNodeID pgtype.Text
	AuthorLogin  pgtype.Text
	CreatedAt    pgtype.Timestamptz
	GhUpdatedAt  pgtype.Timestamptz
	HeadSha      string
}

func (q *Queries) ListLoadgenCachedPullRequestComments(ctx context.Context, repoFullName string) ([]ListLoadgenCachedPullRequestCommentsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedPullRequestComments, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedPullRequestCommentsRow
	for rows.Next() {
		var i ListLoadgenCachedPullRequestCommentsRow
		if err := rows.Scan(
			&i.PrNumber,
			&i.GhID,
			&i.NodeID,
			&i.AuthorKind,
			&i.AuthorNodeID,
			&i.AuthorLogin,
			&i.CreatedAt,
			&i.GhUpdatedAt,
			&i.HeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedPullRequestReviewRequests = `-- name: ListLoadgenCachedPullRequestReviewRequests :many
SELECT
    request.pr_number,
    request.reviewer_kind,
    request.reviewer_gh_id,
    request.reviewer_node_id,
    request.reviewer_login,
    request.requested_at,
    request.head_sha
FROM pull_request_review_requests AS request
JOIN repos AS repo ON repo.id = request.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND request.tombstoned_at IS NULL
ORDER BY request.pr_number, request.reviewer_kind, request.reviewer_gh_id
`

type ListLoadgenCachedPullRequestReviewRequestsRow struct {
	PrNumber       int32
	ReviewerKind   string
	ReviewerGhID   int64
	ReviewerNodeID string
	ReviewerLogin  string
	RequestedAt    pgtype.Timestamptz
	HeadSha        string
}

func (q *Queries) ListLoadgenCachedPullRequestReviewRequests(ctx context.Context, repoFullName string) ([]ListLoadgenCachedPullRequestReviewRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedPullRequestReviewRequests, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedPullRequestReviewRequestsRow
	for rows.Next() {
		var i ListLoadgenCachedPullRequestReviewRequestsRow
		if err := rows.Scan(
			&i.PrNumber,
			&i.ReviewerKind,
			&i.ReviewerGhID,
			&i.ReviewerNodeID,
			&i.ReviewerLogin,
			&i.RequestedAt,
			&i.HeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedPullRequestReviews = `-- name: ListLoadgenCachedPullRequestReviews :many
SELECT review.pr_number, review.gh_id, review.node_id,
       review.author_kind, review.author_node_id, review.author_login,
       review.state, review.submitted_at, review.commit_oid,
       review.gh_updated_at, review.head_sha
FROM pull_request_reviews AS review
JOIN repos AS repo ON repo.id = review.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND review.tombstoned_at IS NULL
ORDER BY review.pr_number, review.node_id
`

type ListLoadgenCachedPullRequestReviewsRow struct {
	PrNumber     int32
	GhID         pgtype.Int8
	NodeID       string
	AuthorKind   string
	AuthorNodeID pgtype.Text
	AuthorLogin  pgtype.Text
	State        string
	SubmittedAt  pgtype.Timestamptz
	CommitOid    pgtype.Text
	GhUpdatedAt  pgtype.Timestamptz
	HeadSha      string
}

func (q *Queries) ListLoadgenCachedPullRequestReviews(ctx context.Context, repoFullName string) ([]ListLoadgenCachedPullRequestReviewsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedPullRequestReviews, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedPullRequestReviewsRow
	for rows.Next() {
		var i ListLoadgenCachedPullRequestReviewsRow
		if err := rows.Scan(
			&i.PrNumber,
			&i.GhID,
			&i.NodeID,
			&i.AuthorKind,
			&i.AuthorNodeID,
			&i.AuthorLogin,
			&i.State,
			&i.SubmittedAt,
			&i.CommitOid,
			&i.GhUpdatedAt,
			&i.HeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedPullRequests = `-- name: ListLoadgenCachedPullRequests :many
SELECT
    pull.gh_id,
    pull.node_id,
    pull.number,
    pull.title,
    pull.state,
    pull.draft,
    pull.author_login,
    pull.review_decision,
    pull.mergeable_state,
    pull.head_ref,
    pull.head_sha,
    pull.base_ref,
    pull.base_sha,
    pull.stack_number,
    pull.stack_position,
    pull.gh_updated_at
FROM pull_requests AS pull
JOIN repos AS repo ON repo.id = pull.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND pull.tombstoned_at IS NULL
ORDER BY pull.number
`

type ListLoadgenCachedPullRequestsRow struct {
	GhID           pgtype.Int8
	NodeID         string
	Number         int32
	Title          string
	State          string
	Draft          bool
	AuthorLogin    string
	ReviewDecision string
	MergeableState string
	HeadRef        string
	HeadSha        string
	BaseRef        string
	BaseSha        string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	GhUpdatedAt    pgtype.Timestamptz
}

func (q *Queries) ListLoadgenCachedPullRequests(ctx context.Context, repoFullName string) ([]ListLoadgenCachedPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedPullRequests, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedPullRequestsRow
	for rows.Next() {
		var i ListLoadgenCachedPullRequestsRow
		if err := rows.Scan(
			&i.GhID,
			&i.NodeID,
			&i.Number,
			&i.Title,
			&i.State,
			&i.Draft,
			&i.AuthorLogin,
			&i.ReviewDecision,
			&i.MergeableState,
			&i.HeadRef,
			&i.HeadSha,
			&i.BaseRef,
			&i.BaseSha,
			&i.StackNumber,
			&i.StackPosition,
			&i.GhUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedReviewThreads = `-- name: ListLoadgenCachedReviewThreads :many
SELECT
    thread.id,
    thread.pr_number,
    thread.is_resolved,
    thread.is_outdated,
    thread.path,
    thread.line,
    thread.comments,
    thread.gh_updated_at,
    thread.head_sha
FROM review_threads AS thread
JOIN repos AS repo ON repo.id = thread.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND thread.tombstoned_at IS NULL
ORDER BY thread.id
`

type ListLoadgenCachedReviewThreadsRow struct {
	ID          string
	PrNumber    int32
	IsResolved  bool
	IsOutdated  bool
	Path        string
	Line        pgtype.Int4
	Comments    []byte
	GhUpdatedAt pgtype.Timestamptz
	HeadSha     string
}

func (q *Queries) ListLoadgenCachedReviewThreads(ctx context.Context, repoFullName string) ([]ListLoadgenCachedReviewThreadsRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedReviewThreads, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedReviewThreadsRow
	for rows.Next() {
		var i ListLoadgenCachedReviewThreadsRow
		if err := rows.Scan(
			&i.ID,
			&i.PrNumber,
			&i.IsResolved,
			&i.IsOutdated,
			&i.Path,
			&i.Line,
			&i.Comments,
			&i.GhUpdatedAt,
			&i.HeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenCachedStacks = `-- name: ListLoadgenCachedStacks :many
SELECT
    stack.gh_id,
    stack.node_id,
    stack.number,
    stack.base_ref,
    stack.base_sha,
    stack.open,
    stack.entries,
    stack.gh_updated_at,
    stack.head_sha
FROM stacks AS stack
JOIN repos AS repo ON repo.id = stack.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND stack.tombstoned_at IS NULL
ORDER BY stack.number
`

type ListLoadgenCachedStacksRow struct {
	GhID        pgtype.Int8
	NodeID      string
	Number      int32
	BaseRef     string
	BaseSha     string
	Open        bool
	Entries     []byte
	GhUpdatedAt pgtype.Timestamptz
	HeadSha     string
}

func (q *Queries) ListLoadgenCachedStacks(ctx context.Context, repoFullName string) ([]ListLoadgenCachedStacksRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenCachedStacks, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenCachedStacksRow
	for rows.Next() {
		var i ListLoadgenCachedStacksRow
		if err := rows.Scan(
			&i.GhID,
			&i.NodeID,
			&i.Number,
			&i.BaseRef,
			&i.BaseSha,
			&i.Open,
			&i.Entries,
			&i.GhUpdatedAt,
			&i.HeadSha,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoadgenDroppedDeliveries = `-- name: ListLoadgenDroppedDeliveries :many
SELECT delivery_guid, received_at, status
FROM webhook_deliveries
WHERE delivery_guid = ANY($1::text[])
`

type ListLoadgenDroppedDeliveriesRow struct {
	DeliveryGuid string
	ReceivedAt   pgtype.Timestamptz
	Status       string
}

func (q *Queries) ListLoadgenDroppedDeliveries(ctx context.Context, deliveryGuids []string) ([]ListLoadgenDroppedDeliveriesRow, error) {
	rows, err := q.db.Query(ctx, listLoadgenDroppedDeliveries, deliveryGuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLoadgenDroppedDeliveriesRow
	for rows.Next() {
		var i ListLoadgenDroppedDeliveriesRow
		if err := rows.Scan(&i.DeliveryGuid, &i.ReceivedAt, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
