// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: metrics.sql

package dbgen

import (
	"context"
)

const collectBudgetMetrics = `-- name: CollectBudgetMetrics :many
SELECT class,
       COALESCE(remaining, -1)::bigint AS remaining,
       COALESCE(rate_limit, -1)::bigint AS rate_limit,
       COALESCE(backoff_until > clock_timestamp(), false)::boolean
           AS gate_closed
FROM installation_budgets
WHERE installation_id = $1
ORDER BY class
`

type CollectBudgetMetricsRow struct {
	Class      string
	Remaining  int64
	RateLimit  int64
	GateClosed bool
}

func (q *Queries) CollectBudgetMetrics(ctx context.Context, installationID int64) ([]CollectBudgetMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectBudgetMetrics, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectBudgetMetricsRow
	for rows.Next() {
		var i CollectBudgetMetricsRow
		if err := rows.Scan(
			&i.Class,
			&i.Remaining,
			&i.RateLimit,
			&i.GateClosed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectCacheStalenessMetrics = `-- name: CollectCacheStalenessMetrics :many
WITH ages(entity_class, age_seconds) AS (
    SELECT 'repository',
           max(EXTRACT(EPOCH FROM (
               clock_timestamp() - repos.last_checked_at
           )))
    FROM repos
    WHERE repos.installation_id = $1
      AND repos.tombstoned_at IS NULL
    UNION ALL
    SELECT 'open_stack',
           max(EXTRACT(EPOCH FROM (
               clock_timestamp() - stacks.last_checked_at
           )))
    FROM stacks
    JOIN repos ON repos.id = stacks.repo_id
    WHERE repos.installation_id = $1
      AND repos.tombstoned_at IS NULL
      AND stacks.tombstoned_at IS NULL
      AND stacks.open
    UNION ALL
    SELECT 'open_pr',
           max(EXTRACT(EPOCH FROM (
               clock_timestamp() - pull_requests.last_checked_at
           )))
    FROM pull_requests
    JOIN repos ON repos.id = pull_requests.repo_id
    WHERE repos.installation_id = $1
      AND repos.tombstoned_at IS NULL
      AND pull_requests.tombstoned_at IS NULL
      AND pull_requests.state = 'open'
    UNION ALL
    SELECT 'repo_rules',
           max(EXTRACT(EPOCH FROM (
               clock_timestamp() - state.last_checked_at
           )))
    FROM repo_rule_sync_state AS state
    JOIN repos ON repos.id = state.repo_id
    WHERE repos.installation_id = $1
      AND repos.tombstoned_at IS NULL
    UNION ALL
    SELECT 'closed_displayed',
           max(age_seconds)
    FROM (
        SELECT EXTRACT(EPOCH FROM (
                   clock_timestamp() - stacks.last_checked_at
               )) AS age_seconds
        FROM stacks
        JOIN repos ON repos.id = stacks.repo_id
        WHERE repos.installation_id = $1
          AND repos.tombstoned_at IS NULL
          AND stacks.tombstoned_at IS NULL
          AND NOT stacks.open
          AND stacks.display_until > clock_timestamp()
        UNION ALL
        SELECT EXTRACT(EPOCH FROM (
                   clock_timestamp() - pull_requests.last_checked_at
               ))
        FROM pull_requests
        JOIN repos ON repos.id = pull_requests.repo_id
        WHERE repos.installation_id = $1
          AND repos.tombstoned_at IS NULL
          AND pull_requests.tombstoned_at IS NULL
          AND pull_requests.state <> 'open'
          AND pull_requests.display_until > clock_timestamp()
    ) AS closed
)
SELECT entity_class, COALESCE(age_seconds, 0)::double precision AS age_seconds
FROM ages
ORDER BY entity_class
`

type CollectCacheStalenessMetricsRow struct {
	EntityClass string
	AgeSeconds  float64
}

func (q *Queries) CollectCacheStalenessMetrics(ctx context.Context, installationID int64) ([]CollectCacheStalenessMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectCacheStalenessMetrics, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectCacheStalenessMetricsRow
	for rows.Next() {
		var i CollectCacheStalenessMetricsRow
		if err := rows.Scan(&i.EntityClass, &i.AgeSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectConsumerStreamMetrics = `-- name: CollectConsumerStreamMetrics :many
SELECT cursor.consumer,
       cursor.stream,
       count(events.seq) AS outstanding_count,
       COALESCE(EXTRACT(EPOCH FROM (
           clock_timestamp() - min(events.occurred_at)
       )), 0)::double precision AS oldest_outstanding_age,
       cursor.resync_count
FROM consumer_cursors AS cursor
CROSS JOIN stream_watermark AS watermark
LEFT JOIN change_events AS events
  ON events.stream = cursor.stream
 AND events.seq > cursor.seq
 AND events.seq <= watermark.safe_seq
GROUP BY cursor.consumer, cursor.stream, cursor.resync_count
ORDER BY cursor.consumer, cursor.stream
`

type CollectConsumerStreamMetricsRow struct {
	Consumer             string
	Stream               string
	OutstandingCount     int64
	OldestOutstandingAge float64
	ResyncCount          int64
}

func (q *Queries) CollectConsumerStreamMetrics(ctx context.Context) ([]CollectConsumerStreamMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectConsumerStreamMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectConsumerStreamMetricsRow
	for rows.Next() {
		var i CollectConsumerStreamMetricsRow
		if err := rows.Scan(
			&i.Consumer,
			&i.Stream,
			&i.OutstandingCount,
			&i.OldestOutstandingAge,
			&i.ResyncCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectDeliveryMetrics = `-- name: CollectDeliveryMetrics :one
SELECT
    COALESCE(EXTRACT(EPOCH FROM (clock_timestamp() - LEAST(
        (
            SELECT min(received_at)
            FROM webhook_deliveries
            WHERE status = 'pending'
        ),
        (
            SELECT min(received_at)
            FROM webhook_deliveries
            WHERE status = 'processing'
        )
    ))), 0)::double precision AS oldest_unprocessed,
    (
        SELECT count(*)
        FROM webhook_deliveries
        WHERE status = 'parked'
    )::bigint AS parked,
    COALESCE(EXTRACT(EPOCH FROM (clock_timestamp() - (
        SELECT min(received_at)
        FROM webhook_deliveries
        WHERE status = 'parked'
    ))), 0)::double precision AS oldest_parked,
    (
        SELECT count(*)
        FROM refresh_intent_generations
        WHERE completed_generation < generation
    ) AS outstanding_generations,
    (
        SELECT count(*)
        FROM refresh_intent_generations
        WHERE completed_generation < generation
          AND event_received_at IS NOT NULL
    ) AS outstanding_event_generations,
    (
        SELECT COALESCE(EXTRACT(EPOCH FROM (
            clock_timestamp() - min(event_received_at)
        )), 0)::double precision
        FROM refresh_intent_generations
        WHERE completed_generation < generation
          AND event_received_at IS NOT NULL
    ) AS oldest_generation
`

type CollectDeliveryMetricsRow struct {
	OldestUnprocessed           float64
	Parked                      int64
	OldestParked                float64
	OutstandingGenerations      int64
	OutstandingEventGenerations int64
	OldestGeneration            float64
}

// Every aggregate here is per-status so that it rides
// webhook_deliveries_unfinished_received_idx (status, received_at) WHERE
// status IN ('pending','processing','parked'). Aggregate FILTER clauses
// block both the min/max index optimisation and the partial index's
// predicate proof, so the older single-pass form seq-scanned the whole
// delivery table on every metrics scrape. LEAST() ignores NULLs, so
// LEAST(min pending, min processing) is exactly the old
// min(received_at) FILTER (WHERE status IN ('pending','processing')).
func (q *Queries) CollectDeliveryMetrics(ctx context.Context) (CollectDeliveryMetricsRow, error) {
	row := q.db.QueryRow(ctx, collectDeliveryMetrics)
	var i CollectDeliveryMetricsRow
	err := row.Scan(
		&i.OldestUnprocessed,
		&i.Parked,
		&i.OldestParked,
		&i.OutstandingGenerations,
		&i.OutstandingEventGenerations,
		&i.OldestGeneration,
	)
	return i, err
}

const collectDriftMetrics = `-- name: CollectDriftMetrics :many
SELECT CASE WHEN resolved_at IS NULL THEN 'open' ELSE 'resolved' END
           AS finding_state,
       entity_kind,
       count(*) AS finding_count
FROM drift_findings
WHERE installation_id = $1
GROUP BY 1, entity_kind
`

type CollectDriftMetricsRow struct {
	FindingState string
	EntityKind   string
	FindingCount int64
}

func (q *Queries) CollectDriftMetrics(ctx context.Context, installationID int64) ([]CollectDriftMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectDriftMetrics, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectDriftMetricsRow
	for rows.Next() {
		var i CollectDriftMetricsRow
		if err := rows.Scan(&i.FindingState, &i.EntityKind, &i.FindingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectOperationHeartbeatMetrics = `-- name: CollectOperationHeartbeatMetrics :many
WITH expected AS (
    SELECT 'drift'::text AS component, 'detector'::text AS operation
    UNION ALL SELECT 'sweep', 'repositories'
    UNION ALL SELECT 'sweep', 'stacks'
    UNION ALL SELECT 'sweep', 'pull_requests'
    UNION ALL SELECT 'sweep', 'repo_rules'
    UNION ALL SELECT 'sweep', 'closed_tracked'
    UNION ALL SELECT 'watermarker', 'entities'
    UNION ALL SELECT 'deriver', 'dirty_sets'
    UNION ALL SELECT 'fetch', 'branch_reconciliation'
)
SELECT expected.component,
       expected.operation,
       COALESCE(heartbeat.success_count, 0)::bigint AS success_count,
       COALESCE(heartbeat.sample_count, 0)::bigint AS sample_count,
       CASE
           WHEN heartbeat.last_success_at IS NULL THEN -1
           ELSE EXTRACT(EPOCH FROM (
               clock_timestamp() - heartbeat.last_success_at
           ))::double precision
       END AS success_age_seconds,
       CASE
           WHEN heartbeat.last_sample_at IS NULL THEN -1
           ELSE EXTRACT(EPOCH FROM (
               clock_timestamp() - heartbeat.last_sample_at
           ))::double precision
       END AS sample_age_seconds
FROM expected
LEFT JOIN operation_heartbeats AS heartbeat
  ON heartbeat.installation_id = $1
 AND heartbeat.component = expected.component
 AND heartbeat.operation = expected.operation
ORDER BY 1, 2
`

type CollectOperationHeartbeatMetricsRow struct {
	Component         string
	Operation         string
	SuccessCount      int64
	SampleCount       int64
	SuccessAgeSeconds float64
	SampleAgeSeconds  float64
}

func (q *Queries) CollectOperationHeartbeatMetrics(ctx context.Context, installationID int64) ([]CollectOperationHeartbeatMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectOperationHeartbeatMetrics, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectOperationHeartbeatMetricsRow
	for rows.Next() {
		var i CollectOperationHeartbeatMetricsRow
		if err := rows.Scan(
			&i.Component,
			&i.Operation,
			&i.SuccessCount,
			&i.SampleCount,
			&i.SuccessAgeSeconds,
			&i.SampleAgeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectPrunableOutboxMetrics = `-- name: CollectPrunableOutboxMetrics :many
SELECT events.stream, count(*) AS prunable_count
FROM change_events AS events
CROSS JOIN stream_watermark AS watermark
WHERE events.occurred_at <
      clock_timestamp() - $1::text::interval
  AND events.seq <= watermark.safe_seq
GROUP BY events.stream
`

type CollectPrunableOutboxMetricsRow struct {
	Stream        string
	PrunableCount int64
}

func (q *Queries) CollectPrunableOutboxMetrics(ctx context.Context, retentionAge string) ([]CollectPrunableOutboxMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectPrunableOutboxMetrics, retentionAge)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectPrunableOutboxMetricsRow
	for rows.Next() {
		var i CollectPrunableOutboxMetricsRow
		if err := rows.Scan(&i.Stream, &i.PrunableCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectRiverQueueDepthMetrics = `-- name: CollectRiverQueueDepthMetrics :many
SELECT queue, count(*) AS depth
FROM river_job
WHERE state IN (
    'available', 'pending', 'retryable', 'running', 'scheduled'
)
GROUP BY queue
`

type CollectRiverQueueDepthMetricsRow struct {
	Queue string
	Depth int64
}

func (q *Queries) CollectRiverQueueDepthMetrics(ctx context.Context) ([]CollectRiverQueueDepthMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectRiverQueueDepthMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectRiverQueueDepthMetricsRow
	for rows.Next() {
		var i CollectRiverQueueDepthMetricsRow
		if err := rows.Scan(&i.Queue, &i.Depth); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectStreamWatermarkMetrics = `-- name: CollectStreamWatermarkMetrics :one
SELECT watermark.safe_seq,
       COALESCE(max(events.seq), 0)::bigint AS max_seq,
       EXTRACT(EPOCH FROM (
           clock_timestamp() - watermark.updated_at
       ))::double precision AS age_seconds
FROM stream_watermark AS watermark
LEFT JOIN change_events AS events ON true
WHERE watermark.singleton
GROUP BY watermark.safe_seq, watermark.updated_at
`

type CollectStreamWatermarkMetricsRow struct {
	SafeSeq    int64
	MaxSeq     int64
	AgeSeconds float64
}

func (q *Queries) CollectStreamWatermarkMetrics(ctx context.Context) (CollectStreamWatermarkMetricsRow, error) {
	row := q.db.QueryRow(ctx, collectStreamWatermarkMetrics)
	var i CollectStreamWatermarkMetricsRow
	err := row.Scan(&i.SafeSeq, &i.MaxSeq, &i.AgeSeconds)
	return i, err
}

const collectSweepMetrics = `-- name: CollectSweepMetrics :many
SELECT sweep_kind,
       max(GREATEST(EXTRACT(EPOCH FROM (
           COALESCE(completed_at, clock_timestamp()) - started_at
       )), 0))::double precision AS duration_seconds
FROM sweep_cursors
WHERE installation_id = $1
  AND started_at IS NOT NULL
GROUP BY sweep_kind
`

type CollectSweepMetricsRow struct {
	SweepKind       string
	DurationSeconds float64
}

func (q *Queries) CollectSweepMetrics(ctx context.Context, installationID int64) ([]CollectSweepMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectSweepMetrics, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectSweepMetricsRow
	for rows.Next() {
		var i CollectSweepMetricsRow
		if err := rows.Scan(&i.SweepKind, &i.DurationSeconds); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const collectTombstoneMetrics = `-- name: CollectTombstoneMetrics :many
SELECT entity_kind, count(*) AS tombstone_count
FROM (
    SELECT 'repository' AS entity_kind FROM repos
    WHERE tombstoned_at IS NOT NULL
    UNION ALL
    SELECT 'repo_rules' FROM repo_rules
    WHERE tombstoned_at IS NOT NULL
    UNION ALL
    SELECT 'stack' FROM stacks
    WHERE tombstoned_at IS NOT NULL
    UNION ALL
    SELECT 'pull_request' FROM pull_requests
    WHERE tombstoned_at IS NOT NULL
    UNION ALL
    SELECT 'review_thread' FROM review_threads
    WHERE tombstoned_at IS NOT NULL
    UNION ALL
    SELECT 'check_run' FROM check_runs
    WHERE tombstoned_at IS NOT NULL
) AS tombstones
GROUP BY entity_kind
`

type CollectTombstoneMetricsRow struct {
	EntityKind     string
	TombstoneCount int64
}

func (q *Queries) CollectTombstoneMetrics(ctx context.Context) ([]CollectTombstoneMetricsRow, error) {
	rows, err := q.db.Query(ctx, collectTombstoneMetrics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CollectTombstoneMetricsRow
	for rows.Next() {
		var i CollectTombstoneMetricsRow
		if err := rows.Scan(&i.EntityKind, &i.TombstoneCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDerivationDirty = `-- name: CountDerivationDirty :one
SELECT count(*)
FROM derivation_dirty
`

func (q *Queries) CountDerivationDirty(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDerivationDirty)
	var count int64
	err := row.Scan(&count)
	return count, err
}
