// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type BackfillChild struct {
	InstallationID   int64
	RepoFullName     string
	Kind             string
	RefreshKey       string
	TargetGeneration int64
	CreatedAt        pgtype.Timestamptz
	CompletedAt      pgtype.Timestamptz
}

type BackfillCursor struct {
	InstallationID int64
	RepoFullName   string
	Phase          string
	Page           int32
	CompletedAt    pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	QueueName      string
}

type ChangeEvent struct {
	Seq        int64
	Stream     string
	Kind       string
	EntityKey  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
	OutboxTxid pgtype.Uint64
}

type CheckHistory struct {
	ID              int64
	CheckRunGhID    int64
	RepoID          int64
	Name            string
	Status          string
	Conclusion      string
	Observed        []byte
	GhUpdatedAt     pgtype.Timestamptz
	HeadSha         string
	SyncedAt        pgtype.Timestamptz
	Etag            string
	SyncSource      string
	TombstonedAt    pgtype.Timestamptz
	SemanticVersion string
}

type CheckRun struct {
	GhID            int64
	RepoID          int64
	NodeID          string
	Name            string
	Status          string
	Conclusion      string
	DetailsUrl      string
	AppSlug         string
	StartedAt       pgtype.Timestamptz
	CompletedAt     pgtype.Timestamptz
	GhUpdatedAt     pgtype.Timestamptz
	HeadSha         string
	SyncedAt        pgtype.Timestamptz
	Etag            string
	SyncSource      string
	TombstonedAt    pgtype.Timestamptz
	SemanticVersion string
	LastCheckedAt   pgtype.Timestamptz
}

type ConsumerCursor struct {
	Consumer     string
	Stream       string
	Seq          int64
	UpdatedAt    pgtype.Timestamptz
	ResyncCount  int64
	LastResyncAt pgtype.Timestamptz
}

type DerivationDirty struct {
	ScopeKey string
	MarkedAt pgtype.Timestamptz
}

type DriftEntity struct {
	InstallationID int64
	EntityKind     string
	SourceID       int64
	EntityKey      string
	LockKey        string
	CacheSnapshot  []byte
}

type DriftFinding struct {
	ID                int64
	InstallationID    int64
	EntityKind        string
	EntityKey         string
	DetectedAt        pgtype.Timestamptz
	CacheSnapshot     []byte
	UpstreamSnapshot  []byte
	Diff              []byte
	RefreshEnqueuedAt pgtype.Timestamptz
	DiffHash          string
	FirstSeenAt       pgtype.Timestamptz
	LastSeenAt        pgtype.Timestamptz
	OccurrenceCount   int64
	HealGeneration    int64
	EscalatedAt       pgtype.Timestamptz
	ResolvedAt        pgtype.Timestamptz
}

type DriftSampleCursor struct {
	InstallationID int64
	EntityKind     string
	SourceID       int64
	UpdatedAt      pgtype.Timestamptz
}

type GapHealCursor struct {
	InstallationID int64
	Cursor         string
	Cutoff         pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
}

type InstallationBackfillCursor struct {
	InstallationID int64
	Phase          string
	Page           int32
	QueueName      string
	CompletedAt    pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type InstallationBudget struct {
	InstallationID int64
	Class          string
	Remaining      pgtype.Int8
	RateLimit      pgtype.Int8
	ResetAt        pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	BackoffUntil   pgtype.Timestamptz
}

type OperationHeartbeat struct {
	InstallationID int64
	Component      string
	Operation      string
	SuccessCount   int64
	LastSuccessAt  pgtype.Timestamptz
	SampleCount    int64
	LastSampleAt   pgtype.Timestamptz
}

type PullRequest struct {
	ID             int64
	RepoID         int64
	GhID           pgtype.Int8
	NodeID         string
	Number         int32
	Title          string
	State          string
	Draft          bool
	AuthorLogin    string
	HeadRef        string
	HeadSha        string
	BaseRef        string
	BaseSha        string
	ReviewDecision string
	MergeableState string
	StackNumber    pgtype.Int4
	StackPosition  pgtype.Int4
	GhUpdatedAt    pgtype.Timestamptz
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
	TombstonedAt   pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
	DisplayUntil   pgtype.Timestamptz
}

type RefreshIntentGeneration struct {
	Kind                string
	RefreshKey          string
	Generation          int64
	UpdatedAt           pgtype.Timestamptz
	CompletedGeneration int64
	DeadlineAt          pgtype.Timestamptz
	EventReceivedAt     pgtype.Timestamptz
}

type Repo struct {
	ID             int64
	InstallationID int64
	OrgID          int64
	GhID           int64
	NodeID         string
	Owner          string
	Name           string
	FullName       string
	DefaultBranch  string
	Archived       bool
	GhUpdatedAt    pgtype.Timestamptz
	HeadSha        string
	SyncedAt       pgtype.Timestamptz
	Etag           string
	SyncSource     string
	TombstonedAt   pgtype.Timestamptz
	LastCheckedAt  pgtype.Timestamptz
}

type RepoAlias struct {
	FullName    string
	RepoID      int64
	FirstSeenAt pgtype.Timestamptz
	LastSeenAt  pgtype.Timestamptz
}

type RepoRule struct {
	RepoID        int64
	RuleKey       string
	Rule          []byte
	GhUpdatedAt   pgtype.Timestamptz
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	Etag          string
	SyncSource    string
	TombstonedAt  pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
}

type RepoRuleSyncState struct {
	RepoID        int64
	Etag          string
	LastCheckedAt pgtype.Timestamptz
}

type ReviewThread struct {
	ID            string
	RepoID        int64
	PrNumber      int32
	IsResolved    bool
	IsOutdated    bool
	Path          string
	Line          pgtype.Int4
	Comments      []byte
	GhUpdatedAt   pgtype.Timestamptz
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	Etag          string
	SyncSource    string
	TombstonedAt  pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
}

type Stack struct {
	ID            int64
	RepoID        int64
	GhID          pgtype.Int8
	NodeID        string
	Number        int32
	BaseRef       string
	BaseSha       string
	Open          bool
	Entries       []byte
	GhUpdatedAt   pgtype.Timestamptz
	HeadSha       string
	SyncedAt      pgtype.Timestamptz
	Etag          string
	SyncSource    string
	TombstonedAt  pgtype.Timestamptz
	LastCheckedAt pgtype.Timestamptz
	DisplayUntil  pgtype.Timestamptz
}

type StreamHorizon struct {
	Stream           string
	PrunedThroughSeq int64
	UpdatedAt        pgtype.Timestamptz
}

type StreamWatermark struct {
	Singleton    bool
	SafeSeq      int64
	CandidateSeq pgtype.Int8
	CandidateXid pgtype.Uint64
	UpdatedAt    pgtype.Timestamptz
	LeaseToken   pgtype.Text
	LeaseUntil   pgtype.Timestamptz
}

type SweepCursor struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
	SeenKeys       []byte
	StartedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	CompletedAt    pgtype.Timestamptz
	PassNewCount   int32
}

type SweepPage struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
	Etag           string
	NextCursor     string
	EntityKeys     []byte
	ListSeenAt     pgtype.Timestamptz
}

type WebhookDelivery struct {
	DeliveryGuid    string
	Event           string
	RawBody         []byte
	Headers         []byte
	ReceivedAt      pgtype.Timestamptz
	Status          string
	Attempts        int32
	LastError       pgtype.Text
	PayloadPrunedAt pgtype.Timestamptz
}

type WorkItem struct {
	IdentityKey string
	OrgID       int64
	Payload     []byte
	UpdatedAt   pgtype.Timestamptz
	ScopeKey    string
}
