// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InstallationBudget struct {
	InstallationID int64
	Class          string
	Remaining      pgtype.Int8
	RateLimit      pgtype.Int8
	ResetAt        pgtype.Timestamptz
	LeaseOwner     pgtype.Text
	LeaseUntil     pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	BackoffUntil   pgtype.Timestamptz
}

type WebhookDelivery struct {
	DeliveryGuid string
	Event        string
	RawBody      []byte
	Headers      []byte
	ReceivedAt   pgtype.Timestamptz
	Status       string
	Attempts     int32
	LastError    pgtype.Text
}
