// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type WebhookDelivery struct {
	DeliveryGuid string
	Event        string
	RawBody      []byte
	Headers      []byte
	ReceivedAt   pgtype.Timestamptz
	Status       string
	Attempts     int32
	LastError    pgtype.Text
}
