// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observation_versions.sql

package dbgen

import (
	"context"
)

const advanceEntityObservationVersion = `-- name: AdvanceEntityObservationVersion :one
INSERT INTO entity_observation_versions (entity_key, version)
VALUES ($1, 1)
ON CONFLICT (entity_key) DO UPDATE
SET version = entity_observation_versions.version + 1
RETURNING version
`

func (q *Queries) AdvanceEntityObservationVersion(ctx context.Context, entityKey string) (int64, error) {
	row := q.db.QueryRow(ctx, advanceEntityObservationVersion, entityKey)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getEntityObservationVersion = `-- name: GetEntityObservationVersion :one
SELECT version
FROM entity_observation_versions
WHERE entity_key = $1
`

func (q *Queries) GetEntityObservationVersion(ctx context.Context, entityKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getEntityObservationVersion, entityKey)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const getEntityObservationVersionForUpdate = `-- name: GetEntityObservationVersionForUpdate :one
SELECT version
FROM entity_observation_versions
WHERE entity_key = $1
FOR UPDATE
`

func (q *Queries) GetEntityObservationVersionForUpdate(ctx context.Context, entityKey string) (int64, error) {
	row := q.db.QueryRow(ctx, getEntityObservationVersionForUpdate, entityKey)
	var version int64
	err := row.Scan(&version)
	return version, err
}
