// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: opsstate.sql

package dbgen

import (
	"context"
)

const recordOperationHeartbeat = `-- name: RecordOperationHeartbeat :exec
INSERT INTO operation_heartbeats (
    installation_id, component, operation,
    success_count, sample_count, last_success_at, last_sample_at
)
VALUES (
    $1, $2, $3,
    1, $4::bigint, clock_timestamp(),
    CASE
        WHEN $4::bigint > 0 THEN clock_timestamp()
        ELSE NULL
    END
)
ON CONFLICT (installation_id, component, operation) DO UPDATE
SET success_count = operation_heartbeats.success_count + 1,
    sample_count = operation_heartbeats.sample_count + EXCLUDED.sample_count,
    last_success_at = EXCLUDED.last_success_at,
    last_sample_at = COALESCE(
        EXCLUDED.last_sample_at,
        operation_heartbeats.last_sample_at
    )
`

type RecordOperationHeartbeatParams struct {
	InstallationID int64
	Component      string
	Operation      string
	Samples        int64
}

func (q *Queries) RecordOperationHeartbeat(ctx context.Context, arg RecordOperationHeartbeatParams) error {
	_, err := q.db.Exec(ctx, recordOperationHeartbeat,
		arg.InstallationID,
		arg.Component,
		arg.Operation,
		arg.Samples,
	)
	return err
}
