// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_intent_generations.sql

package dbgen

import (
	"context"
)

const bumpRefreshIntentGenerations = `-- name: BumpRefreshIntentGenerations :many
WITH intents AS (
    SELECT DISTINCT
        element->>'kind' AS kind,
        element->>'refresh_key' AS refresh_key
    FROM jsonb_array_elements($1::jsonb) AS element
)
INSERT INTO refresh_intent_generations (kind, refresh_key, generation)
SELECT kind, refresh_key, 1
FROM intents
ON CONFLICT (kind, refresh_key) DO UPDATE
SET generation = refresh_intent_generations.generation + 1,
    updated_at = now()
RETURNING kind, refresh_key, generation
`

type BumpRefreshIntentGenerationsRow struct {
	Kind       string
	RefreshKey string
	Generation int64
}

// Bump each coalesced key once in the same transaction that inserts its River
// job. Workers snapshot it when they begin authoritative refresh work.
func (q *Queries) BumpRefreshIntentGenerations(ctx context.Context, intents []byte) ([]BumpRefreshIntentGenerationsRow, error) {
	rows, err := q.db.Query(ctx, bumpRefreshIntentGenerations, intents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BumpRefreshIntentGenerationsRow
	for rows.Next() {
		var i BumpRefreshIntentGenerationsRow
		if err := rows.Scan(&i.Kind, &i.RefreshKey, &i.Generation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshIntentGeneration = `-- name: GetRefreshIntentGeneration :one
SELECT generation
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
`

type GetRefreshIntentGenerationParams struct {
	Kind       string
	RefreshKey string
}

// A running worker snapshots the generation before fetching authoritative
// state. Signals coalesced before the fetch are thereby covered by that fetch.
func (q *Queries) GetRefreshIntentGeneration(ctx context.Context, arg GetRefreshIntentGenerationParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentGeneration, arg.Kind, arg.RefreshKey)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getRefreshIntentGenerationForUpdate = `-- name: GetRefreshIntentGenerationForUpdate :one
SELECT generation
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
FOR UPDATE
`

type GetRefreshIntentGenerationForUpdateParams struct {
	Kind       string
	RefreshKey string
}

// Workers lock the generation before transactionally completing their River
// job. A concurrent dispatcher therefore bumps either before the recheck or
// after completion, when it can insert a fresh job.
func (q *Queries) GetRefreshIntentGenerationForUpdate(ctx context.Context, arg GetRefreshIntentGenerationForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentGenerationForUpdate, arg.Kind, arg.RefreshKey)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}
