// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_intent_generations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireRefreshIntentGenerationLock = `-- name: AcquireRefreshIntentGenerationLock :exec
SELECT pg_advisory_xact_lock(hashtextextended(
    current_database() || chr(31) || $1::text || chr(31) ||
        $2::text,
    0
))
`

type AcquireRefreshIntentGenerationLockParams struct {
	Kind       string
	RefreshKey string
}

// Completion has only one generation key, so it may wait without convoying
// unrelated keys. It takes this lock before the corresponding row lock.
func (q *Queries) AcquireRefreshIntentGenerationLock(ctx context.Context, arg AcquireRefreshIntentGenerationLockParams) error {
	_, err := q.db.Exec(ctx, acquireRefreshIntentGenerationLock, arg.Kind, arg.RefreshKey)
	return err
}

const bumpRefreshIntentGenerations = `-- name: BumpRefreshIntentGenerations :many
WITH intents AS (
    SELECT DISTINCT
        element->>'kind' AS kind,
        element->>'refresh_key' AS refresh_key,
        NULLIF(element->>'deadline_at', '')::timestamptz AS deadline_at,
        NULLIF(element->>'event_received_at', '')::timestamptz
            AS event_received_at
    FROM jsonb_array_elements($1::jsonb) AS element
    -- Upsert conflict-row locks must be acquired in the same order everywhere.
    ORDER BY kind, refresh_key
)
INSERT INTO refresh_intent_generations (
    kind, refresh_key, generation, deadline_at, event_received_at
)
SELECT kind, refresh_key, 1, deadline_at, event_received_at
FROM intents
ON CONFLICT (kind, refresh_key) DO UPDATE
SET generation = refresh_intent_generations.generation + 1,
    deadline_at = CASE
        WHEN EXCLUDED.deadline_at IS NULL
        THEN refresh_intent_generations.deadline_at
        WHEN refresh_intent_generations.deadline_at IS NULL
        THEN EXCLUDED.deadline_at
        ELSE LEAST(
            refresh_intent_generations.deadline_at,
            EXCLUDED.deadline_at
        )
    END,
    event_received_at = CASE
        WHEN EXCLUDED.event_received_at IS NULL
        THEN refresh_intent_generations.event_received_at
        WHEN refresh_intent_generations.event_received_at IS NULL
        THEN EXCLUDED.event_received_at
        ELSE LEAST(
            refresh_intent_generations.event_received_at,
            EXCLUDED.event_received_at
        )
    END,
    updated_at = now()
RETURNING kind, refresh_key, generation, deadline_at, event_received_at
`

type BumpRefreshIntentGenerationsRow struct {
	Kind            string
	RefreshKey      string
	Generation      int64
	DeadlineAt      pgtype.Timestamptz
	EventReceivedAt pgtype.Timestamptz
}

// Bump each coalesced key once in the same transaction that inserts its River
// job. Production callers first acquire the transaction advisory lock for
// every key; this ordered upsert remains a second deadlock-avoidance layer.
// Workers snapshot it when they begin authoritative refresh work.
func (q *Queries) BumpRefreshIntentGenerations(ctx context.Context, intents []byte) ([]BumpRefreshIntentGenerationsRow, error) {
	rows, err := q.db.Query(ctx, bumpRefreshIntentGenerations, intents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BumpRefreshIntentGenerationsRow
	for rows.Next() {
		var i BumpRefreshIntentGenerationsRow
		if err := rows.Scan(
			&i.Kind,
			&i.RefreshKey,
			&i.Generation,
			&i.DeadlineAt,
			&i.EventReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeRefreshIntentGeneration = `-- name: CompleteRefreshIntentGeneration :exec
UPDATE refresh_intent_generations
SET completed_generation = GREATEST(
        completed_generation,
        $1
    ),
    deadline_at = CASE
        WHEN generation = $1
        THEN NULL
        ELSE deadline_at
    END,
    event_received_at = CASE
        WHEN generation = $1
        THEN NULL
        ELSE event_received_at
    END,
    updated_at = now()
WHERE kind = $2
  AND refresh_key = $3
  AND generation >= $1
`

type CompleteRefreshIntentGenerationParams struct {
	CompletedGeneration int64
	Kind                string
	RefreshKey          string
}

func (q *Queries) CompleteRefreshIntentGeneration(ctx context.Context, arg CompleteRefreshIntentGenerationParams) error {
	_, err := q.db.Exec(ctx, completeRefreshIntentGeneration, arg.CompletedGeneration, arg.Kind, arg.RefreshKey)
	return err
}

const getRefreshIntentGenerationForShare = `-- name: GetRefreshIntentGenerationForShare :one
SELECT generation
FROM refresh_intent_generations
WHERE kind = $1
  AND refresh_key = $2
FOR SHARE
`

type GetRefreshIntentGenerationForShareParams struct {
	Kind       string
	RefreshKey string
}

// Post-fetch writers hold a shared row lock through their short entity
// transaction. Producers either finish their generation bump first or wait
// until this write commits; no advisory lock is retained across hooks.
func (q *Queries) GetRefreshIntentGenerationForShare(ctx context.Context, arg GetRefreshIntentGenerationForShareParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentGenerationForShare, arg.Kind, arg.RefreshKey)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getRefreshIntentGenerationForUpdate = `-- name: GetRefreshIntentGenerationForUpdate :one
SELECT generation
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
FOR UPDATE
`

type GetRefreshIntentGenerationForUpdateParams struct {
	Kind       string
	RefreshKey string
}

// Workers lock the generation before transactionally completing their River
// job. A concurrent dispatcher therefore bumps either before the recheck or
// after completion, when it can insert a fresh job.
func (q *Queries) GetRefreshIntentGenerationForUpdate(ctx context.Context, arg GetRefreshIntentGenerationForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentGenerationForUpdate, arg.Kind, arg.RefreshKey)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getRefreshIntentState = `-- name: GetRefreshIntentState :one
SELECT generation, completed_generation, deadline_at, event_received_at
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
`

type GetRefreshIntentStateParams struct {
	Kind       string
	RefreshKey string
}

type GetRefreshIntentStateRow struct {
	Generation          int64
	CompletedGeneration int64
	DeadlineAt          pgtype.Timestamptz
	EventReceivedAt     pgtype.Timestamptz
}

func (q *Queries) GetRefreshIntentState(ctx context.Context, arg GetRefreshIntentStateParams) (GetRefreshIntentStateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentState, arg.Kind, arg.RefreshKey)
	var i GetRefreshIntentStateRow
	err := row.Scan(
		&i.Generation,
		&i.CompletedGeneration,
		&i.DeadlineAt,
		&i.EventReceivedAt,
	)
	return i, err
}

const getRefreshIntentStateForShare = `-- name: GetRefreshIntentStateForShare :one
SELECT generation, completed_generation
FROM refresh_intent_generations
WHERE kind = $1
  AND refresh_key = $2
FOR SHARE
`

type GetRefreshIntentStateForShareParams struct {
	Kind       string
	RefreshKey string
}

type GetRefreshIntentStateForShareRow struct {
	Generation          int64
	CompletedGeneration int64
}

func (q *Queries) GetRefreshIntentStateForShare(ctx context.Context, arg GetRefreshIntentStateForShareParams) (GetRefreshIntentStateForShareRow, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentStateForShare, arg.Kind, arg.RefreshKey)
	var i GetRefreshIntentStateForShareRow
	err := row.Scan(&i.Generation, &i.CompletedGeneration)
	return i, err
}

const tryAcquireRefreshIntentGenerationLocks = `-- name: TryAcquireRefreshIntentGenerationLocks :one
WITH RECURSIVE generation_keys AS MATERIALIZED (
    SELECT
        row_number() OVER (ORDER BY kind, refresh_key) AS lock_index,
        kind,
        refresh_key
    FROM (
        SELECT DISTINCT
            element->>'kind' AS kind,
            element->>'refresh_key' AS refresh_key
        FROM jsonb_array_elements($1::jsonb) AS element
    ) AS parsed
), generation_locks AS (
    SELECT
        lock_index,
        pg_try_advisory_xact_lock(hashtextextended(
            current_database() || chr(31) || kind || chr(31) || refresh_key,
            0
        )) AS acquired
    FROM generation_keys
    WHERE lock_index = 1

    UNION ALL

    SELECT
        next_key.lock_index,
        pg_try_advisory_xact_lock(hashtextextended(
            current_database() || chr(31) || next_key.kind || chr(31) ||
                next_key.refresh_key,
            0
        )) AS acquired
    FROM generation_locks AS prior_lock
    JOIN generation_keys AS next_key
      ON next_key.lock_index = prior_lock.lock_index + 1
    WHERE prior_lock.acquired
), lock_summary AS (
    SELECT count(*) AS key_count
    FROM generation_keys
)
SELECT
    CASE
        WHEN COALESCE((
            SELECT bool_and(acquired)
            FROM generation_locks
        ), true)
          AND (SELECT count(*) FROM generation_locks) = lock_summary.key_count
        THEN true
        ELSE false
    END AS acquired,
    COALESCE((
        SELECT count(*) FILTER (WHERE acquired)
        FROM generation_locks
    ), 0::bigint)::bigint AS acquired_count,
    lock_summary.key_count
FROM lock_summary
`

type TryAcquireRefreshIntentGenerationLocksRow struct {
	Acquired      bool
	AcquiredCount int64
	KeyCount      int64
}

// Producers acquire these transaction locks one key at a time in sorted order.
// A failed try-lock is rolled back with its transaction or containing
// savepoint before it takes any refresh-generation row locks. Include the
// database in the hash because advisory locks are cluster-wide and tests use
// parallel per-test databases.
func (q *Queries) TryAcquireRefreshIntentGenerationLocks(ctx context.Context, keys []byte) (TryAcquireRefreshIntentGenerationLocksRow, error) {
	row := q.db.QueryRow(ctx, tryAcquireRefreshIntentGenerationLocks, keys)
	var i TryAcquireRefreshIntentGenerationLocksRow
	err := row.Scan(&i.Acquired, &i.AcquiredCount, &i.KeyCount)
	return i, err
}

const tryAcquireRefreshIntentGenerationRowLocks = `-- name: TryAcquireRefreshIntentGenerationRowLocks :one
WITH generation_keys AS MATERIALIZED (
    SELECT DISTINCT
        element->>'kind' AS kind,
        element->>'refresh_key' AS refresh_key
    FROM jsonb_array_elements($1::jsonb) AS element
), locked_generation_rows AS MATERIALIZED (
    SELECT generation.kind, generation.refresh_key
    FROM refresh_intent_generations AS generation
    JOIN generation_keys AS requested
      ON requested.kind = generation.kind
     AND requested.refresh_key = generation.refresh_key
    ORDER BY generation.kind, generation.refresh_key
    FOR UPDATE OF generation SKIP LOCKED
), lock_summary AS (
    SELECT
        (SELECT count(*) FROM generation_keys) AS key_count,
        (
            SELECT count(*)
            FROM refresh_intent_generations AS generation
            JOIN generation_keys AS requested
              ON requested.kind = generation.kind
             AND requested.refresh_key = generation.refresh_key
        ) AS existing_count,
        (SELECT count(*) FROM locked_generation_rows) AS locked_count
)
SELECT
    locked_count = existing_count AS acquired,
    (key_count - existing_count + locked_count)::bigint AS acquired_count,
    key_count
FROM lock_summary
`

type TryAcquireRefreshIntentGenerationRowLocksRow struct {
	Acquired      bool
	AcquiredCount int64
	KeyCount      int64
}

// Advisory locks serialize participating producers, but an already-open
// transaction may hold only the generation row. Probe every existing row
// without waiting so a hot row cannot make this transaction retain unrelated
// generation locks.
func (q *Queries) TryAcquireRefreshIntentGenerationRowLocks(ctx context.Context, keys []byte) (TryAcquireRefreshIntentGenerationRowLocksRow, error) {
	row := q.db.QueryRow(ctx, tryAcquireRefreshIntentGenerationRowLocks, keys)
	var i TryAcquireRefreshIntentGenerationRowLocksRow
	err := row.Scan(&i.Acquired, &i.AcquiredCount, &i.KeyCount)
	return i, err
}
