// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_intent_generations.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpRefreshIntentGenerations = `-- name: BumpRefreshIntentGenerations :many
WITH intents AS (
    SELECT DISTINCT
        element->>'kind' AS kind,
        element->>'refresh_key' AS refresh_key,
        NULLIF(element->>'deadline_at', '')::timestamptz AS deadline_at,
        NULLIF(element->>'event_received_at', '')::timestamptz
            AS event_received_at
    FROM jsonb_array_elements($1::jsonb) AS element
    -- Upsert conflict-row locks must be acquired in the same order everywhere.
    ORDER BY kind, refresh_key
)
INSERT INTO refresh_intent_generations (
    kind, refresh_key, generation, deadline_at, event_received_at
)
SELECT kind, refresh_key, 1, deadline_at, event_received_at
FROM intents
ON CONFLICT (kind, refresh_key) DO UPDATE
SET generation = refresh_intent_generations.generation + 1,
    deadline_at = CASE
        WHEN EXCLUDED.deadline_at IS NULL
        THEN refresh_intent_generations.deadline_at
        WHEN refresh_intent_generations.deadline_at IS NULL
        THEN EXCLUDED.deadline_at
        ELSE LEAST(
            refresh_intent_generations.deadline_at,
            EXCLUDED.deadline_at
        )
    END,
    event_received_at = CASE
        WHEN EXCLUDED.event_received_at IS NULL
        THEN refresh_intent_generations.event_received_at
        WHEN refresh_intent_generations.event_received_at IS NULL
        THEN EXCLUDED.event_received_at
        ELSE LEAST(
            refresh_intent_generations.event_received_at,
            EXCLUDED.event_received_at
        )
    END,
    updated_at = now()
RETURNING kind, refresh_key, generation, deadline_at, event_received_at
`

type BumpRefreshIntentGenerationsRow struct {
	Kind            string
	RefreshKey      string
	Generation      int64
	DeadlineAt      pgtype.Timestamptz
	EventReceivedAt pgtype.Timestamptz
}

// Bump each coalesced key once in the same transaction that inserts its River
// job. Workers snapshot it when they begin authoritative refresh work.
func (q *Queries) BumpRefreshIntentGenerations(ctx context.Context, intents []byte) ([]BumpRefreshIntentGenerationsRow, error) {
	rows, err := q.db.Query(ctx, bumpRefreshIntentGenerations, intents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BumpRefreshIntentGenerationsRow
	for rows.Next() {
		var i BumpRefreshIntentGenerationsRow
		if err := rows.Scan(
			&i.Kind,
			&i.RefreshKey,
			&i.Generation,
			&i.DeadlineAt,
			&i.EventReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const completeRefreshIntentGeneration = `-- name: CompleteRefreshIntentGeneration :exec
UPDATE refresh_intent_generations
SET completed_generation = GREATEST(
        completed_generation,
        $1
    ),
    deadline_at = CASE
        WHEN generation = $1
        THEN NULL
        ELSE deadline_at
    END,
    event_received_at = CASE
        WHEN generation = $1
        THEN NULL
        ELSE event_received_at
    END,
    updated_at = now()
WHERE kind = $2
  AND refresh_key = $3
  AND generation >= $1
`

type CompleteRefreshIntentGenerationParams struct {
	CompletedGeneration int64
	Kind                string
	RefreshKey          string
}

func (q *Queries) CompleteRefreshIntentGeneration(ctx context.Context, arg CompleteRefreshIntentGenerationParams) error {
	_, err := q.db.Exec(ctx, completeRefreshIntentGeneration, arg.CompletedGeneration, arg.Kind, arg.RefreshKey)
	return err
}

const getRefreshIntentGenerationForUpdate = `-- name: GetRefreshIntentGenerationForUpdate :one
SELECT generation
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
FOR UPDATE
`

type GetRefreshIntentGenerationForUpdateParams struct {
	Kind       string
	RefreshKey string
}

// Workers lock the generation before transactionally completing their River
// job. A concurrent dispatcher therefore bumps either before the recheck or
// after completion, when it can insert a fresh job.
func (q *Queries) GetRefreshIntentGenerationForUpdate(ctx context.Context, arg GetRefreshIntentGenerationForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentGenerationForUpdate, arg.Kind, arg.RefreshKey)
	var generation int64
	err := row.Scan(&generation)
	return generation, err
}

const getRefreshIntentState = `-- name: GetRefreshIntentState :one
SELECT generation, completed_generation, deadline_at, event_received_at
FROM refresh_intent_generations
WHERE kind = $1 AND refresh_key = $2
`

type GetRefreshIntentStateParams struct {
	Kind       string
	RefreshKey string
}

type GetRefreshIntentStateRow struct {
	Generation          int64
	CompletedGeneration int64
	DeadlineAt          pgtype.Timestamptz
	EventReceivedAt     pgtype.Timestamptz
}

func (q *Queries) GetRefreshIntentState(ctx context.Context, arg GetRefreshIntentStateParams) (GetRefreshIntentStateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshIntentState, arg.Kind, arg.RefreshKey)
	var i GetRefreshIntentStateRow
	err := row.Scan(
		&i.Generation,
		&i.CompletedGeneration,
		&i.DeadlineAt,
		&i.EventReceivedAt,
	)
	return i, err
}
