// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: soak.sql

package dbgen

import (
	"context"
)

const deleteSoakConsumerCursor = `-- name: DeleteSoakConsumerCursor :exec
DELETE FROM consumer_cursors
WHERE consumer = $1
  AND stream = $2
`

type DeleteSoakConsumerCursorParams struct {
	Consumer string
	Stream   string
}

func (q *Queries) DeleteSoakConsumerCursor(ctx context.Context, arg DeleteSoakConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, deleteSoakConsumerCursor, arg.Consumer, arg.Stream)
	return err
}

const getSoakCacheSeedState = `-- name: GetSoakCacheSeedState :one
SELECT
    EXISTS (
        SELECT 1
        FROM installation_backfill_cursors
        WHERE installation_backfill_cursors.installation_id =
              $1
          AND phase = 'done'
          AND completed_at IS NOT NULL
    ) AS installation_done,
    (
        SELECT count(*)
        FROM backfill_cursors
        WHERE backfill_cursors.installation_id = $1
    ) AS repositories,
    (
        SELECT count(*)
        FROM backfill_cursors
        WHERE backfill_cursors.installation_id = $1
          AND phase <> 'done'
    ) AS incomplete_repos,
    (
        SELECT count(*)
        FROM backfill_children
        WHERE backfill_children.installation_id = $1
          AND completed_at IS NULL
    ) AS pending_children,
    (
        SELECT count(*)
        FROM river_job
        WHERE queue IN ('interactive', 'event', 'sweep', 'reconcile')
          AND (
              state IN ('available', 'pending', 'running')
              OR (
                  state IN ('retryable', 'scheduled')
                  AND scheduled_at <= now()
              )
          )
    ) AS cache_writers
`

type GetSoakCacheSeedStateRow struct {
	InstallationDone bool
	Repositories     int64
	IncompleteRepos  int64
	PendingChildren  int64
	CacheWriters     int64
}

func (q *Queries) GetSoakCacheSeedState(ctx context.Context, installationID int64) (GetSoakCacheSeedStateRow, error) {
	row := q.db.QueryRow(ctx, getSoakCacheSeedState, installationID)
	var i GetSoakCacheSeedStateRow
	err := row.Scan(
		&i.InstallationDone,
		&i.Repositories,
		&i.IncompleteRepos,
		&i.PendingChildren,
		&i.CacheWriters,
	)
	return i, err
}

const listSoakCachedPullRequests = `-- name: ListSoakCachedPullRequests :many
SELECT pull.number, pull.title
FROM pull_requests AS pull
JOIN repos AS repo ON repo.id = pull.repo_id
WHERE repo.full_name = $1
  AND repo.tombstoned_at IS NULL
  AND pull.tombstoned_at IS NULL
`

type ListSoakCachedPullRequestsRow struct {
	Number int32
	Title  string
}

func (q *Queries) ListSoakCachedPullRequests(ctx context.Context, repoFullName string) ([]ListSoakCachedPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listSoakCachedPullRequests, repoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSoakCachedPullRequestsRow
	for rows.Next() {
		var i ListSoakCachedPullRequestsRow
		if err := rows.Scan(&i.Number, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
