// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: streamclient.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const ensureConsumerCursor = `-- name: EnsureConsumerCursor :exec
INSERT INTO consumer_cursors (consumer, stream, seq, updated_at)
VALUES (
    $1, $2, 0, clock_timestamp()
)
ON CONFLICT (consumer, stream) DO NOTHING
`

type EnsureConsumerCursorParams struct {
	Consumer string
	Stream   string
}

func (q *Queries) EnsureConsumerCursor(ctx context.Context, arg EnsureConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, ensureConsumerCursor, arg.Consumer, arg.Stream)
	return err
}

const getConsumerCursorForUpdate = `-- name: GetConsumerCursorForUpdate :one
SELECT seq
FROM consumer_cursors
WHERE consumer = $1
  AND stream = $2
FOR UPDATE
`

type GetConsumerCursorForUpdateParams struct {
	Consumer string
	Stream   string
}

func (q *Queries) GetConsumerCursorForUpdate(ctx context.Context, arg GetConsumerCursorForUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, getConsumerCursorForUpdate, arg.Consumer, arg.Stream)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}

const getStreamPrunedThroughSequence = `-- name: GetStreamPrunedThroughSequence :one
SELECT COALESCE((
    SELECT pruned_through_seq
    FROM stream_horizons
    WHERE stream = $1
), 0)::bigint
`

func (q *Queries) GetStreamPrunedThroughSequence(ctx context.Context, stream string) (int64, error) {
	row := q.db.QueryRow(ctx, getStreamPrunedThroughSequence, stream)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getStreamSafeSequence = `-- name: GetStreamSafeSequence :one
SELECT safe_seq
FROM stream_watermark
WHERE singleton
`

func (q *Queries) GetStreamSafeSequence(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getStreamSafeSequence)
	var safe_seq int64
	err := row.Scan(&safe_seq)
	return safe_seq, err
}

const pageChangeEvents = `-- name: PageChangeEvents :many
SELECT seq, stream, kind, entity_key, occurred_at, payload
FROM change_events
WHERE stream = $1
  AND seq > $2
  AND seq <= $3
ORDER BY seq
LIMIT $4
`

type PageChangeEventsParams struct {
	Stream     string
	AfterSeq   int64
	ThroughSeq int64
	PageSize   int32
}

type PageChangeEventsRow struct {
	Seq        int64
	Stream     string
	Kind       string
	EntityKey  string
	OccurredAt pgtype.Timestamptz
	Payload    []byte
}

func (q *Queries) PageChangeEvents(ctx context.Context, arg PageChangeEventsParams) ([]PageChangeEventsRow, error) {
	rows, err := q.db.Query(ctx, pageChangeEvents,
		arg.Stream,
		arg.AfterSeq,
		arg.ThroughSeq,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageChangeEventsRow
	for rows.Next() {
		var i PageChangeEventsRow
		if err := rows.Scan(
			&i.Seq,
			&i.Stream,
			&i.Kind,
			&i.EntityKey,
			&i.OccurredAt,
			&i.Payload,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordConsumerResync = `-- name: RecordConsumerResync :exec
UPDATE consumer_cursors
SET resync_count = resync_count + 1,
    last_resync_at = clock_timestamp(),
    updated_at = clock_timestamp()
WHERE consumer = $1
  AND stream = $2
`

type RecordConsumerResyncParams struct {
	Consumer string
	Stream   string
}

func (q *Queries) RecordConsumerResync(ctx context.Context, arg RecordConsumerResyncParams) error {
	_, err := q.db.Exec(ctx, recordConsumerResync, arg.Consumer, arg.Stream)
	return err
}

const updateConsumerCursor = `-- name: UpdateConsumerCursor :exec
UPDATE consumer_cursors
SET seq = $1, updated_at = clock_timestamp()
WHERE consumer = $2
  AND stream = $3
`

type UpdateConsumerCursorParams struct {
	Seq      int64
	Consumer string
	Stream   string
}

func (q *Queries) UpdateConsumerCursor(ctx context.Context, arg UpdateConsumerCursorParams) error {
	_, err := q.db.Exec(ctx, updateConsumerCursor, arg.Seq, arg.Consumer, arg.Stream)
	return err
}
