// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stream.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acquireOrRenewStreamWatermarkLease = `-- name: AcquireOrRenewStreamWatermarkLease :one
UPDATE stream_watermark
SET lease_token = $1::text,
    lease_until = clock_timestamp() + $2::text::interval
WHERE singleton
  AND (
      lease_token IS NULL
      OR lease_until <= clock_timestamp()
      OR lease_token = $1::text
  )
RETURNING COALESCE(lease_token, '')::text
`

type AcquireOrRenewStreamWatermarkLeaseParams struct {
	LeaseToken string
	LeaseTtl   string
}

func (q *Queries) AcquireOrRenewStreamWatermarkLease(ctx context.Context, arg AcquireOrRenewStreamWatermarkLeaseParams) (string, error) {
	row := q.db.QueryRow(ctx, acquireOrRenewStreamWatermarkLease, arg.LeaseToken, arg.LeaseTtl)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const acquireOutboxWatermarkFence = `-- name: AcquireOutboxWatermarkFence :exec
SELECT pg_advisory_xact_lock($1)
`

func (q *Queries) AcquireOutboxWatermarkFence(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, acquireOutboxWatermarkFence, lockKey)
	return err
}

const acquireOutboxWriterFence = `-- name: AcquireOutboxWriterFence :exec
SELECT pg_advisory_xact_lock_shared($1)
`

func (q *Queries) AcquireOutboxWriterFence(ctx context.Context, lockKey int64) error {
	_, err := q.db.Exec(ctx, acquireOutboxWriterFence, lockKey)
	return err
}

const pruneChangeEvents = `-- name: PruneChangeEvents :execrows
WITH doomed AS MATERIALIZED (
    SELECT events.seq, events.stream
    FROM change_events AS events
    CROSS JOIN stream_watermark AS watermark
    WHERE events.occurred_at < $1
      -- C-S2/C-S7: never publish a pruned horizon above the greatest sequence
      -- consumers were allowed to observe.
      AND events.seq <= watermark.safe_seq
    ORDER BY events.occurred_at, events.seq
    LIMIT $2
    FOR UPDATE OF events SKIP LOCKED
),
advanced AS (
    INSERT INTO stream_horizons (
        stream, pruned_through_seq, updated_at
    )
    SELECT stream, max(seq), clock_timestamp()
    FROM doomed
    GROUP BY stream
    ON CONFLICT (stream) DO UPDATE
    SET pruned_through_seq = GREATEST(
            stream_horizons.pruned_through_seq,
            EXCLUDED.pruned_through_seq
        ),
        updated_at = EXCLUDED.updated_at
    RETURNING stream
)
DELETE FROM change_events AS events
USING doomed
WHERE events.seq = doomed.seq
  -- Reference the data-changing CTE explicitly: horizon and delete are one
  -- atomic RESYNC boundary (C-S4/C-S7).
  AND (SELECT count(*) FROM advanced) >= 0
`

type PruneChangeEventsParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) PruneChangeEvents(ctx context.Context, arg PruneChangeEventsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneChangeEvents, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const publishStreamWatermark = `-- name: PublishStreamWatermark :one
UPDATE stream_watermark
SET safe_seq = $1,
    candidate_seq = NULL,
    candidate_xid = NULL,
    updated_at = clock_timestamp()
WHERE singleton
  AND lease_token = $2::text
  AND lease_until > clock_timestamp()
  AND safe_seq < $1
RETURNING safe_seq
`

type PublishStreamWatermarkParams struct {
	SafeSeq    int64
	LeaseToken string
}

func (q *Queries) PublishStreamWatermark(ctx context.Context, arg PublishStreamWatermarkParams) (int64, error) {
	row := q.db.QueryRow(ctx, publishStreamWatermark, arg.SafeSeq, arg.LeaseToken)
	var safe_seq int64
	err := row.Scan(&safe_seq)
	return safe_seq, err
}

const readStreamWatermarkTarget = `-- name: ReadStreamWatermarkTarget :one
SELECT watermark.safe_seq,
       COALESCE((SELECT max(seq) FROM change_events), 0)::bigint AS target_seq,
       COALESCE(
           watermark.lease_token = $1::text
               AND watermark.lease_until > clock_timestamp(),
           false
       )::boolean AS lease_valid
FROM stream_watermark AS watermark
WHERE watermark.singleton
`

type ReadStreamWatermarkTargetRow struct {
	SafeSeq    int64
	TargetSeq  int64
	LeaseValid bool
}

func (q *Queries) ReadStreamWatermarkTarget(ctx context.Context, leaseToken string) (ReadStreamWatermarkTargetRow, error) {
	row := q.db.QueryRow(ctx, readStreamWatermarkTarget, leaseToken)
	var i ReadStreamWatermarkTargetRow
	err := row.Scan(&i.SafeSeq, &i.TargetSeq, &i.LeaseValid)
	return i, err
}

const releaseStreamWatermarkLease = `-- name: ReleaseStreamWatermarkLease :exec
UPDATE stream_watermark
SET lease_token = NULL, lease_until = NULL
WHERE singleton
  AND lease_token = $1::text
`

func (q *Queries) ReleaseStreamWatermarkLease(ctx context.Context, leaseToken string) error {
	_, err := q.db.Exec(ctx, releaseStreamWatermarkLease, leaseToken)
	return err
}

const setLocalLockTimeout = `-- name: SetLocalLockTimeout :exec
SELECT set_config('lock_timeout', $1, true)
`

func (q *Queries) SetLocalLockTimeout(ctx context.Context, lockTimeout string) error {
	_, err := q.db.Exec(ctx, setLocalLockTimeout, lockTimeout)
	return err
}
