// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sweep.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceGapHealCursor = `-- name: AdvanceGapHealCursor :one
UPDATE gap_heal_cursors
SET cursor = $1,
    updated_at = $2
WHERE installation_id = $3
  AND cursor = $4
  AND completed_at IS NULL
RETURNING installation_id, cursor, cutoff, started_at, updated_at, completed_at
`

type AdvanceGapHealCursorParams struct {
	NextCursor     string
	UpdatedAt      pgtype.Timestamptz
	InstallationID int64
	ExpectedCursor string
}

func (q *Queries) AdvanceGapHealCursor(ctx context.Context, arg AdvanceGapHealCursorParams) (GapHealCursor, error) {
	row := q.db.QueryRow(ctx, advanceGapHealCursor,
		arg.NextCursor,
		arg.UpdatedAt,
		arg.InstallationID,
		arg.ExpectedCursor,
	)
	var i GapHealCursor
	err := row.Scan(
		&i.InstallationID,
		&i.Cursor,
		&i.Cutoff,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const advanceSweepCursor = `-- name: AdvanceSweepCursor :one
UPDATE sweep_cursors
SET cursor = $1,
    pass_new_count = $2,
    updated_at = $3
WHERE installation_id = $4
  AND sweep_kind = $5
  AND scope_key = $6
  AND cursor = $7
  AND completed_at IS NULL
RETURNING installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
`

type AdvanceSweepCursorParams struct {
	NextCursor     string
	PassNewCount   int32
	UpdatedAt      pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	ExpectedCursor string
}

func (q *Queries) AdvanceSweepCursor(ctx context.Context, arg AdvanceSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, advanceSweepCursor,
		arg.NextCursor,
		arg.PassNewCount,
		arg.UpdatedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.ExpectedCursor,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const completeGapHealCursor = `-- name: CompleteGapHealCursor :one
UPDATE gap_heal_cursors
SET cursor = '',
    updated_at = $1,
    completed_at = $1
WHERE installation_id = $2
  AND cursor = $3
  AND completed_at IS NULL
RETURNING installation_id, cursor, cutoff, started_at, updated_at, completed_at
`

type CompleteGapHealCursorParams struct {
	CompletedAt    pgtype.Timestamptz
	InstallationID int64
	ExpectedCursor string
}

func (q *Queries) CompleteGapHealCursor(ctx context.Context, arg CompleteGapHealCursorParams) (GapHealCursor, error) {
	row := q.db.QueryRow(ctx, completeGapHealCursor, arg.CompletedAt, arg.InstallationID, arg.ExpectedCursor)
	var i GapHealCursor
	err := row.Scan(
		&i.InstallationID,
		&i.Cursor,
		&i.Cutoff,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeSweepCursor = `-- name: CompleteSweepCursor :one
UPDATE sweep_cursors
SET cursor = '',
    pass_new_count = 0,
    updated_at = $1,
    completed_at = $1
WHERE installation_id = $2
  AND sweep_kind = $3
  AND scope_key = $4
  AND cursor = $5
  AND completed_at IS NULL
RETURNING installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
`

type CompleteSweepCursorParams struct {
	CompletedAt    pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	ExpectedCursor string
}

func (q *Queries) CompleteSweepCursor(ctx context.Context, arg CompleteSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, completeSweepCursor,
		arg.CompletedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.ExpectedCursor,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const deleteCheckHistoryBatch = `-- name: DeleteCheckHistoryBatch :execrows
DELETE FROM check_history AS history
WHERE history.id IN (
    SELECT candidate.id
    FROM check_history AS candidate
    WHERE candidate.synced_at < $1
    ORDER BY candidate.synced_at, candidate.id
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
`

type DeleteCheckHistoryBatchParams struct {
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) DeleteCheckHistoryBatch(ctx context.Context, arg DeleteCheckHistoryBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckHistoryBatch, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureGapHealCursor = `-- name: EnsureGapHealCursor :one
INSERT INTO gap_heal_cursors (installation_id)
VALUES ($1)
ON CONFLICT (installation_id) DO UPDATE
SET installation_id = EXCLUDED.installation_id
RETURNING installation_id, cursor, cutoff, started_at, updated_at, completed_at
`

func (q *Queries) EnsureGapHealCursor(ctx context.Context, installationID int64) (GapHealCursor, error) {
	row := q.db.QueryRow(ctx, ensureGapHealCursor, installationID)
	var i GapHealCursor
	err := row.Scan(
		&i.InstallationID,
		&i.Cursor,
		&i.Cutoff,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const ensureSweepCursor = `-- name: EnsureSweepCursor :one
INSERT INTO sweep_cursors (
    installation_id, sweep_kind, scope_key
) VALUES (
    $1, $2, $3
)
ON CONFLICT (installation_id, sweep_kind, scope_key) DO UPDATE
SET sweep_kind = EXCLUDED.sweep_kind
RETURNING installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
`

type EnsureSweepCursorParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) EnsureSweepCursor(ctx context.Context, arg EnsureSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, ensureSweepCursor, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const getGapHealCursorForUpdate = `-- name: GetGapHealCursorForUpdate :one
SELECT installation_id, cursor, cutoff, started_at, updated_at, completed_at
FROM gap_heal_cursors
WHERE installation_id = $1
FOR UPDATE
`

func (q *Queries) GetGapHealCursorForUpdate(ctx context.Context, installationID int64) (GapHealCursor, error) {
	row := q.db.QueryRow(ctx, getGapHealCursorForUpdate, installationID)
	var i GapHealCursor
	err := row.Scan(
		&i.InstallationID,
		&i.Cursor,
		&i.Cutoff,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSweepCursor = `-- name: GetSweepCursor :one
SELECT installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
FROM sweep_cursors
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
`

type GetSweepCursorParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) GetSweepCursor(ctx context.Context, arg GetSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, getSweepCursor, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const getSweepCursorForUpdate = `-- name: GetSweepCursorForUpdate :one
SELECT installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
FROM sweep_cursors
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
FOR UPDATE
`

type GetSweepCursorForUpdateParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) GetSweepCursorForUpdate(ctx context.Context, arg GetSweepCursorForUpdateParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, getSweepCursorForUpdate, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const getSweepPage = `-- name: GetSweepPage :one
SELECT installation_id, sweep_kind, scope_key, cursor, etag, next_cursor, entity_keys, list_seen_at
FROM sweep_pages
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
  AND cursor = $4
`

type GetSweepPageParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
}

func (q *Queries) GetSweepPage(ctx context.Context, arg GetSweepPageParams) (SweepPage, error) {
	row := q.db.QueryRow(ctx, getSweepPage,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.Cursor,
	)
	var i SweepPage
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.Etag,
		&i.NextCursor,
		&i.EntityKeys,
		&i.ListSeenAt,
	)
	return i, err
}

const insertSweepSeenKeys = `-- name: InsertSweepSeenKeys :one
WITH input AS (
    SELECT DISTINCT entity_key
    FROM unnest($1::text[]) AS keys(entity_key)
),
inserted AS (
    INSERT INTO sweep_seen_keys (
        installation_id, sweep_kind, scope_key, entity_key, first_seen_at
    )
    SELECT $2, $3,
           $4, input.entity_key, $5
    FROM input
    ON CONFLICT DO NOTHING
    RETURNING entity_key
)
SELECT count(*) FROM inserted
`

type InsertSweepSeenKeysParams struct {
	EntityKeys     []string
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	FirstSeenAt    pgtype.Timestamptz
}

func (q *Queries) InsertSweepSeenKeys(ctx context.Context, arg InsertSweepSeenKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertSweepSeenKeys,
		arg.EntityKeys,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.FirstSeenAt,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listExistingWebhookDeliveryGUIDs = `-- name: ListExistingWebhookDeliveryGUIDs :many
SELECT delivery_guid
FROM webhook_deliveries
WHERE delivery_guid = ANY($1::text[])
`

func (q *Queries) ListExistingWebhookDeliveryGUIDs(ctx context.Context, deliveryGuids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listExistingWebhookDeliveryGUIDs, deliveryGuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var delivery_guid string
		if err := rows.Scan(&delivery_guid); err != nil {
			return nil, err
		}
		items = append(items, delivery_guid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveOpenPullRequestNumbers = `-- name: ListLiveOpenPullRequestNumbers :many
SELECT pull_requests.number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.full_name = $2
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state = 'open'
ORDER BY pull_requests.number
`

type ListLiveOpenPullRequestNumbersParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) ListLiveOpenPullRequestNumbers(ctx context.Context, arg ListLiveOpenPullRequestNumbersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listLiveOpenPullRequestNumbers, arg.InstallationID, arg.RepoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveRepositoryNames = `-- name: ListLiveRepositoryNames :many
SELECT full_name
FROM repos
WHERE installation_id = $1
  AND tombstoned_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListLiveRepositoryNames(ctx context.Context, installationID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listLiveRepositoryNames, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveStackNumbers = `-- name: ListLiveStackNumbers :many
SELECT stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.full_name = $2
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
ORDER BY stacks.number
`

type ListLiveStackNumbersParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) ListLiveStackNumbers(ctx context.Context, arg ListLiveStackNumbersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listLiveStackNumbers, arg.InstallationID, arg.RepoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissingSweepEntityKeys = `-- name: ListMissingSweepEntityKeys :many
WITH cached AS (
    SELECT ('repo:' || repos.full_name || ':metadata')::text AS entity_key
    FROM repos
    WHERE $2::text = 'repositories'
      AND repos.installation_id = $1
      AND repos.tombstoned_at IS NULL

    UNION ALL

    SELECT ('stack:' || repos.full_name || ':' || stacks.number)::text
    FROM stacks
    JOIN repos ON repos.id = stacks.repo_id
    WHERE $2::text = 'stacks'
      AND repos.installation_id = $1
      AND repos.full_name = $3
      AND repos.tombstoned_at IS NULL
      AND stacks.tombstoned_at IS NULL

    UNION ALL

    SELECT ('pr:' || repos.full_name || ':' ||
            pull_requests.number)::text
    FROM pull_requests
    JOIN repos ON repos.id = pull_requests.repo_id
    WHERE $2::text = 'pull_requests'
      AND repos.installation_id = $1
      AND repos.full_name = $3
      AND repos.tombstoned_at IS NULL
      AND pull_requests.tombstoned_at IS NULL
      AND pull_requests.state = 'open'
)
SELECT cached.entity_key
FROM cached
WHERE NOT EXISTS (
    SELECT 1
    FROM sweep_seen_keys AS seen
    WHERE seen.installation_id = $1
      AND seen.sweep_kind = $2
      AND seen.scope_key = $3
      AND seen.entity_key = cached.entity_key
)
ORDER BY cached.entity_key
`

type ListMissingSweepEntityKeysParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

// C-R3/Q13: disappearance candidates are cached live entities absent from the
// row-oriented membership set accumulated by the completed listing.
func (q *Queries) ListMissingSweepEntityKeys(ctx context.Context, arg ListMissingSweepEntityKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMissingSweepEntityKeys, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var entity_key string
		if err := rows.Scan(&entity_key); err != nil {
			return nil, err
		}
		items = append(items, entity_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleClosedPullRequests = `-- name: ListStaleClosedPullRequests :many
SELECT repos.full_name AS repo_full_name, pull_requests.number,
       pull_requests.last_checked_at
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state <> 'open'
  AND pull_requests.display_until > clock_timestamp()
  AND pull_requests.last_checked_at <= $2
ORDER BY pull_requests.last_checked_at,
         pull_requests.repo_id,
         pull_requests.number
`

type ListStaleClosedPullRequestsParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleClosedPullRequestsRow struct {
	RepoFullName  string
	Number        int32
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) ListStaleClosedPullRequests(ctx context.Context, arg ListStaleClosedPullRequestsParams) ([]ListStaleClosedPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listStaleClosedPullRequests, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleClosedPullRequestsRow
	for rows.Next() {
		var i ListStaleClosedPullRequestsRow
		if err := rows.Scan(&i.RepoFullName, &i.Number, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleClosedStacks = `-- name: ListStaleClosedStacks :many
SELECT repos.full_name AS repo_full_name, stacks.number,
       stacks.last_checked_at
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
  AND NOT stacks.open
  AND stacks.display_until > clock_timestamp()
  AND stacks.last_checked_at <= $2
ORDER BY stacks.last_checked_at, stacks.repo_id, stacks.number
`

type ListStaleClosedStacksParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleClosedStacksRow struct {
	RepoFullName  string
	Number        int32
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) ListStaleClosedStacks(ctx context.Context, arg ListStaleClosedStacksParams) ([]ListStaleClosedStacksRow, error) {
	rows, err := q.db.Query(ctx, listStaleClosedStacks, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleClosedStacksRow
	for rows.Next() {
		var i ListStaleClosedStacksRow
		if err := rows.Scan(&i.RepoFullName, &i.Number, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOpenPullRequests = `-- name: ListStaleOpenPullRequests :many
SELECT repos.full_name AS repo_full_name, pull_requests.number,
       pull_requests.last_checked_at
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state = 'open'
  AND pull_requests.last_checked_at <= $2
ORDER BY pull_requests.last_checked_at,
         pull_requests.repo_id,
         pull_requests.number
`

type ListStaleOpenPullRequestsParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleOpenPullRequestsRow struct {
	RepoFullName  string
	Number        int32
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) ListStaleOpenPullRequests(ctx context.Context, arg ListStaleOpenPullRequestsParams) ([]ListStaleOpenPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listStaleOpenPullRequests, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleOpenPullRequestsRow
	for rows.Next() {
		var i ListStaleOpenPullRequestsRow
		if err := rows.Scan(&i.RepoFullName, &i.Number, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOpenStacks = `-- name: ListStaleOpenStacks :many
SELECT repos.full_name AS repo_full_name, stacks.number,
       stacks.last_checked_at
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
  AND stacks.open
  AND stacks.last_checked_at <= $2
ORDER BY stacks.last_checked_at, stacks.repo_id, stacks.number
`

type ListStaleOpenStacksParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleOpenStacksRow struct {
	RepoFullName  string
	Number        int32
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) ListStaleOpenStacks(ctx context.Context, arg ListStaleOpenStacksParams) ([]ListStaleOpenStacksRow, error) {
	rows, err := q.db.Query(ctx, listStaleOpenStacks, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleOpenStacksRow
	for rows.Next() {
		var i ListStaleOpenStacksRow
		if err := rows.Scan(&i.RepoFullName, &i.Number, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRepoRules = `-- name: ListStaleRepoRules :many
SELECT repos.full_name,
       COALESCE(
           repo_rule_sync_state.last_checked_at,
           repos.last_checked_at
       ) AS last_checked_at
FROM repos
LEFT JOIN repo_rule_sync_state ON repo_rule_sync_state.repo_id = repos.id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND COALESCE(
      repo_rule_sync_state.last_checked_at,
      repos.last_checked_at
  ) <= $2
ORDER BY COALESCE(
    repo_rule_sync_state.last_checked_at,
    repos.last_checked_at
), repos.full_name
`

type ListStaleRepoRulesParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleRepoRulesRow struct {
	FullName      string
	LastCheckedAt pgtype.Timestamptz
}

func (q *Queries) ListStaleRepoRules(ctx context.Context, arg ListStaleRepoRulesParams) ([]ListStaleRepoRulesRow, error) {
	rows, err := q.db.Query(ctx, listStaleRepoRules, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleRepoRulesRow
	for rows.Next() {
		var i ListStaleRepoRulesRow
		if err := rows.Scan(&i.FullName, &i.LastCheckedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepRepositories = `-- name: ListSweepRepositories :many
SELECT id, gh_id, full_name
FROM repos
WHERE installation_id = $1
  AND tombstoned_at IS NULL
ORDER BY id
`

type ListSweepRepositoriesRow struct {
	ID       int64
	GhID     int64
	FullName string
}

func (q *Queries) ListSweepRepositories(ctx context.Context, installationID int64) ([]ListSweepRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listSweepRepositories, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSweepRepositoriesRow
	for rows.Next() {
		var i ListSweepRepositoriesRow
		if err := rows.Scan(&i.ID, &i.GhID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWebhookDeliveryPayloadBatch = `-- name: PruneWebhookDeliveryPayloadBatch :execrows
WITH batch AS (
    SELECT candidate.delivery_guid
    FROM webhook_deliveries AS candidate
    WHERE candidate.received_at < $2
      AND candidate.raw_body IS NOT NULL
      AND candidate.status = 'processed'
    ORDER BY candidate.received_at, candidate.delivery_guid
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
UPDATE webhook_deliveries AS delivery
SET raw_body = NULL,
    headers = '{}'::jsonb,
    traceparent = NULL,
    tracestate = NULL,
    payload_pruned_at = $1
FROM batch
WHERE delivery.delivery_guid = batch.delivery_guid
`

type PruneWebhookDeliveryPayloadBatchParams struct {
	PrunedAt  pgtype.Timestamptz
	Cutoff    pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) PruneWebhookDeliveryPayloadBatch(ctx context.Context, arg PruneWebhookDeliveryPayloadBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookDeliveryPayloadBatch, arg.PrunedAt, arg.Cutoff, arg.BatchSize)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reapOrphanedRepositorySweepCursors = `-- name: ReapOrphanedRepositorySweepCursors :execrows
DELETE FROM sweep_cursors AS cursor
WHERE cursor.installation_id = $1
  AND cursor.sweep_kind IN ('stacks', 'pull_requests')
  AND NOT EXISTS (
      SELECT 1
      FROM repos
      WHERE repos.installation_id = cursor.installation_id
        AND repos.full_name = cursor.scope_key
        AND repos.tombstoned_at IS NULL
  )
`

// Q16: repository-scoped cursors use mutable names to call GitHub. Remove
// scopes whose current live repository identity no longer owns that name;
// child pages and seen keys follow via ON DELETE CASCADE.
func (q *Queries) ReapOrphanedRepositorySweepCursors(ctx context.Context, installationID int64) (int64, error) {
	result, err := q.db.Exec(ctx, reapOrphanedRepositorySweepCursors, installationID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const restartSweepCursorPass = `-- name: RestartSweepCursorPass :one
UPDATE sweep_cursors
SET cursor = $1,
    pass_new_count = 0,
    updated_at = $2
WHERE installation_id = $3
  AND sweep_kind = $4
  AND scope_key = $5
  AND cursor = $6
  AND completed_at IS NULL
RETURNING installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
`

type RestartSweepCursorPassParams struct {
	FirstCursor    string
	UpdatedAt      pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	ExpectedCursor string
}

func (q *Queries) RestartSweepCursorPass(ctx context.Context, arg RestartSweepCursorPassParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, restartSweepCursorPass,
		arg.FirstCursor,
		arg.UpdatedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.ExpectedCursor,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const startGapHealCursor = `-- name: StartGapHealCursor :one
UPDATE gap_heal_cursors
SET cursor = '',
    cutoff = $1,
    started_at = $2,
    updated_at = $2,
    completed_at = NULL
WHERE installation_id = $3
RETURNING installation_id, cursor, cutoff, started_at, updated_at, completed_at
`

type StartGapHealCursorParams struct {
	Cutoff         pgtype.Timestamptz
	StartedAt      pgtype.Timestamptz
	InstallationID int64
}

func (q *Queries) StartGapHealCursor(ctx context.Context, arg StartGapHealCursorParams) (GapHealCursor, error) {
	row := q.db.QueryRow(ctx, startGapHealCursor, arg.Cutoff, arg.StartedAt, arg.InstallationID)
	var i GapHealCursor
	err := row.Scan(
		&i.InstallationID,
		&i.Cursor,
		&i.Cutoff,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const startSweepCursor = `-- name: StartSweepCursor :one
WITH cleared AS (
    DELETE FROM sweep_seen_keys
    WHERE installation_id = $3
      AND sweep_kind = $4
      AND scope_key = $5
    RETURNING entity_key
)
UPDATE sweep_cursors
SET cursor = $1,
    pass_new_count = 0,
    started_at = $2,
    updated_at = $2,
    completed_at = NULL
WHERE sweep_cursors.installation_id = $3
  AND sweep_cursors.sweep_kind = $4
  AND sweep_cursors.scope_key = $5
  AND (SELECT count(*) FROM cleared) >= 0
RETURNING installation_id, sweep_kind, scope_key, cursor, started_at, updated_at, completed_at, pass_new_count
`

type StartSweepCursorParams struct {
	FirstCursor    string
	StartedAt      pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) StartSweepCursor(ctx context.Context, arg StartSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, startSweepCursor,
		arg.FirstCursor,
		arg.StartedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.PassNewCount,
	)
	return i, err
}

const upsertSweepPage = `-- name: UpsertSweepPage :exec
INSERT INTO sweep_pages (
    installation_id, sweep_kind, scope_key, cursor, etag, next_cursor,
    entity_keys, list_seen_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT (installation_id, sweep_kind, scope_key, cursor) DO UPDATE
SET etag = EXCLUDED.etag,
    next_cursor = EXCLUDED.next_cursor,
    entity_keys = EXCLUDED.entity_keys,
    list_seen_at = EXCLUDED.list_seen_at
`

type UpsertSweepPageParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
	Etag           string
	NextCursor     string
	EntityKeys     []byte
	ListSeenAt     pgtype.Timestamptz
}

func (q *Queries) UpsertSweepPage(ctx context.Context, arg UpsertSweepPageParams) error {
	_, err := q.db.Exec(ctx, upsertSweepPage,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.Cursor,
		arg.Etag,
		arg.NextCursor,
		arg.EntityKeys,
		arg.ListSeenAt,
	)
	return err
}
