// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sweep.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceSweepCursor = `-- name: AdvanceSweepCursor :one
UPDATE sweep_cursors
SET cursor = $1,
    seen_keys = $2,
    updated_at = $3
WHERE installation_id = $4
  AND sweep_kind = $5
  AND scope_key = $6
  AND cursor = $7
  AND completed_at IS NULL
RETURNING installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
`

type AdvanceSweepCursorParams struct {
	NextCursor     string
	SeenKeys       []byte
	UpdatedAt      pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	ExpectedCursor string
}

func (q *Queries) AdvanceSweepCursor(ctx context.Context, arg AdvanceSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, advanceSweepCursor,
		arg.NextCursor,
		arg.SeenKeys,
		arg.UpdatedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.ExpectedCursor,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeSweepCursor = `-- name: CompleteSweepCursor :one
UPDATE sweep_cursors
SET cursor = '',
    seen_keys = $1,
    updated_at = $2,
    completed_at = $2
WHERE installation_id = $3
  AND sweep_kind = $4
  AND scope_key = $5
  AND cursor = $6
  AND completed_at IS NULL
RETURNING installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
`

type CompleteSweepCursorParams struct {
	SeenKeys       []byte
	CompletedAt    pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	ExpectedCursor string
}

func (q *Queries) CompleteSweepCursor(ctx context.Context, arg CompleteSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, completeSweepCursor,
		arg.SeenKeys,
		arg.CompletedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.ExpectedCursor,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteCheckHistoryBefore = `-- name: DeleteCheckHistoryBefore :execrows
DELETE FROM check_history
WHERE synced_at < $1
`

func (q *Queries) DeleteCheckHistoryBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCheckHistoryBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureSweepCursor = `-- name: EnsureSweepCursor :one
INSERT INTO sweep_cursors (
    installation_id, sweep_kind, scope_key
) VALUES (
    $1, $2, $3
)
ON CONFLICT (installation_id, sweep_kind, scope_key) DO UPDATE
SET sweep_kind = EXCLUDED.sweep_kind
RETURNING installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
`

type EnsureSweepCursorParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) EnsureSweepCursor(ctx context.Context, arg EnsureSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, ensureSweepCursor, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSweepCursor = `-- name: GetSweepCursor :one
SELECT installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
FROM sweep_cursors
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
`

type GetSweepCursorParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) GetSweepCursor(ctx context.Context, arg GetSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, getSweepCursor, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSweepCursorForUpdate = `-- name: GetSweepCursorForUpdate :one
SELECT installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
FROM sweep_cursors
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
FOR UPDATE
`

type GetSweepCursorForUpdateParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) GetSweepCursorForUpdate(ctx context.Context, arg GetSweepCursorForUpdateParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, getSweepCursorForUpdate, arg.InstallationID, arg.SweepKind, arg.ScopeKey)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getSweepPage = `-- name: GetSweepPage :one
SELECT installation_id, sweep_kind, scope_key, cursor, etag, next_cursor, entity_keys, last_checked_at
FROM sweep_pages
WHERE installation_id = $1
  AND sweep_kind = $2
  AND scope_key = $3
  AND cursor = $4
`

type GetSweepPageParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
}

func (q *Queries) GetSweepPage(ctx context.Context, arg GetSweepPageParams) (SweepPage, error) {
	row := q.db.QueryRow(ctx, getSweepPage,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.Cursor,
	)
	var i SweepPage
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.Etag,
		&i.NextCursor,
		&i.EntityKeys,
		&i.LastCheckedAt,
	)
	return i, err
}

const listExistingWebhookDeliveryGUIDs = `-- name: ListExistingWebhookDeliveryGUIDs :many
SELECT delivery_guid
FROM webhook_deliveries
WHERE delivery_guid = ANY($1::text[])
`

func (q *Queries) ListExistingWebhookDeliveryGUIDs(ctx context.Context, deliveryGuids []string) ([]string, error) {
	rows, err := q.db.Query(ctx, listExistingWebhookDeliveryGUIDs, deliveryGuids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var delivery_guid string
		if err := rows.Scan(&delivery_guid); err != nil {
			return nil, err
		}
		items = append(items, delivery_guid)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveOpenPullRequestNumbers = `-- name: ListLiveOpenPullRequestNumbers :many
SELECT pull_requests.number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.full_name = $2
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state = 'open'
ORDER BY pull_requests.number
`

type ListLiveOpenPullRequestNumbersParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) ListLiveOpenPullRequestNumbers(ctx context.Context, arg ListLiveOpenPullRequestNumbersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listLiveOpenPullRequestNumbers, arg.InstallationID, arg.RepoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveRepositoryNames = `-- name: ListLiveRepositoryNames :many
SELECT full_name
FROM repos
WHERE installation_id = $1
  AND tombstoned_at IS NULL
ORDER BY full_name
`

func (q *Queries) ListLiveRepositoryNames(ctx context.Context, installationID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listLiveRepositoryNames, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveStackNumbers = `-- name: ListLiveStackNumbers :many
SELECT stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.full_name = $2
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
ORDER BY stacks.number
`

type ListLiveStackNumbersParams struct {
	InstallationID int64
	RepoFullName   string
}

func (q *Queries) ListLiveStackNumbers(ctx context.Context, arg ListLiveStackNumbersParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, listLiveStackNumbers, arg.InstallationID, arg.RepoFullName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int32
	for rows.Next() {
		var number int32
		if err := rows.Scan(&number); err != nil {
			return nil, err
		}
		items = append(items, number)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleClosedPullRequests = `-- name: ListStaleClosedPullRequests :many
SELECT repos.full_name AS repo_full_name, pull_requests.number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state <> 'open'
  AND pull_requests.last_checked_at <= $2
ORDER BY pull_requests.last_checked_at, repos.full_name, pull_requests.number
`

type ListStaleClosedPullRequestsParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleClosedPullRequestsRow struct {
	RepoFullName string
	Number       int32
}

func (q *Queries) ListStaleClosedPullRequests(ctx context.Context, arg ListStaleClosedPullRequestsParams) ([]ListStaleClosedPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listStaleClosedPullRequests, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleClosedPullRequestsRow
	for rows.Next() {
		var i ListStaleClosedPullRequestsRow
		if err := rows.Scan(&i.RepoFullName, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleClosedStacks = `-- name: ListStaleClosedStacks :many
SELECT repos.full_name AS repo_full_name, stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
  AND NOT stacks.open
  AND stacks.last_checked_at <= $2
ORDER BY stacks.last_checked_at, repos.full_name, stacks.number
`

type ListStaleClosedStacksParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleClosedStacksRow struct {
	RepoFullName string
	Number       int32
}

func (q *Queries) ListStaleClosedStacks(ctx context.Context, arg ListStaleClosedStacksParams) ([]ListStaleClosedStacksRow, error) {
	rows, err := q.db.Query(ctx, listStaleClosedStacks, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleClosedStacksRow
	for rows.Next() {
		var i ListStaleClosedStacksRow
		if err := rows.Scan(&i.RepoFullName, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOpenPullRequests = `-- name: ListStaleOpenPullRequests :many
SELECT repos.full_name AS repo_full_name, pull_requests.number
FROM pull_requests
JOIN repos ON repos.id = pull_requests.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state = 'open'
  AND pull_requests.last_checked_at <= $2
ORDER BY pull_requests.last_checked_at, repos.full_name, pull_requests.number
`

type ListStaleOpenPullRequestsParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleOpenPullRequestsRow struct {
	RepoFullName string
	Number       int32
}

func (q *Queries) ListStaleOpenPullRequests(ctx context.Context, arg ListStaleOpenPullRequestsParams) ([]ListStaleOpenPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, listStaleOpenPullRequests, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleOpenPullRequestsRow
	for rows.Next() {
		var i ListStaleOpenPullRequestsRow
		if err := rows.Scan(&i.RepoFullName, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleOpenStacks = `-- name: ListStaleOpenStacks :many
SELECT repos.full_name AS repo_full_name, stacks.number
FROM stacks
JOIN repos ON repos.id = stacks.repo_id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
  AND stacks.open
  AND stacks.last_checked_at <= $2
ORDER BY stacks.last_checked_at, repos.full_name, stacks.number
`

type ListStaleOpenStacksParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

type ListStaleOpenStacksRow struct {
	RepoFullName string
	Number       int32
}

func (q *Queries) ListStaleOpenStacks(ctx context.Context, arg ListStaleOpenStacksParams) ([]ListStaleOpenStacksRow, error) {
	rows, err := q.db.Query(ctx, listStaleOpenStacks, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaleOpenStacksRow
	for rows.Next() {
		var i ListStaleOpenStacksRow
		if err := rows.Scan(&i.RepoFullName, &i.Number); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleRepoRules = `-- name: ListStaleRepoRules :many
SELECT repos.full_name
FROM repos
LEFT JOIN repo_rule_sync_state ON repo_rule_sync_state.repo_id = repos.id
WHERE repos.installation_id = $1
  AND repos.tombstoned_at IS NULL
  AND COALESCE(
      repo_rule_sync_state.last_checked_at,
      repos.last_checked_at
  ) <= $2
ORDER BY COALESCE(
    repo_rule_sync_state.last_checked_at,
    repos.last_checked_at
), repos.full_name
`

type ListStaleRepoRulesParams struct {
	InstallationID int64
	StaleBefore    pgtype.Timestamptz
}

func (q *Queries) ListStaleRepoRules(ctx context.Context, arg ListStaleRepoRulesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listStaleRepoRules, arg.InstallationID, arg.StaleBefore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var full_name string
		if err := rows.Scan(&full_name); err != nil {
			return nil, err
		}
		items = append(items, full_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSweepRepositories = `-- name: ListSweepRepositories :many
SELECT id, gh_id, full_name
FROM repos
WHERE installation_id = $1
  AND tombstoned_at IS NULL
ORDER BY id
`

type ListSweepRepositoriesRow struct {
	ID       int64
	GhID     int64
	FullName string
}

func (q *Queries) ListSweepRepositories(ctx context.Context, installationID int64) ([]ListSweepRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, listSweepRepositories, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSweepRepositoriesRow
	for rows.Next() {
		var i ListSweepRepositoriesRow
		if err := rows.Scan(&i.ID, &i.GhID, &i.FullName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneWebhookDeliveryPayloads = `-- name: PruneWebhookDeliveryPayloads :execrows
UPDATE webhook_deliveries
SET raw_body = NULL,
    headers = '{}'::jsonb,
    payload_pruned_at = $1
WHERE received_at < $2
  AND raw_body IS NOT NULL
`

type PruneWebhookDeliveryPayloadsParams struct {
	PrunedAt pgtype.Timestamptz
	Cutoff   pgtype.Timestamptz
}

func (q *Queries) PruneWebhookDeliveryPayloads(ctx context.Context, arg PruneWebhookDeliveryPayloadsParams) (int64, error) {
	result, err := q.db.Exec(ctx, pruneWebhookDeliveryPayloads, arg.PrunedAt, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const startSweepCursor = `-- name: StartSweepCursor :one
UPDATE sweep_cursors
SET cursor = $1,
    seen_keys = '[]'::jsonb,
    started_at = $2,
    updated_at = $2,
    completed_at = NULL
WHERE installation_id = $3
  AND sweep_kind = $4
  AND scope_key = $5
RETURNING installation_id, sweep_kind, scope_key, cursor, seen_keys, started_at, updated_at, completed_at
`

type StartSweepCursorParams struct {
	FirstCursor    string
	StartedAt      pgtype.Timestamptz
	InstallationID int64
	SweepKind      string
	ScopeKey       string
}

func (q *Queries) StartSweepCursor(ctx context.Context, arg StartSweepCursorParams) (SweepCursor, error) {
	row := q.db.QueryRow(ctx, startSweepCursor,
		arg.FirstCursor,
		arg.StartedAt,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
	)
	var i SweepCursor
	err := row.Scan(
		&i.InstallationID,
		&i.SweepKind,
		&i.ScopeKey,
		&i.Cursor,
		&i.SeenKeys,
		&i.StartedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const touchListedPullRequestsCheckedAt = `-- name: TouchListedPullRequestsCheckedAt :execrows
UPDATE pull_requests
SET last_checked_at = GREATEST(
    last_checked_at,
    $1
)
FROM repos
WHERE repos.id = pull_requests.repo_id
  AND repos.installation_id = $2
  AND repos.full_name = $3
  AND repos.tombstoned_at IS NULL
  AND pull_requests.tombstoned_at IS NULL
  AND pull_requests.state = 'open'
  AND pull_requests.number = ANY($4::int[])
`

type TouchListedPullRequestsCheckedAtParams struct {
	CheckedAt      pgtype.Timestamptz
	InstallationID int64
	RepoFullName   string
	PrNumbers      []int32
}

// C-R1/C-B4: the unchanged authoritative open-PR page is a successful
// validation for every live PR summary it contains.
func (q *Queries) TouchListedPullRequestsCheckedAt(ctx context.Context, arg TouchListedPullRequestsCheckedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchListedPullRequestsCheckedAt,
		arg.CheckedAt,
		arg.InstallationID,
		arg.RepoFullName,
		arg.PrNumbers,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchListedStacksCheckedAt = `-- name: TouchListedStacksCheckedAt :execrows
UPDATE stacks
SET last_checked_at = GREATEST(
    last_checked_at,
    $1
)
FROM repos
WHERE repos.id = stacks.repo_id
  AND repos.installation_id = $2
  AND repos.full_name = $3
  AND repos.tombstoned_at IS NULL
  AND stacks.tombstoned_at IS NULL
  AND stacks.open
  AND stacks.number = ANY($4::int[])
`

type TouchListedStacksCheckedAtParams struct {
	CheckedAt      pgtype.Timestamptz
	InstallationID int64
	RepoFullName   string
	StackNumbers   []int32
}

// A 304 on the authoritative stack-list page validates the open stack
// summaries on that page without downloading one response per stack.
func (q *Queries) TouchListedStacksCheckedAt(ctx context.Context, arg TouchListedStacksCheckedAtParams) (int64, error) {
	result, err := q.db.Exec(ctx, touchListedStacksCheckedAt,
		arg.CheckedAt,
		arg.InstallationID,
		arg.RepoFullName,
		arg.StackNumbers,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertSweepPage = `-- name: UpsertSweepPage :exec
INSERT INTO sweep_pages (
    installation_id, sweep_kind, scope_key, cursor, etag, next_cursor,
    entity_keys, last_checked_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8
)
ON CONFLICT (installation_id, sweep_kind, scope_key, cursor) DO UPDATE
SET etag = EXCLUDED.etag,
    next_cursor = EXCLUDED.next_cursor,
    entity_keys = EXCLUDED.entity_keys,
    last_checked_at = EXCLUDED.last_checked_at
`

type UpsertSweepPageParams struct {
	InstallationID int64
	SweepKind      string
	ScopeKey       string
	Cursor         string
	Etag           string
	NextCursor     string
	EntityKeys     []byte
	LastCheckedAt  pgtype.Timestamptz
}

func (q *Queries) UpsertSweepPage(ctx context.Context, arg UpsertSweepPageParams) error {
	_, err := q.db.Exec(ctx, upsertSweepPage,
		arg.InstallationID,
		arg.SweepKind,
		arg.ScopeKey,
		arg.Cursor,
		arg.Etag,
		arg.NextCursor,
		arg.EntityKeys,
		arg.LastCheckedAt,
	)
	return err
}
