// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package dbgen

import (
	"context"
)

const countWebhookDeliveriesByStatus = `-- name: CountWebhookDeliveriesByStatus :one
SELECT count(*) FROM webhook_deliveries WHERE status = $1
`

func (q *Queries) CountWebhookDeliveriesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT delivery_guid, event, raw_body, headers, received_at, status, attempts, last_error FROM webhook_deliveries WHERE delivery_guid = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, deliveryGuid string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, deliveryGuid)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryGuid,
		&i.Event,
		&i.RawBody,
		&i.Headers,
		&i.ReceivedAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :execrows
INSERT INTO webhook_deliveries (delivery_guid, event, raw_body, headers)
VALUES ($1, $2, $3, $4)
ON CONFLICT (delivery_guid) DO NOTHING
`

type InsertWebhookDeliveryParams struct {
	DeliveryGuid string
	Event        string
	RawBody      []byte
	Headers      []byte
}

// C-I3: duplicate deliveries are free no-ops.
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.DeliveryGuid,
		arg.Event,
		arg.RawBody,
		arg.Headers,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
