// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhook_deliveries.sql

package dbgen

import (
	"context"
)

const claimWebhookDeliveries = `-- name: ClaimWebhookDeliveries :many
WITH candidates AS (
    SELECT candidate.delivery_guid
    FROM webhook_deliveries AS candidate
    WHERE candidate.status = 'pending'
      AND candidate.next_attempt_at <= clock_timestamp()
    ORDER BY candidate.next_attempt_at,
             candidate.received_at,
             candidate.delivery_guid
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE webhook_deliveries AS delivery
SET status = 'processing',
    attempts = delivery.attempts + 1,
    last_error = NULL
FROM candidates
WHERE delivery.delivery_guid = candidates.delivery_guid
RETURNING delivery.delivery_guid, delivery.event, delivery.raw_body, delivery.headers, delivery.received_at, delivery.status, delivery.attempts, delivery.last_error, delivery.payload_pruned_at, delivery.next_attempt_at, delivery.traceparent, delivery.tracestate
`

// C-P2/C-O2: claim a bounded batch without blocking another dispatcher. The
// processing transition and attempt increment remain in the caller's batch
// transaction, so a crashed dispatcher rolls the claim back to pending.
func (q *Queries) ClaimWebhookDeliveries(ctx context.Context, batchSize int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, claimWebhookDeliveries, batchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryGuid,
			&i.Event,
			&i.RawBody,
			&i.Headers,
			&i.ReceivedAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.PayloadPrunedAt,
			&i.NextAttemptAt,
			&i.Traceparent,
			&i.Tracestate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookDeliveriesByStatus = `-- name: CountWebhookDeliveriesByStatus :one
SELECT count(*) FROM webhook_deliveries WHERE status = $1
`

func (q *Queries) CountWebhookDeliveriesByStatus(ctx context.Context, status string) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveriesByStatus, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWebhookDelivery = `-- name: GetWebhookDelivery :one
SELECT delivery_guid, event, raw_body, headers, received_at, status, attempts, last_error, payload_pruned_at, next_attempt_at, traceparent, tracestate FROM webhook_deliveries WHERE delivery_guid = $1
`

func (q *Queries) GetWebhookDelivery(ctx context.Context, deliveryGuid string) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDelivery, deliveryGuid)
	var i WebhookDelivery
	err := row.Scan(
		&i.DeliveryGuid,
		&i.Event,
		&i.RawBody,
		&i.Headers,
		&i.ReceivedAt,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.PayloadPrunedAt,
		&i.NextAttemptAt,
		&i.Traceparent,
		&i.Tracestate,
	)
	return i, err
}

const insertWebhookDelivery = `-- name: InsertWebhookDelivery :execrows
INSERT INTO webhook_deliveries (
    delivery_guid,
    event,
    raw_body,
    headers,
    traceparent,
    tracestate
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    NULLIF($5::text, ''),
    NULLIF($6::text, '')
)
ON CONFLICT (delivery_guid) DO NOTHING
`

type InsertWebhookDeliveryParams struct {
	DeliveryGuid string
	Event        string
	RawBody      []byte
	Headers      []byte
	Traceparent  string
	Tracestate   string
}

// C-I3: duplicate deliveries are free no-ops.
func (q *Queries) InsertWebhookDelivery(ctx context.Context, arg InsertWebhookDeliveryParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertWebhookDelivery,
		arg.DeliveryGuid,
		arg.Event,
		arg.RawBody,
		arg.Headers,
		arg.Traceparent,
		arg.Tracestate,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listParkedWebhookDeliveries = `-- name: ListParkedWebhookDeliveries :many
SELECT delivery_guid, event, raw_body, headers, received_at, status, attempts, last_error, payload_pruned_at, next_attempt_at, traceparent, tracestate
FROM webhook_deliveries
WHERE status = 'parked'
ORDER BY received_at, delivery_guid
LIMIT $1
`

// C-I5: dead-letter deliveries are explicitly queryable for operations and
// replay tooling.
func (q *Queries) ListParkedWebhookDeliveries(ctx context.Context, resultLimit int32) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listParkedWebhookDeliveries, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebhookDelivery
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.DeliveryGuid,
			&i.Event,
			&i.RawBody,
			&i.Headers,
			&i.ReceivedAt,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.PayloadPrunedAt,
			&i.NextAttemptAt,
			&i.Traceparent,
			&i.Tracestate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueParkedWebhookDeliveries = `-- name: RequeueParkedWebhookDeliveries :execrows
WITH selected AS MATERIALIZED (
    SELECT delivery_guid, raw_body, payload_pruned_at
    FROM webhook_deliveries
    WHERE status = 'parked'
      AND (
          (
              COALESCE(
                  cardinality($1::text[]),
                  0
              ) > 0
              AND delivery_guid = ANY($1::text[])
          )
          OR (
              COALESCE(
                  cardinality($1::text[]),
                  0
              ) = 0
              AND event = $2::text
              AND COALESCE(last_error, '') LIKE
                  '%' || $3::text || '%'
          )
      )
    ORDER BY received_at, delivery_guid
    LIMIT 100
    FOR UPDATE SKIP LOCKED
),
refused AS (
    UPDATE webhook_deliveries AS delivery
    SET last_error = format(
        'operator requeue refused at %s: payload unavailable%s; prior error: %s',
        clock_timestamp(),
        CASE
            WHEN selected.payload_pruned_at IS NOT NULL
            THEN format(' (pruned at %s)', selected.payload_pruned_at)
            ELSE ' (raw body is null)'
        END,
        COALESCE(delivery.last_error, '<none>')
    )
    FROM selected
    WHERE delivery.delivery_guid = selected.delivery_guid
      AND (
          selected.payload_pruned_at IS NOT NULL
          OR selected.raw_body IS NULL
      )
    RETURNING delivery.delivery_guid
),
candidates AS (
    SELECT delivery_guid
    FROM selected
    WHERE payload_pruned_at IS NULL
      AND raw_body IS NOT NULL
)
UPDATE webhook_deliveries AS delivery
SET status = 'pending',
    attempts = 0,
    next_attempt_at = clock_timestamp(),
    last_error = format(
        'operator requeue at %s; attempts reset from %s; prior error: %s',
        clock_timestamp(),
        delivery.attempts,
        COALESCE(delivery.last_error, '<none>')
    )
FROM candidates
WHERE delivery.delivery_guid = candidates.delivery_guid
  AND (SELECT count(*) FROM refused) >= 0
`

type RequeueParkedWebhookDeliveriesParams struct {
	DeliveryGuids []string
	Event         string
	ErrorContains string
}

// C-I5: replay is deliberately bounded to an explicit GUID set or one
// event/error signature. Payload-pruned deliveries remain parked and receive
// an explicit refusal reason; an explicit-GUID CLI replay consequently fails
// its selected-vs-requeued count check instead of dispatching a nil body.
func (q *Queries) RequeueParkedWebhookDeliveries(ctx context.Context, arg RequeueParkedWebhookDeliveriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, requeueParkedWebhookDeliveries, arg.DeliveryGuids, arg.Event, arg.ErrorContains)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setWebhookDeliveryResults = `-- name: SetWebhookDeliveryResults :execrows
UPDATE webhook_deliveries AS delivery
SET status = result.status,
    last_error = NULLIF(result.last_error, ''),
    next_attempt_at = CASE
        WHEN result.retry_delay_seconds IS NULL
        THEN delivery.next_attempt_at
        ELSE clock_timestamp() + make_interval(
            secs => result.retry_delay_seconds
        )
    END
FROM jsonb_to_recordset($1::jsonb)
    AS result(
        delivery_guid text,
        status text,
        last_error text,
        retry_delay_seconds int
    )
WHERE delivery.delivery_guid = result.delivery_guid
  AND delivery.status = 'processing'
`

// C-P2: finish the entire claimed batch with one set-based status update.
func (q *Queries) SetWebhookDeliveryResults(ctx context.Context, results []byte) (int64, error) {
	result, err := q.db.Exec(ctx, setWebhookDeliveryResults, results)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
